# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 ActivityDefinition resource.

Supports declaration of the ActivityDefinition metadata required by HL7 and other organizations that share and publish activity definitions with a focus on the aspects of that metadata that are important for post-publication activities including distribution, inclusion in repositories, consumption, and implementation.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Age, Attachment, BackboneElement, CodeableConcept, Coding, ContactDetail, Dosage, Duration, Expression, Extension, Identifier, Period, Quantity, Range, Reference, RelatedArtifact, Timing, UsageContext
from typing import Any, List, Optional

@dataclass
class ActivityDefinitionRelatedArtifact:
    """
    ActivityDefinitionRelatedArtifact nested class.
    """

    type: Optional[str] = None  # The type of relationship to the related artifact.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    classifier: Optional[List[CodeableConcept]] = field(default_factory=list)  # Provides additional classifiers of the related artifact.
    label: Optional[str] = None  # A short label that can be used to reference the citation from elsewhere in the containing artifac...
    display: Optional[str] = None  # A brief description of the document or knowledge resource being referenced, suitable for display ...
    citation: Optional[str] = None  # A bibliographic citation for the related artifact. This text SHOULD be formatted according to an ...
    document: Optional[Attachment] = None  # The document being referenced, represented as an attachment. This is exclusive with the resource ...
    resource: Optional[str] = None  # The related artifact, such as a library, value set, profile, or other knowledge resource.
    resourceReference: Optional[Reference] = None  # The related artifact, if the artifact is not a canonical resource, or a resource reference to a c...
    publicationStatus: Optional[str] = None  # The publication status of the artifact being referred to.
    publicationDate: Optional[str] = None  # The date of publication of the artifact being referred to.

@dataclass
class ActivityDefinitionParticipant:
    """
    ActivityDefinitionParticipant nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    type: Optional[str] = None  # The type of participant in the action.
    typeCanonical: Optional[str] = None  # The type of participant in the action.
    typeReference: Optional[Reference] = None  # The type of participant in the action.
    role: Optional[CodeableConcept] = None  # The role the participant should play in performing the described action.
    function: Optional[CodeableConcept] = None  # Indicates how the actor will be involved in the action - author, reviewer, witness, etc.

@dataclass
class ActivityDefinitionDynamicValue:
    """
    ActivityDefinitionDynamicValue nested class.
    """

    path: Optional[str] = None  # The path to the element to be customized. This is the path on the resource that will hold the res...
    expression: Optional[Expression] = None  # An expression specifying the value of the customized element.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...


@dataclass
class ActivityDefinition(FHIRResource):
    """
    Supports declaration of the ActivityDefinition metadata required by HL7 and other organizations that share and publish activity definitions with a focus on the aspects of that metadata that are important for post-publication activities including distribution, inclusion in repositories, consumption, and implementation.
    """

    url: Optional[str] = None  # An absolute URI that is used to identify this activity definition when it is referenced in a spec...
    version: Optional[str] = None  # The identifier that is used to identify this version of the activity definition when it is refere...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the activity definition.
    status: Optional[str] = None  # The status of this activity definition. Enables tracking the life-cycle of the content.
    experimental: Optional[bool] = None  # A Boolean value to indicate that this activity definition is authored for testing purposes (or ed...
    date: Optional[str] = None  # The date  (and optionally time) when the activity definition was last significantly changed.
    description: Optional[str] = None  # A free text natural language description of the activity definition from a consumer's perspective.
    resourceType: str = "ActivityDefinition"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this activity definition when it is represented in o...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    name: Optional[str] = None  # A natural language name identifying the activity definition. This name should be usable as an ide...
    subtitle: Optional[str] = None  # An explanatory or alternate title for the activity definition giving additional information about...
    subject: Optional[Any] = None  # A code, group definition, or canonical reference that describes  or identifies the intended subje...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the activity definition is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this activity definition is needed and why it has been designed as it has.
    usage: Optional[str] = None  # A detailed description of how the activity definition is used from a clinical perspective.
    copyright: Optional[str] = None  # A copyright statement relating to the activity definition and/or its contents. Copyright statemen...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the resource content was approved by the publisher. Approval happens once when ...
    lastReviewDate: Optional[str] = None  # The date on which the resource content was last reviewed. Review happens periodically after appro...
    effectivePeriod: Optional[Period] = None  # The period during which the activity definition content was or is planned to be in active use.
    topic: Optional[List[CodeableConcept]] = field(default_factory=list)  # Descriptive topics related to the content of the activity. Topics provide a high-level categoriza...
    author: Optional[List[ContactDetail]] = field(default_factory=list)  # An individiual or organization primarily involved in the creation and maintenance of the content.
    editor: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization primarily responsible for internal coherence of the content.
    reviewer: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be primarily responsible for review of...
    endorser: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be responsible for officially endorsin...
    relatedArtifact: Optional[List[RelatedArtifact]] = field(default_factory=list)  # Related artifacts such as additional documentation, justification, or bibliographic references.
    library: Optional[List[str]] = field(default_factory=list)  # A reference to a Library resource containing any formal logic used by the activity definition.
    kind: Optional[str] = None  # A description of the kind of resource the activity definition is representing. For example, a Med...
    profile: Optional[str] = None  # A profile to which the target of the activity definition is expected to conform.
    code: Optional[CodeableConcept] = None  # Detailed description of the type of activity; e.g. What lab test, what procedure, what kind of en...
    intent: Optional[str] = None  # Indicates the level of authority/intentionality associated with the activity and where the reques...
    priority: Optional[str] = None  # Indicates how quickly the activity  should be addressed with respect to other requests.
    doNotPerform: Optional[bool] = None  # Set this to true if the definition is to indicate that a particular activity should NOT be perfor...
    timing: Optional[Any] = None  # The timing or frequency upon which the described activity is to occur.
    asNeeded: Optional[Any] = None  # If a CodeableConcept is present, it indicates the pre-condition for performing the service.  For ...
    location: Optional[Any] = None  # Identifies the facility where the activity will occur; e.g. home, hospital, specific clinic, etc.
    participant: Optional[List[BackboneElement]] = field(default_factory=list)  # Indicates who should participate in performing the action described.
    product: Optional[Any] = None  # Identifies the food, drug or other product being consumed or supplied in the activity.
    quantity: Optional[Quantity] = None  # Identifies the quantity expected to be consumed at once (per dose, per meal, etc.).
    dosage: Optional[List[Dosage]] = field(default_factory=list)  # Provides detailed dosage instructions in the same way that they are described for MedicationReque...
    bodySite: Optional[List[CodeableConcept]] = field(default_factory=list)  # Indicates the sites on the subject's body where the procedure should be performed (I.e. the targe...
    specimenRequirement: Optional[List[str]] = field(default_factory=list)  # Defines specimen requirements for the action to be performed, such as required specimens for a la...
    observationRequirement: Optional[List[str]] = field(default_factory=list)  # Defines observation requirements for the action to be performed, such as body weight or surface a...
    observationResultRequirement: Optional[List[str]] = field(default_factory=list)  # Defines the observations that are expected to be produced by the action.
    transform: Optional[str] = None  # A reference to a StructureMap resource that defines a transform that can be executed to produce t...
    dynamicValue: Optional[List[BackboneElement]] = field(default_factory=list)  # Dynamic values that will be evaluated to produce values for elements of the resulting resource. F...