# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 Bundle resource.

This profile holds all the requirements and constraints related to a FHIR batch bundle.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource, Resource
from dnhealth.dnhealth_fhir.types import BackboneElement, Extension, Identifier, Signature
from typing import Any, List, Optional

@dataclass
class BundleLink:
    """
    BundleLink nested class.
    """

    relation: Optional[str] = None  # A name which details the functional use for this link - see [http://www.iana.org/assignments/link...
    url: Optional[str] = None  # The reference details for the link.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class BundleEntry:
    """
    BundleEntry nested class.
    """

    method: Optional[str] = None  # In a transaction or batch, this is the HTTP action to be executed for this entry. In a history bu...
    url: Optional[str] = None  # The URL for this entry, relative to the root (the address to which the request is posted).
    status: Optional[str] = None  # The status code returned by processing this entry. The status SHALL start with a 3 digit HTTP cod...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    link: Optional[List[Any]] = field(default_factory=list)  # A series of links that provide context to this entry.
    fullUrl: Optional[str] = None  # The Absolute URL for the resource. Except for transactions and batches, each entry in a Bundle mu...
    resource: Optional[Resource] = None  # The Resource for the entry. The purpose/meaning of the resource is determined by the Bundle.type....
    search: Optional[BackboneElement] = None  # Information about the search process that lead to the creation of this entry.
    mode: Optional[str] = None  # Why this entry is in the result set - whether it's included as a match or because of an _include ...
    score: Optional[float] = None  # When searching, the server's search ranking score for the entry.
    request: Optional[BackboneElement] = None  # Additional information about how this entry should be processed as part of a transaction or batch...
    ifNoneMatch: Optional[str] = None  # If the ETag values match, return a 304 Not Modified status. See the API documentation for [\"Cond...
    ifModifiedSince: Optional[str] = None  # Only perform the operation if the last updated date matches. See the API documentation for [\"Con...
    ifMatch: Optional[str] = None  # Only perform the operation if the Etag value matches. For more information, see the API section [...
    ifNoneExist: Optional[str] = None  # Instruct the server not to perform the create if a specified resource already exists. For further...
    response: Optional[BackboneElement] = None  # Indicates the results of processing the corresponding 'request' entry in the batch or transaction...
    location: Optional[str] = None  # The location header created by processing this operation, populated if the operation returns a lo...
    etag: Optional[str] = None  # The Etag for the resource, if the operation for the entry produced a versioned resource (see [Res...
    lastModified: Optional[str] = None  # The date/time that the resource was modified on the server.
    outcome: Optional[Resource] = None  # An OperationOutcome containing hints and warnings produced as part of processing this entry in a ...

@dataclass
class BundleEntrySearch:
    """
    BundleEntrySearch nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    mode: Optional[str] = None  # Why this entry is in the result set - whether it's included as a match or because of an _include ...
    score: Optional[float] = None  # When searching, the server's search ranking score for the entry.

@dataclass
class BundleEntryRequest:
    """
    BundleEntryRequest nested class.
    """

    method: Optional[str] = None  # In a transaction or batch, this is the HTTP action to be executed for this entry. In a history bu...
    url: Optional[str] = None  # The URL for this entry, relative to the root (the address to which the request is posted).
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    ifNoneMatch: Optional[str] = None  # If the ETag values match, return a 304 Not Modified status. See the API documentation for [\"Cond...
    ifModifiedSince: Optional[str] = None  # Only perform the operation if the last updated date matches. See the API documentation for [\"Con...
    ifMatch: Optional[str] = None  # Only perform the operation if the Etag value matches. For more information, see the API section [...
    ifNoneExist: Optional[str] = None  # Instruct the server not to perform the create if a specified resource already exists. For further...

@dataclass
class BundleEntryResponse:
    """
    BundleEntryResponse nested class.
    """

    status: Optional[str] = None  # The status code returned by processing this entry. The status SHALL start with a 3 digit HTTP cod...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    location: Optional[str] = None  # The location header created by processing this operation, populated if the operation returns a lo...
    etag: Optional[str] = None  # The Etag for the resource, if the operation for the entry produced a versioned resource (see [Res...
    lastModified: Optional[str] = None  # The date/time that the resource was modified on the server.
    outcome: Optional[Resource] = None  # An OperationOutcome containing hints and warnings produced as part of processing this entry in a ...


@dataclass
class Bundle(FHIRResource):
    """
    This profile holds all the requirements and constraints related to a FHIR batch bundle.
    """

    type: Optional[str] = None  # Indicates the purpose of this bundle - how it is intended to be used.
    resourceType: str = "Bundle"
    identifier: Optional[Identifier] = None  # A persistent identifier for the bundle that won't change as a bundle is copied from server to ser...
    timestamp: Optional[str] = None  # The date/time that the bundle was assembled - i.e. when the resources were placed in the bundle.
    total: Optional[int] = None  # If a set of search matches, this is the (potentially estimated) total number of entries of type '...
    link: Optional[List[BackboneElement]] = field(default_factory=list)  # A series of links that provide context to this bundle.
    entry: Optional[List[BackboneElement]] = field(default_factory=list)  # An entry in a bundle resource - will either contain a resource or information about a resource (t...
    signature: Optional[Signature] = None  # Digital Signature - base64 encoded. XML-DSig or a JWS.
    issues: Optional[Resource] = None  # Captures issues and warnings that relate to the construction of the Bundle and the content within...