# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 CapabilityStatement resource.

A Capability Statement documents a set of capabilities (behaviors) of a FHIR Server or Client for a particular version of FHIR that may be used as a statement of actual server functionality or a statement of required or desired server implementation.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Coding, ContactDetail, Extension, Identifier, Reference, UsageContext
from typing import Any, List, Optional

@dataclass
class CapabilityStatementSoftware:
    """
    CapabilityStatementSoftware nested class.
    """

    name: Optional[str] = None  # Name the software is known by.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    version: Optional[str] = None  # The version identifier for the software covered by this statement.
    releaseDate: Optional[str] = None  # Date this version of the software was released.

@dataclass
class CapabilityStatementImplementation:
    """
    CapabilityStatementImplementation nested class.
    """

    description: Optional[str] = None  # Information about the specific installation that this capability statement relates to.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    url: Optional[str] = None  # An absolute base URL for the implementation.  This forms the base for REST interfaces as well as ...
    custodian: Optional[Reference] = None  # The organization responsible for the management of the instance and oversight of the data on the ...

@dataclass
class CapabilityStatementRest:
    """
    CapabilityStatementRest nested class.
    """

    mode: Optional[str] = None  # Identifies whether this portion of the statement is describing the ability to initiate or receive...
    type: Optional[str] = None  # A type of resource exposed via the restful interface.
    code: Optional[str] = None  # Coded identifier of the operation, supported by the system resource.
    name: Optional[str] = None  # The label used for the search parameter in this particular system's API - i.e. the 'name' portion...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    documentation: Optional[str] = None  # Information about the system's restful capabilities that apply across all applications, such as s...
    security: Optional[BackboneElement] = None  # Information about security implementation from an interface perspective - what a client needs to ...
    cors: Optional[bool] = None  # Server adds CORS headers when responding to requests - this enables Javascript applications to us...
    service: Optional[List[CodeableConcept]] = field(default_factory=list)  # Types of security services that are supported/required by the system.
    description: Optional[str] = None  # General description of how security works.
    resource: Optional[List[BackboneElement]] = field(default_factory=list)  # A specification of the restful capabilities of the solution for a specific resource type.
    profile: Optional[str] = None  # A system-wide profile that is applied across *all* instances of the resource supported by the sys...
    supportedProfile: Optional[List[str]] = field(default_factory=list)  # A list of profiles representing different use cases the system hosts/produces. A supported profil...
    interaction: Optional[List[BackboneElement]] = field(default_factory=list)  # Identifies a restful operation supported by the solution.
    versioning: Optional[str] = None  # This field is set to no-version to specify that the system does not support (server) or use (clie...
    readHistory: Optional[bool] = None  # A flag for whether the server is able to return past versions as part of the vRead operation.
    updateCreate: Optional[bool] = None  # A flag to indicate that the server allows or needs to allow the client to create new identities o...
    conditionalCreate: Optional[bool] = None  # A flag that indicates that the server supports conditional create.
    conditionalRead: Optional[str] = None  # A code that indicates how the server supports conditional read.
    conditionalUpdate: Optional[bool] = None  # A flag that indicates that the server supports conditional update.
    conditionalPatch: Optional[bool] = None  # A flag that indicates that the server supports conditional patch.
    conditionalDelete: Optional[str] = None  # A code that indicates how the server supports conditional delete.
    referencePolicy: Optional[List[str]] = field(default_factory=list)  # A set of flags that defines how references are supported.
    searchInclude: Optional[List[str]] = field(default_factory=list)  # A list of _include values supported by the server.
    searchRevInclude: Optional[List[str]] = field(default_factory=list)  # A list of _revinclude (reverse include) values supported by the server.
    searchParam: Optional[List[BackboneElement]] = field(default_factory=list)  # Search parameters for implementations to support and/or make use of - either references to ones d...
    definition: Optional[str] = None  # An absolute URI that is a formal reference to where this parameter was first defined, so that a c...
    operation: Optional[List[BackboneElement]] = field(default_factory=list)  # Definition of an operation or a named query together with its parameters and their meaning and ty...
    compartment: Optional[List[str]] = field(default_factory=list)  # An absolute URI which is a reference to the definition of a compartment that the system supports....

@dataclass
class CapabilityStatementRestSecurity:
    """
    CapabilityStatementRestSecurity nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    cors: Optional[bool] = None  # Server adds CORS headers when responding to requests - this enables Javascript applications to us...
    service: Optional[List[CodeableConcept]] = field(default_factory=list)  # Types of security services that are supported/required by the system.
    description: Optional[str] = None  # General description of how security works.

@dataclass
class CapabilityStatementRestResource:
    """
    CapabilityStatementRestResource nested class.
    """

    type: Optional[str] = None  # A type of resource exposed via the restful interface.
    code: Optional[str] = None  # Coded identifier of the operation, supported by the system resource.
    name: Optional[str] = None  # The label used for the search parameter in this particular system's API - i.e. the 'name' portion...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    profile: Optional[str] = None  # A system-wide profile that is applied across *all* instances of the resource supported by the sys...
    supportedProfile: Optional[List[str]] = field(default_factory=list)  # A list of profiles representing different use cases the system hosts/produces. A supported profil...
    documentation: Optional[str] = None  # Additional information about the resource type used by the system.
    interaction: Optional[List[BackboneElement]] = field(default_factory=list)  # Identifies a restful operation supported by the solution.
    versioning: Optional[str] = None  # This field is set to no-version to specify that the system does not support (server) or use (clie...
    readHistory: Optional[bool] = None  # A flag for whether the server is able to return past versions as part of the vRead operation.
    updateCreate: Optional[bool] = None  # A flag to indicate that the server allows or needs to allow the client to create new identities o...
    conditionalCreate: Optional[bool] = None  # A flag that indicates that the server supports conditional create.
    conditionalRead: Optional[str] = None  # A code that indicates how the server supports conditional read.
    conditionalUpdate: Optional[bool] = None  # A flag that indicates that the server supports conditional update.
    conditionalPatch: Optional[bool] = None  # A flag that indicates that the server supports conditional patch.
    conditionalDelete: Optional[str] = None  # A code that indicates how the server supports conditional delete.
    referencePolicy: Optional[List[str]] = field(default_factory=list)  # A set of flags that defines how references are supported.
    searchInclude: Optional[List[str]] = field(default_factory=list)  # A list of _include values supported by the server.
    searchRevInclude: Optional[List[str]] = field(default_factory=list)  # A list of _revinclude (reverse include) values supported by the server.
    searchParam: Optional[List[BackboneElement]] = field(default_factory=list)  # Search parameters for implementations to support and/or make use of - either references to ones d...
    definition: Optional[str] = None  # An absolute URI that is a formal reference to where this parameter was first defined, so that a c...
    operation: Optional[List[BackboneElement]] = field(default_factory=list)  # Definition of an operation or a named query together with its parameters and their meaning and ty...

@dataclass
class CapabilityStatementRestResourceInteraction:
    """
    CapabilityStatementRestResourceInteraction nested class.
    """

    code: Optional[str] = None  # Coded identifier of the operation, supported by the system resource.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    documentation: Optional[str] = None  # Guidance specific to the implementation of this operation, such as 'delete is a logical delete' o...

@dataclass
class CapabilityStatementRestResourceSearchParam:
    """
    CapabilityStatementRestResourceSearchParam nested class.
    """

    name: Optional[str] = None  # The label used for the search parameter in this particular system's API - i.e. the 'name' portion...
    type: Optional[str] = None  # The type of value a search parameter refers to, and how the content is interpreted.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    definition: Optional[str] = None  # An absolute URI that is a formal reference to where this parameter was first defined, so that a c...
    documentation: Optional[str] = None  # This allows documentation of any distinct behaviors about how the search parameter is used.  For ...

@dataclass
class CapabilityStatementRestResourceOperation:
    """
    CapabilityStatementRestResourceOperation nested class.
    """

    name: Optional[str] = None  # The name of the operation or query. For an operation, this name is prefixed with $ and used in th...
    definition: Optional[str] = None  # Where the formal definition can be found. If a server references the base definition of an Operat...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    documentation: Optional[str] = None  # Documentation that describes anything special about the operation behavior, possibly detailing di...

@dataclass
class CapabilityStatementRestInteraction:
    """
    CapabilityStatementRestInteraction nested class.
    """

    code: Optional[str] = None  # A coded identifier of the operation, supported by the system.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    documentation: Optional[str] = None  # Guidance specific to the implementation of this operation, such as limitations on the kind of tra...

@dataclass
class CapabilityStatementMessaging:
    """
    CapabilityStatementMessaging nested class.
    """

    protocol: Optional[Coding] = None  # A list of the messaging transport protocol(s) identifiers, supported by this endpoint.
    address: Optional[str] = None  # The network address of the endpoint. For solutions that do not use network addresses for routing,...
    mode: Optional[str] = None  # The mode of this event declaration - whether application is sender or receiver.
    definition: Optional[str] = None  # Points to a message definition that identifies the messaging event, message structure, allowed re...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    endpoint: Optional[List[BackboneElement]] = field(default_factory=list)  # An endpoint (network accessible address) to which messages and/or replies are to be sent.
    reliableCache: Optional[int] = None  # Length if the receiver's reliable messaging cache in minutes (if a receiver) or how long the cach...
    documentation: Optional[str] = None  # Documentation about the system's messaging capabilities for this endpoint not otherwise documente...
    supportedMessage: Optional[List[BackboneElement]] = field(default_factory=list)  # References to message definitions for messages this system can send or receive.

@dataclass
class CapabilityStatementMessagingEndpoint:
    """
    CapabilityStatementMessagingEndpoint nested class.
    """

    protocol: Optional[Coding] = None  # A list of the messaging transport protocol(s) identifiers, supported by this endpoint.
    address: Optional[str] = None  # The network address of the endpoint. For solutions that do not use network addresses for routing,...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class CapabilityStatementMessagingSupportedMessage:
    """
    CapabilityStatementMessagingSupportedMessage nested class.
    """

    mode: Optional[str] = None  # The mode of this event declaration - whether application is sender or receiver.
    definition: Optional[str] = None  # Points to a message definition that identifies the messaging event, message structure, allowed re...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class CapabilityStatementDocument:
    """
    CapabilityStatementDocument nested class.
    """

    mode: Optional[str] = None  # Mode of this document declaration - whether an application is a producer or consumer.
    profile: Optional[str] = None  # A profile on the document Bundle that constrains which resources are present, and their contents.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    documentation: Optional[str] = None  # A description of how the application supports or uses the specified document profile.  For exampl...


@dataclass
class CapabilityStatement(FHIRResource):
    """
    A Capability Statement documents a set of capabilities (behaviors) of a FHIR Server or Client for a particular version of FHIR that may be used as a statement of actual server functionality or a statement of required or desired server implementation.
    """

    status: Optional[str] = None  # The status of this capability statement. Enables tracking the life-cycle of the content.
    date: Optional[str] = None  # The date  (and optionally time) when the capability statement was last significantly changed. The...
    kind: Optional[str] = None  # The way that this statement is intended to be used, to describe an actual running instance of sof...
    fhirVersion: Optional[str] = None  # The version of the FHIR specification that this CapabilityStatement describes (which SHALL be the...
    format: List[str] = field(default_factory=list)  # A list of the formats supported by this implementation using their content types.
    resourceType: str = "CapabilityStatement"
    url: Optional[str] = None  # An absolute URI that is used to identify this capability statement when it is referenced in a spe...
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this CapabilityStatement when it is represented in o...
    version: Optional[str] = None  # The identifier that is used to identify this version of the capability statement when it is refer...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    name: Optional[str] = None  # A natural language name identifying the capability statement. This name should be usable as an id...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the capability statement.
    experimental: Optional[bool] = None  # A Boolean value to indicate that this capability statement is authored for testing purposes (or e...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    description: Optional[str] = None  # A free text natural language description of the capability statement from a consumer's perspectiv...
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the capability statement is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this capability statement is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the capability statement and/or its contents. Copyright stateme...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    instantiates: Optional[List[str]] = field(default_factory=list)  # Reference to a canonical URL of another CapabilityStatement that this software implements. This c...
    imports: Optional[List[str]] = field(default_factory=list)  # Reference to a canonical URL of another CapabilityStatement that this software adds to. The capab...
    software: Optional[BackboneElement] = None  # Software that is covered by this capability statement.  It is used when the capability statement ...
    implementation: Optional[BackboneElement] = None  # Identifies a specific implementation instance that is described by the capability statement - i.e...
    patchFormat: Optional[List[str]] = field(default_factory=list)  # A list of the patch formats supported by this implementation using their content types.
    acceptLanguage: Optional[List[str]] = field(default_factory=list)  # A list of the languages supported by this implementation that are usefully supported in the ```Ac...
    implementationGuide: Optional[List[str]] = field(default_factory=list)  # A list of implementation guides that the server does (or should) support in their entirety.
    rest: Optional[List[BackboneElement]] = field(default_factory=list)  # A definition of the restful capabilities of the solution, if any.
    messaging: Optional[List[BackboneElement]] = field(default_factory=list)  # A description of the messaging capabilities of the solution.
    document: Optional[List[BackboneElement]] = field(default_factory=list)  # A document definition.