# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 ChargeItemDefinition resource.

The ChargeItemDefinition resource provides the properties that apply to the (billing) codes necessary to calculate costs and prices. The properties may differ largely depending on type and realm, therefore this resource gives only a rough structure and requires profiling for each type of billing code system.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Coding, ContactDetail, Expression, Extension, Identifier, Period, Reference, RelatedArtifact, UsageContext
from typing import Any, List, Optional

@dataclass
class ChargeItemDefinitionApplicability:
    """
    ChargeItemDefinitionApplicability nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    condition: Optional[Expression] = None  # An expression that returns true or false, indicating whether the condition is satisfied. When usi...
    effectivePeriod: Optional[Period] = None  # The period during which the charge item definition content was or is planned to be in active use.
    relatedArtifact: Optional[RelatedArtifact] = None  # Reference to / quotation of the external source of the group of properties.

@dataclass
class ChargeItemDefinitionPropertyGroup:
    """
    ChargeItemDefinitionPropertyGroup nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    applicability: Optional[List[Any]] = field(default_factory=list)  # Expressions that describe applicability criteria for the priceComponent.
    priceComponent: Optional[List[Any]] = field(default_factory=list)  # The price for a ChargeItem may be calculated as a base price with surcharges/deductions that appl...


@dataclass
class ChargeItemDefinition(FHIRResource):
    """
    The ChargeItemDefinition resource provides the properties that apply to the (billing) codes necessary to calculate costs and prices. The properties may differ largely depending on type and realm, therefore this resource gives only a rough structure and requires profiling for each type of billing code system.
    """

    status: Optional[str] = None  # The current state of the ChargeItemDefinition.
    resourceType: str = "ChargeItemDefinition"
    url: Optional[str] = None  # An absolute URI that is used to identify this charge item definition when it is referenced in a s...
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this charge item definition when it is represented i...
    version: Optional[str] = None  # The identifier that is used to identify this version of the charge item definition when it is ref...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    name: Optional[str] = None  # A natural language name identifying the ChargeItemDefinition. This name should be usable as an id...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the charge item definition.
    derivedFromUri: Optional[List[str]] = field(default_factory=list)  # The URL pointing to an externally-defined charge item definition that is adhered to in whole or i...
    partOf: Optional[List[str]] = field(default_factory=list)  # A larger definition of which this particular definition is a component or step.
    replaces: Optional[List[str]] = field(default_factory=list)  # As new versions of a protocol or guideline are defined, allows identification of what versions ar...
    experimental: Optional[bool] = None  # A Boolean value to indicate that this charge item definition is authored for testing purposes (or...
    date: Optional[str] = None  # The date  (and optionally time) when the charge item definition was last significantly changed. T...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    description: Optional[str] = None  # A free text natural language description of the charge item definition from a consumer's perspect...
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the charge item definition is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this charge item definition is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the charge item definition and/or its contents. Copyright state...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the resource content was approved by the publisher. Approval happens once when ...
    lastReviewDate: Optional[str] = None  # The date on which the resource content was last reviewed. Review happens periodically after appro...
    code: Optional[CodeableConcept] = None  # The defined billing details in this resource pertain to the given billing code.
    instance: Optional[List[Reference]] = field(default_factory=list)  # The defined billing details in this resource pertain to the given product instance(s).
    applicability: Optional[List[BackboneElement]] = field(default_factory=list)  # Expressions that describe applicability criteria for the billing code.
    propertyGroup: Optional[List[BackboneElement]] = field(default_factory=list)  # Group of properties which are applicable under the same conditions. If no applicability rules are...