# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 Claim resource.

A provider issued list of professional services and products which have been provided, or are to be provided, to a patient which is sent to an insurer for reimbursement.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Address, Attachment, BackboneElement, CodeableConcept, Extension, Identifier, Money, Period, Quantity, Reference
from typing import Any, List, Optional

@dataclass
class ClaimRelated:
    """
    ClaimRelated nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    claim: Optional[Reference] = None  # Reference to a related claim.
    relationship: Optional[CodeableConcept] = None  # A code to convey how the claims are related.
    reference: Optional[Identifier] = None  # An alternate organizational reference to the case or file to which this particular claim pertains.

@dataclass
class ClaimPayee:
    """
    ClaimPayee nested class.
    """

    type: Optional[CodeableConcept] = None  # Type of Party to be reimbursed: subscriber, provider, other.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    party: Optional[Reference] = None  # Reference to the individual or organization to whom any payment will be made.

@dataclass
class ClaimEvent:
    """
    ClaimEvent nested class.
    """

    type: Optional[CodeableConcept] = None  # A coded event such as when a service is expected or a card printed.
    when: Optional[Any] = None  # A date or period in the past or future indicating when the event occurred or is expectd to occur.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class ClaimCareTeam:
    """
    ClaimCareTeam nested class.
    """

    sequence: Optional[int] = None  # A number to uniquely identify care team entries.
    provider: Optional[Reference] = None  # Member of the team who provided the product or service.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    responsible: Optional[bool] = None  # The party who is billing and/or responsible for the claimed products or services.
    role: Optional[CodeableConcept] = None  # The lead, assisting or supervising practitioner and their discipline if a multidisciplinary team.
    specialty: Optional[CodeableConcept] = None  # The specialization of the practitioner or provider which is applicable for this service.

@dataclass
class ClaimSupportingInfo:
    """
    ClaimSupportingInfo nested class.
    """

    sequence: Optional[int] = None  # A number to uniquely identify supporting information entries.
    category: Optional[CodeableConcept] = None  # The general class of the information supplied: information; exception; accident, employment; onse...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    code: Optional[CodeableConcept] = None  # System and code pertaining to the specific information regarding special conditions relating to t...
    timing: Optional[Any] = None  # The date when or period to which this information refers.
    value: Optional[Any] = None  # Additional data or information such as resources, documents, images etc. including references to ...
    reason: Optional[CodeableConcept] = None  # Provides the reason in the situation where a reason code is required in addition to the content.

@dataclass
class ClaimDiagnosis:
    """
    ClaimDiagnosis nested class.
    """

    sequence: Optional[int] = None  # A number to uniquely identify diagnosis entries.
    diagnosis: Optional[Any] = None  # The nature of illness or problem in a coded form or as a reference to an external defined Condition.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    type: Optional[List[CodeableConcept]] = field(default_factory=list)  # When the condition was observed or the relative ranking.
    onAdmission: Optional[CodeableConcept] = None  # Indication of whether the diagnosis was present on admission to a facility.

@dataclass
class ClaimProcedure:
    """
    ClaimProcedure nested class.
    """

    sequence: Optional[int] = None  # A number to uniquely identify procedure entries.
    procedure: Optional[Any] = None  # The code or reference to a Procedure resource which identifies the clinical intervention performed.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    type: Optional[List[CodeableConcept]] = field(default_factory=list)  # When the condition was observed or the relative ranking.
    date: Optional[str] = None  # Date and optionally time the procedure was performed.
    udi: Optional[List[Reference]] = field(default_factory=list)  # Unique Device Identifiers associated with this line item.

@dataclass
class ClaimInsurance:
    """
    ClaimInsurance nested class.
    """

    sequence: Optional[int] = None  # A number to uniquely identify insurance entries and provide a sequence of coverages to convey coo...
    focal: Optional[bool] = None  # A flag to indicate that this Coverage is to be used for adjudication of this claim when set to true.
    coverage: Optional[Reference] = None  # Reference to the insurance card level information contained in the Coverage resource. The coverag...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    identifier: Optional[Identifier] = None  # The business identifier to be used when the claim is sent for adjudication against this insurance...
    businessArrangement: Optional[str] = None  # A business agreement number established between the provider and the insurer for special business...
    preAuthRef: Optional[List[str]] = field(default_factory=list)  # Reference numbers previously provided by the insurer to the provider to be quoted on subsequent c...
    claimResponse: Optional[Reference] = None  # The result of the adjudication of the line items for the Coverage specified in this insurance.

@dataclass
class ClaimAccident:
    """
    ClaimAccident nested class.
    """

    date: Optional[str] = None  # Date of an accident event  related to the products and services contained in the claim.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    type: Optional[CodeableConcept] = None  # The type or context of the accident event for the purposes of selection of potential insurance co...
    location: Optional[Any] = None  # The physical location of the accident event.

@dataclass
class ClaimItem:
    """
    ClaimItem nested class.
    """

    sequence: Optional[int] = None  # A number to uniquely identify item entries.
    site: List[Any] = field(default_factory=list)  # Physical service site on the patient (limb, tooth, etc.).
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    traceNumber: Optional[List[Identifier]] = field(default_factory=list)  # Trace number for tracking purposes. May be defined at the jurisdiction level or between trading p...
    careTeamSequence: Optional[List[int]] = field(default_factory=list)  # CareTeam members related to this service or product.
    diagnosisSequence: Optional[List[int]] = field(default_factory=list)  # Diagnosis applicable for this service or product.
    procedureSequence: Optional[List[int]] = field(default_factory=list)  # Procedures applicable for this service or product.
    informationSequence: Optional[List[int]] = field(default_factory=list)  # Exceptions, special conditions and supporting information applicable for this service or product.
    revenue: Optional[CodeableConcept] = None  # The type of revenue or cost center providing the product and/or service.
    category: Optional[CodeableConcept] = None  # Code to identify the general type of benefits under which products and services are provided.
    productOrService: Optional[CodeableConcept] = None  # When the value is a group code then this item collects a set of related item details, otherwise t...
    productOrServiceEnd: Optional[CodeableConcept] = None  # This contains the end of a range of product, service, drug or other billing codes for the item. T...
    request: Optional[List[Reference]] = field(default_factory=list)  # Request or Referral for Goods or Service to be rendered.
    modifier: Optional[List[CodeableConcept]] = field(default_factory=list)  # Item typification or modifiers codes to convey additional context for the product or service.
    programCode: Optional[List[CodeableConcept]] = field(default_factory=list)  # Identifies the program under which this may be recovered.
    serviced: Optional[Any] = None  # The date or dates when the service or product was supplied, performed or completed.
    location: Optional[Any] = None  # Where the product or service was provided.
    patientPaid: Optional[Money] = None  # The amount paid by the patient, in total at the claim claim level or specifically for the item an...
    quantity: Optional[Quantity] = None  # The number of repetitions of a service or product.
    unitPrice: Optional[Money] = None  # If the item is not a group then this is the fee for the product or service, otherwise this is the...
    factor: Optional[float] = None  # A real number that represents a multiplier used in determining the overall value of services deli...
    tax: Optional[Money] = None  # The total of taxes applicable for this product or service.
    net: Optional[Money] = None  # The total amount claimed for the group (if a grouper) or the line item. Net = unit price * quanti...
    udi: Optional[List[Reference]] = field(default_factory=list)  # Unique Device Identifiers associated with this line item.
    bodySite: Optional[List[BackboneElement]] = field(default_factory=list)  # Physical location where the service is performed or applies.
    subSite: Optional[List[CodeableConcept]] = field(default_factory=list)  # A region or surface of the bodySite, e.g. limb region or tooth surface(s).
    encounter: Optional[List[Reference]] = field(default_factory=list)  # Healthcare encounters related to this claim.
    detail: Optional[List[BackboneElement]] = field(default_factory=list)  # A claim detail line. Either a simple (a product or service) or a 'group' of sub-details which are...
    subDetail: Optional[List[BackboneElement]] = field(default_factory=list)  # A claim detail line. Either a simple (a product or service) or a 'group' of sub-details which are...

@dataclass
class ClaimItemBodySite:
    """
    ClaimItemBodySite nested class.
    """

    site: List[Any] = field(default_factory=list)  # Physical service site on the patient (limb, tooth, etc.).
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    subSite: Optional[List[CodeableConcept]] = field(default_factory=list)  # A region or surface of the bodySite, e.g. limb region or tooth surface(s).

@dataclass
class ClaimItemDetail:
    """
    ClaimItemDetail nested class.
    """

    sequence: Optional[int] = None  # A number to uniquely identify item entries.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    traceNumber: Optional[List[Identifier]] = field(default_factory=list)  # Trace number for tracking purposes. May be defined at the jurisdiction level or between trading p...
    revenue: Optional[CodeableConcept] = None  # The type of revenue or cost center providing the product and/or service.
    category: Optional[CodeableConcept] = None  # Code to identify the general type of benefits under which products and services are provided.
    productOrService: Optional[CodeableConcept] = None  # When the value is a group code then this item collects a set of related item details, otherwise t...
    productOrServiceEnd: Optional[CodeableConcept] = None  # This contains the end of a range of product, service, drug or other billing codes for the item. T...
    modifier: Optional[List[CodeableConcept]] = field(default_factory=list)  # Item typification or modifiers codes to convey additional context for the product or service.
    programCode: Optional[List[CodeableConcept]] = field(default_factory=list)  # Identifies the program under which this may be recovered.
    patientPaid: Optional[Money] = None  # The amount paid by the patient, in total at the claim claim level or specifically for the item an...
    quantity: Optional[Quantity] = None  # The number of repetitions of a service or product.
    unitPrice: Optional[Money] = None  # If the item is not a group then this is the fee for the product or service, otherwise this is the...
    factor: Optional[float] = None  # A real number that represents a multiplier used in determining the overall value of services deli...
    tax: Optional[Money] = None  # The total of taxes applicable for this product or service.
    net: Optional[Money] = None  # The total amount claimed for the group (if a grouper) or the line item.detail. Net = unit price *...
    udi: Optional[List[Reference]] = field(default_factory=list)  # Unique Device Identifiers associated with this line item.
    subDetail: Optional[List[BackboneElement]] = field(default_factory=list)  # A claim detail line. Either a simple (a product or service) or a 'group' of sub-details which are...

@dataclass
class ClaimItemDetailSubDetail:
    """
    ClaimItemDetailSubDetail nested class.
    """

    sequence: Optional[int] = None  # A number to uniquely identify item entries.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    traceNumber: Optional[List[Identifier]] = field(default_factory=list)  # Trace number for tracking purposes. May be defined at the jurisdiction level or between trading p...
    revenue: Optional[CodeableConcept] = None  # The type of revenue or cost center providing the product and/or service.
    category: Optional[CodeableConcept] = None  # Code to identify the general type of benefits under which products and services are provided.
    productOrService: Optional[CodeableConcept] = None  # When the value is a group code then this item collects a set of related item details, otherwise t...
    productOrServiceEnd: Optional[CodeableConcept] = None  # This contains the end of a range of product, service, drug or other billing codes for the item. T...
    modifier: Optional[List[CodeableConcept]] = field(default_factory=list)  # Item typification or modifiers codes to convey additional context for the product or service.
    programCode: Optional[List[CodeableConcept]] = field(default_factory=list)  # Identifies the program under which this may be recovered.
    patientPaid: Optional[Money] = None  # The amount paid by the patient, in total at the claim claim level or specifically for the item an...
    quantity: Optional[Quantity] = None  # The number of repetitions of a service or product.
    unitPrice: Optional[Money] = None  # If the item is not a group then this is the fee for the product or service, otherwise this is the...
    factor: Optional[float] = None  # A real number that represents a multiplier used in determining the overall value of services deli...
    tax: Optional[Money] = None  # The total of taxes applicable for this product or service.
    net: Optional[Money] = None  # The total amount claimed for line item.detail.subDetail. Net = unit price * quantity * factor.
    udi: Optional[List[Reference]] = field(default_factory=list)  # Unique Device Identifiers associated with this line item.


@dataclass
class Claim(FHIRResource):
    """
    A provider issued list of professional services and products which have been provided, or are to be provided, to a patient which is sent to an insurer for reimbursement.
    """

    status: Optional[str] = None  # The status of the resource instance.
    type: Optional[CodeableConcept] = None  # The category of claim, e.g. oral, pharmacy, vision, institutional, professional.
    use: Optional[str] = None  # A code to indicate whether the nature of the request is: Claim - A request to an Insurer to adjud...
    patient: Optional[Reference] = None  # The party to whom the professional services and/or products have been supplied or are being consi...
    created: Optional[str] = None  # The date this resource was created.
    resourceType: str = "Claim"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A unique identifier assigned to this claim.
    traceNumber: Optional[List[Identifier]] = field(default_factory=list)  # Trace number for tracking purposes. May be defined at the jurisdiction level or between trading p...
    subType: Optional[CodeableConcept] = None  # A finer grained suite of claim type codes which may convey additional information such as Inpatie...
    billablePeriod: Optional[Period] = None  # The period for which charges are being submitted.
    enterer: Optional[Reference] = None  # Individual who created the claim, predetermination or preauthorization.
    insurer: Optional[Reference] = None  # The Insurer who is target of the request.
    provider: Optional[Reference] = None  # The provider which is responsible for the claim, predetermination or preauthorization.
    priority: Optional[CodeableConcept] = None  # The provider-required urgency of processing the request. Typical values include: stat, normal, de...
    fundsReserve: Optional[CodeableConcept] = None  # A code to indicate whether and for whom funds are to be reserved for future claims.
    related: Optional[List[BackboneElement]] = field(default_factory=list)  # Other claims which are related to this claim such as prior submissions or claims for related serv...
    prescription: Optional[Reference] = None  # Prescription is the document/authorization given to the claim author for them to provide products...
    originalPrescription: Optional[Reference] = None  # Original prescription which has been superseded by this prescription to support the dispensing of...
    payee: Optional[BackboneElement] = None  # The party to be reimbursed for cost of the products and services according to the terms of the po...
    referral: Optional[Reference] = None  # The referral information received by the claim author, it is not to be used when the author gener...
    encounter: Optional[List[Reference]] = field(default_factory=list)  # Healthcare encounters related to this claim.
    facility: Optional[Reference] = None  # Facility where the services were provided.
    diagnosisRelatedGroup: Optional[CodeableConcept] = None  # A package billing code or bundle code used to group products and services to a particular health ...
    event: Optional[List[BackboneElement]] = field(default_factory=list)  # Information code for an event with a corresponding date or period.
    careTeam: Optional[List[BackboneElement]] = field(default_factory=list)  # The members of the team who provided the products and services.
    supportingInfo: Optional[List[BackboneElement]] = field(default_factory=list)  # Additional information codes regarding exceptions, special considerations, the condition, situati...
    diagnosis: Optional[List[BackboneElement]] = field(default_factory=list)  # Information about diagnoses relevant to the claim items.
    procedure: Optional[List[BackboneElement]] = field(default_factory=list)  # Procedures performed on the patient relevant to the billing items with the claim.
    insurance: Optional[List[BackboneElement]] = field(default_factory=list)  # Financial instruments for reimbursement for the health care products and services specified on th...
    accident: Optional[BackboneElement] = None  # Details of an accident which resulted in injuries which required the products and services listed...
    patientPaid: Optional[Money] = None  # The amount paid by the patient, in total at the claim claim level or specifically for the item an...
    item: Optional[List[BackboneElement]] = field(default_factory=list)  # A claim line. Either a simple  product or service or a 'group' of details which can each be a sim...
    total: Optional[Money] = None  # The total value of the all the items in the claim.