# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 CodeSystem resource.

Defines and enforces the minimum expectations for publication and distribution of a code system, typically as part of an artifact repository or implementation guide publication
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Coding, ContactDetail, Extension, Identifier, Period, RelatedArtifact, UsageContext
from typing import Any, List, Optional

@dataclass
class CodeSystemFilter:
    """
    CodeSystemFilter nested class.
    """

    code: Optional[str] = None  # The code that identifies this filter when it is used as a filter in [ValueSet](valueset.html#).co...
    operator: List[str] = field(default_factory=list)  # A list of operators that can be used with the filter.
    value: Optional[str] = None  # A description of what the value for the filter should be.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    description: Optional[str] = None  # A description of how or why the filter is used.

@dataclass
class CodeSystemProperty:
    """
    CodeSystemProperty nested class.
    """

    code: Optional[str] = None  # A code that is used to identify the property. The code is used internally (in CodeSystem.concept....
    type: Optional[str] = None  # The type of the property value. Properties of type \"code\" contain a code defined by the code sy...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    uri: Optional[str] = None  # Reference to the formal meaning of the property. One possible source of meaning is the [Concept P...
    description: Optional[str] = None  # A description of the property- why it is defined, and how its value might be used.

@dataclass
class CodeSystemConcept:
    """
    CodeSystemConcept nested class.
    """

    code: Optional[str] = None  # A code - a text symbol - that uniquely identifies the concept within the code system.
    value: Optional[str] = None  # The text value for this designation.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    display: Optional[str] = None  # A human readable string that is the recommended default way to present this concept to a user.
    definition: Optional[str] = None  # The formal definition of the concept. The code system resource does not make formal definitions r...
    designation: Optional[List[BackboneElement]] = field(default_factory=list)  # Additional representations for the concept - other languages, aliases, specialized purposes, used...
    language: Optional[str] = None  # The language this designation is defined for.
    use: Optional[Coding] = None  # A code that details how this designation would be used.
    additionalUse: Optional[List[Coding]] = field(default_factory=list)  # Additional codes that detail how this designation would be used, if there is more than one use.
    property: Optional[List[BackboneElement]] = field(default_factory=list)  # A property value for this concept.
    concept: Optional[List[Any]] = field(default_factory=list)  # Defines children of a concept to produce a hierarchy of concepts. The nature of the relationships...

@dataclass
class CodeSystemConceptDesignation:
    """
    CodeSystemConceptDesignation nested class.
    """

    value: Optional[str] = None  # The text value for this designation.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    language: Optional[str] = None  # The language this designation is defined for.
    use: Optional[Coding] = None  # A code that details how this designation would be used.
    additionalUse: Optional[List[Coding]] = field(default_factory=list)  # Additional codes that detail how this designation would be used, if there is more than one use.

@dataclass
class CodeSystemConceptProperty:
    """
    CodeSystemConceptProperty nested class.
    """

    code: Optional[str] = None  # A code that is a reference to CodeSystem.property.code.
    value: Optional[Any] = None  # The value of this property.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...


@dataclass
class CodeSystem(FHIRResource):
    """
    Defines and enforces the minimum expectations for publication and distribution of a code system, typically as part of an artifact repository or implementation guide publication
    """

    url: Optional[str] = None  # An absolute URI that is used to identify this code system when it is referenced in a specificatio...
    version: Optional[str] = None  # The identifier that is used to identify this version of the code system when it is referenced in ...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the code system.
    status: Optional[str] = None  # The status of this code system. Enables tracking the life-cycle of the content.
    experimental: Optional[bool] = None  # A Boolean value to indicate that this code system is authored for testing purposes (or education/...
    date: Optional[str] = None  # The date  (and optionally time) when the code system was last significantly changed. The date mus...
    description: Optional[str] = None  # A free text natural language description of the code system from a consumer's perspective.
    caseSensitive: Optional[bool] = None  # If code comparison is case sensitive when codes within this system are compared to each other.
    content: Optional[str] = None  # The extent of the content of the code system (the concepts and codes it defines) are represented ...
    resourceType: str = "CodeSystem"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this code system when it is represented in other for...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which CodeSystem is more current.
    name: Optional[str] = None  # A natural language name identifying the code system. This name should be usable as an identifier ...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the code system is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this code system is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the code system and/or its contents. Copyright statements are g...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the resource content was approved by the publisher. Approval happens once when ...
    lastReviewDate: Optional[str] = None  # The date on which the resource content was last reviewed. Review happens periodically after appro...
    effectivePeriod: Optional[Period] = None  # The period during which the CodeSystem content was or is planned to be in active use.
    topic: Optional[List[CodeableConcept]] = field(default_factory=list)  # Descriptions related to the content of the CodeSystem. Topics provide a high-level categorization...
    author: Optional[List[ContactDetail]] = field(default_factory=list)  # An individiual or organization primarily involved in the creation and maintenance of the CodeSystem.
    editor: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization primarily responsible for internal coherence of the CodeSystem.
    reviewer: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be primarily responsible for review of...
    endorser: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be responsible for officially endorsin...
    relatedArtifact: Optional[List[RelatedArtifact]] = field(default_factory=list)  # Related artifacts such as additional documentation, justification, dependencies, bibliographic re...
    valueSet: Optional[str] = None  # Canonical reference to the value set that contains all codes in the code system independent of co...
    hierarchyMeaning: Optional[str] = None  # The meaning of the hierarchy of concepts as represented in this resource.
    compositional: Optional[bool] = None  # The code system defines a compositional (post-coordination) grammar.
    versionNeeded: Optional[bool] = None  # This flag is used to signify that the code system does not commit to concept permanence across ve...
    supplements: Optional[str] = None  # The canonical URL of the code system that this code system supplement is adding designations and ...
    count: Optional[int] = None  # The total number of concepts defined by the code system. Where the code system has a compositiona...
    filter: Optional[List[BackboneElement]] = field(default_factory=list)  # A filter that can be used in a value set compose statement when selecting concepts using a filter.
    property: Optional[List[BackboneElement]] = field(default_factory=list)  # A property defines an additional slot through which additional information can be provided about ...
    concept: Optional[List[BackboneElement]] = field(default_factory=list)  # Concepts that are in the code system. The concept definitions are inherently hierarchical, but th...