# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 ConceptMap resource.

Defines and enforces the minimum expectations for publication and distribution of a concept map, typically as part of an artifact repository or implementation guide publication
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Coding, ContactDetail, Extension, Identifier, Period, Quantity, RelatedArtifact, UsageContext
from typing import Any, List, Optional

@dataclass
class ConceptMapProperty:
    """
    ConceptMapProperty nested class.
    """

    code: Optional[str] = None  # A code that is used to identify the property. The code is used internally (in ConceptMap.group.el...
    type: Optional[str] = None  # The type of the property value.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    uri: Optional[str] = None  # Reference to the formal meaning of the property.
    description: Optional[str] = None  # A description of the property - why it is defined, and how its value might be used.
    system: Optional[str] = None  # The CodeSystem that defines the codes from which values of type ```code``` in property values.

@dataclass
class ConceptMapAdditionalAttribute:
    """
    ConceptMapAdditionalAttribute nested class.
    """

    code: Optional[str] = None  # A code that is used to identify this additional data attribute. The code is used internally in Co...
    type: Optional[str] = None  # The type of the source data contained in this concept map for this data element.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    uri: Optional[str] = None  # Reference to the formal definition of the source/target data element. For elements defined by the...
    description: Optional[str] = None  # A description of the additional attribute and/or the data element it refers to - why it is define...

@dataclass
class ConceptMapGroup:
    """
    ConceptMapGroup nested class.
    """

    element: List[BackboneElement] = field(default_factory=list)  # Mappings for an individual concept in the source to one or more concepts in the target.
    relationship: Optional[str] = None  # The relationship between the source and target concepts. The relationship is read from source to ...
    value: Optional[Any] = None  # The value of this property. If the type chosen for this element is 'code', then the property SHAL...
    attribute: Optional[str] = None  # A reference to the additional attribute that holds a value the map depends on.
    mode: Optional[str] = None  # Defines which action to take if there is no match for the source concept in the target system des...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    source: Optional[str] = None  # An absolute URI that identifies the source system where the concepts to be mapped are defined.
    target: Optional[str] = None  # An absolute URI that identifies the target system that the concepts will be mapped to.
    code: Optional[str] = None  # Identity (code or path) or the element/item being mapped.
    display: Optional[str] = None  # The display for the code. The display is only provided to help editors when editing the concept map.
    valueSet: Optional[str] = None  # The set of concepts from the ConceptMap.group.source code system which are all being mapped to th...
    noMap: Optional[bool] = None  # If noMap = true this indicates that no mapping to a target concept exists for this source concept.
    comment: Optional[str] = None  # A description of status/issues in mapping that conveys additional information not represented in ...
    property: Optional[List[BackboneElement]] = field(default_factory=list)  # A property value for this source -> target mapping.
    dependsOn: Optional[List[BackboneElement]] = field(default_factory=list)  # A set of additional dependencies for this mapping to hold. This mapping is only applicable if the...
    product: Optional[List[Any]] = field(default_factory=list)  # Product is the output of a ConceptMap that provides additional values that go in other attributes...
    unmapped: Optional[BackboneElement] = None  # What to do when there is no mapping to a target concept from the source concept and ConceptMap.gr...
    otherMap: Optional[str] = None  # The canonical reference to an additional ConceptMap resource instance to use for mapping if this ...

@dataclass
class ConceptMapGroupElement:
    """
    ConceptMapGroupElement nested class.
    """

    relationship: Optional[str] = None  # The relationship between the source and target concepts. The relationship is read from source to ...
    value: Optional[Any] = None  # The value of this property. If the type chosen for this element is 'code', then the property SHAL...
    attribute: Optional[str] = None  # A reference to the additional attribute that holds a value the map depends on.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    code: Optional[str] = None  # Identity (code or path) or the element/item being mapped.
    display: Optional[str] = None  # The display for the code. The display is only provided to help editors when editing the concept map.
    valueSet: Optional[str] = None  # The set of concepts from the ConceptMap.group.source code system which are all being mapped to th...
    noMap: Optional[bool] = None  # If noMap = true this indicates that no mapping to a target concept exists for this source concept.
    target: Optional[List[BackboneElement]] = field(default_factory=list)  # A concept from the target value set that this concept maps to.
    comment: Optional[str] = None  # A description of status/issues in mapping that conveys additional information not represented in ...
    property: Optional[List[BackboneElement]] = field(default_factory=list)  # A property value for this source -> target mapping.
    dependsOn: Optional[List[BackboneElement]] = field(default_factory=list)  # A set of additional dependencies for this mapping to hold. This mapping is only applicable if the...
    product: Optional[List[Any]] = field(default_factory=list)  # Product is the output of a ConceptMap that provides additional values that go in other attributes...

@dataclass
class ConceptMapGroupElementTarget:
    """
    ConceptMapGroupElementTarget nested class.
    """

    relationship: Optional[str] = None  # The relationship between the source and target concepts. The relationship is read from source to ...
    value: Optional[Any] = None  # The value of this property. If the type chosen for this element is 'code', then the property SHAL...
    attribute: Optional[str] = None  # A reference to the additional attribute that holds a value the map depends on.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    code: Optional[str] = None  # Identity (code or path) or the element/item that the map refers to.
    display: Optional[str] = None  # The display for the code. The display is only provided to help editors when editing the concept map.
    valueSet: Optional[str] = None  # The set of concepts from the ConceptMap.group.target code system which are all being mapped to as...
    comment: Optional[str] = None  # A description of status/issues in mapping that conveys additional information not represented in ...
    property: Optional[List[BackboneElement]] = field(default_factory=list)  # A property value for this source -> target mapping.
    dependsOn: Optional[List[BackboneElement]] = field(default_factory=list)  # A set of additional dependencies for this mapping to hold. This mapping is only applicable if the...
    product: Optional[List[Any]] = field(default_factory=list)  # Product is the output of a ConceptMap that provides additional values that go in other attributes...

@dataclass
class ConceptMapGroupElementTargetProperty:
    """
    ConceptMapGroupElementTargetProperty nested class.
    """

    code: Optional[str] = None  # A reference to a mapping property defined in ConceptMap.property.
    value: Optional[Any] = None  # The value of this property. If the type chosen for this element is 'code', then the property SHAL...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class ConceptMapGroupElementTargetDependsOn:
    """
    ConceptMapGroupElementTargetDependsOn nested class.
    """

    attribute: Optional[str] = None  # A reference to the additional attribute that holds a value the map depends on.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    value: Optional[Any] = None  # Data element value that the map depends on / produces.
    valueSet: Optional[str] = None  # This mapping applies if the data element value is a code from this value set.

@dataclass
class ConceptMapGroupUnmapped:
    """
    ConceptMapGroupUnmapped nested class.
    """

    mode: Optional[str] = None  # Defines which action to take if there is no match for the source concept in the target system des...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    code: Optional[str] = None  # The fixed code to use when the mode = 'fixed'  - all unmapped codes are mapped to a single fixed ...
    display: Optional[str] = None  # The display for the code. The display is only provided to help editors when editing the concept map.
    valueSet: Optional[str] = None  # The set of fixed codes to use when the mode = 'fixed'  - all unmapped codes are mapped to each of...
    relationship: Optional[str] = None  # The default relationship value to apply between the source and target concepts when the source co...
    otherMap: Optional[str] = None  # The canonical reference to an additional ConceptMap resource instance to use for mapping if this ...


@dataclass
class ConceptMap(FHIRResource):
    """
    Defines and enforces the minimum expectations for publication and distribution of a concept map, typically as part of an artifact repository or implementation guide publication
    """

    url: Optional[str] = None  # An absolute URI that is used to identify this concept map when it is referenced in a specificatio...
    version: Optional[str] = None  # The identifier that is used to identify this version of the concept map when it is referenced in ...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the concept map.
    status: Optional[str] = None  # The status of this concept map. Enables tracking the life-cycle of the content.
    experimental: Optional[bool] = None  # A Boolean value to indicate that this concept map is authored for testing purposes (or education/...
    date: Optional[str] = None  # The date  (and optionally time) when the concept map was last significantly changed. The date mus...
    description: Optional[str] = None  # A free text natural language description of the concept map from a consumer's perspective.
    resourceType: str = "ConceptMap"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this concept map when it is represented in other for...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which ConceptMap is more current.
    name: Optional[str] = None  # A natural language name identifying the concept map. This name should be usable as an identifier ...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the concept map is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this concept map is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the concept map and/or its contents. Copyright statements are g...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the resource content was approved by the publisher. Approval happens once when ...
    lastReviewDate: Optional[str] = None  # The date on which the resource content was last reviewed. Review happens periodically after appro...
    effectivePeriod: Optional[Period] = None  # The period during which the ConceptMap content was or is planned to be in active use.
    topic: Optional[List[CodeableConcept]] = field(default_factory=list)  # Descriptions related to the content of the ConceptMap. Topics provide a high-level categorization...
    author: Optional[List[ContactDetail]] = field(default_factory=list)  # An individiual or organization primarily involved in the creation and maintenance of the ConceptMap.
    editor: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization primarily responsible for internal coherence of the ConceptMap.
    reviewer: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be primarily responsible for review of...
    endorser: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be responsible for officially endorsin...
    relatedArtifact: Optional[List[RelatedArtifact]] = field(default_factory=list)  # Related artifacts such as additional documentation, justification, dependencies, bibliographic re...
    property: Optional[List[BackboneElement]] = field(default_factory=list)  # A property defines a slot through which additional information can be provided about a map from s...
    additionalAttribute: Optional[List[BackboneElement]] = field(default_factory=list)  # An additionalAttribute defines an additional data element found in the source or target data mode...
    sourceScope: Optional[Any] = None  # Identifier for the source value set that contains the concepts that are being mapped and provides...
    targetScope: Optional[Any] = None  # Identifier for the target value set that provides important context about how the mapping choices...
    group: Optional[List[BackboneElement]] = field(default_factory=list)  # A group of mappings that all have the same source and target system.