# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 Contract resource.

Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Annotation, Attachment, BackboneElement, CodeableConcept, Coding, Extension, Identifier, Money, Period, Quantity, Reference, Signature, Timing
from typing import Any, List, Optional

@dataclass
class ContractContentDefinition:
    """
    ContractContentDefinition nested class.
    """

    type: Optional[CodeableConcept] = None  # Precusory content structure and use, i.e., a boilerplate, template, application for a contract su...
    publicationStatus: Optional[str] = None  # amended | appended | cancelled | disputed | entered-in-error | executable +.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    subType: Optional[CodeableConcept] = None  # Detailed Precusory content type.
    publisher: Optional[Reference] = None  # The  individual or organization that published the Contract precursor content.
    publicationDate: Optional[str] = None  # The date (and optionally time) when the contract was last significantly changed. The date must ch...
    copyright: Optional[str] = None  # A copyright statement relating to Contract precursor content. Copyright statements are generally ...

@dataclass
class ContractTerm:
    """
    ContractTerm nested class.
    """

    classification: Optional[Coding] = None  # Security label privacy tag that specifies the level of confidentiality protection required for th...
    offer: Optional[BackboneElement] = None  # The matter of concern in the context of this provision of the agrement.
    reference: List[Reference] = field(default_factory=list)  # Participant in the offer.
    role: Optional[CodeableConcept] = None  # How the party participates in the offer.
    value: Optional[Any] = None  # Response to an offer clause or question text,  which enables selection of values to be agreed to,...
    intent: Optional[CodeableConcept] = None  # Reason or purpose for the action stipulated by this Contract Provision.
    status: Optional[CodeableConcept] = None  # Current state of the term action.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    identifier: Optional[Identifier] = None  # Unique identifier for this particular Contract Provision.
    issued: Optional[str] = None  # When this Contract Provision was issued.
    applies: Optional[Period] = None  # Relevant time or time-period when this Contract Provision is applicable.
    topic: Optional[Any] = None  # The entity that the term applies to.
    type: Optional[CodeableConcept] = None  # A legal clause or condition contained within a contract that requires one or both parties to perf...
    subType: Optional[CodeableConcept] = None  # A specialized legal clause or condition based on overarching contract type.
    text: Optional[str] = None  # Statement of a provision in a policy or a contract.
    securityLabel: Optional[List[BackboneElement]] = field(default_factory=list)  # Security labels that protect the handling of information about the term and its elements, which m...
    number: Optional[List[int]] = field(default_factory=list)  # Number used to link this term or term element to the applicable Security Label.
    category: Optional[List[Coding]] = field(default_factory=list)  # Security label privacy tag that specifies the applicable privacy and security policies governing ...
    control: Optional[List[Coding]] = field(default_factory=list)  # Security label privacy tag that specifies the manner in which term and/or term elements are to be...
    party: Optional[List[BackboneElement]] = field(default_factory=list)  # Offer Recipient.
    decision: Optional[CodeableConcept] = None  # Type of choice made by accepting party with respect to an offer made by an offeror/ grantee.
    decisionMode: Optional[List[CodeableConcept]] = field(default_factory=list)  # How the decision about a Contract was conveyed.
    answer: Optional[List[BackboneElement]] = field(default_factory=list)  # Response to offer text.
    linkId: Optional[List[str]] = field(default_factory=list)  # The id of the clause or question text of the offer in the referenced questionnaire/response.
    securityLabelNumber: Optional[List[int]] = field(default_factory=list)  # Security labels that protects the offer.
    asset: Optional[List[BackboneElement]] = field(default_factory=list)  # Contract Term Asset List.
    scope: Optional[CodeableConcept] = None  # Differentiates the kind of the asset .
    typeReference: Optional[List[Reference]] = field(default_factory=list)  # Associated entities.
    subtype: Optional[List[CodeableConcept]] = field(default_factory=list)  # May be a subtype or part of an offered asset.
    relationship: Optional[Coding] = None  # Specifies the applicability of the term to an asset resource instance, and instances it refers to...
    context: Optional[List[BackboneElement]] = field(default_factory=list)  # Circumstance of the asset.
    code: Optional[List[CodeableConcept]] = field(default_factory=list)  # Coded representation of the context generally or of the Referenced entity, such as the asset hold...
    condition: Optional[str] = None  # Description of the quality and completeness of the asset that may be a factor in its valuation.
    periodType: Optional[List[CodeableConcept]] = field(default_factory=list)  # Type of Asset availability for use or ownership.
    period: Optional[List[Period]] = field(default_factory=list)  # Asset relevant contractual time period.
    usePeriod: Optional[List[Period]] = field(default_factory=list)  # Time period of asset use.
    valuedItem: Optional[List[BackboneElement]] = field(default_factory=list)  # Contract Valued Item List.
    entity: Optional[Any] = None  # Specific type of Contract Valued Item that may be priced.
    effectiveTime: Optional[str] = None  # Indicates the time during which this Contract ValuedItem information is effective.
    quantity: Optional[Quantity] = None  # Specifies the units by which the Contract Valued Item is measured or counted, and quantifies the ...
    unitPrice: Optional[Money] = None  # A Contract Valued Item unit valuation measure.
    factor: Optional[float] = None  # A real number that represents a multiplier used in determining the overall value of the Contract ...
    points: Optional[float] = None  # An amount that expresses the weighting (based on difficulty, cost and/or resource intensiveness) ...
    net: Optional[Money] = None  # Expresses the product of the Contract Valued Item unitQuantity and the unitPriceAmt. For example,...
    payment: Optional[str] = None  # Terms of valuation.
    paymentDate: Optional[str] = None  # When payment is due.
    responsible: Optional[Reference] = None  # Who will make payment.
    recipient: Optional[Reference] = None  # Who will receive payment.
    action: Optional[List[BackboneElement]] = field(default_factory=list)  # An actor taking a role in an activity for which it can be assigned some degree of responsibility ...
    doNotPerform: Optional[bool] = None  # True if the term prohibits the  action.
    subject: Optional[List[BackboneElement]] = field(default_factory=list)  # Entity of the action.
    contextLinkId: Optional[List[str]] = field(default_factory=list)  # Id [identifier??] of the clause or question text related to the requester of this action in the r...
    occurrence: Optional[Any] = None  # When action happens.
    requester: Optional[List[Reference]] = field(default_factory=list)  # Who or what initiated the action and has responsibility for its activation.
    requesterLinkId: Optional[List[str]] = field(default_factory=list)  # Id [identifier??] of the clause or question text related to the requester of this action in the r...
    performerType: Optional[List[CodeableConcept]] = field(default_factory=list)  # The type of individual that is desired or required to perform or not perform the action.
    performerRole: Optional[CodeableConcept] = None  # The type of role or competency of an individual desired or required to perform or not perform the...
    performer: Optional[Reference] = None  # Indicates who or what is being asked to perform (or not perform) the ction.
    performerLinkId: Optional[List[str]] = field(default_factory=list)  # Id [identifier??] of the clause or question text related to the reason type or reference of this ...
    reason: Optional[List[Any]] = field(default_factory=list)  # Rationale for the action to be performed or not performed. Describes why the action is permitted ...
    reasonLinkId: Optional[List[str]] = field(default_factory=list)  # Id [identifier??] of the clause or question text related to the reason type or reference of this ...
    note: Optional[List[Annotation]] = field(default_factory=list)  # Comments made about the term action made by the requester, performer, subject or other participants.
    group: Optional[List[Any]] = field(default_factory=list)  # Nested group of Contract Provisions.

@dataclass
class ContractTermSecurityLabel:
    """
    ContractTermSecurityLabel nested class.
    """

    classification: Optional[Coding] = None  # Security label privacy tag that specifies the level of confidentiality protection required for th...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    number: Optional[List[int]] = field(default_factory=list)  # Number used to link this term or term element to the applicable Security Label.
    category: Optional[List[Coding]] = field(default_factory=list)  # Security label privacy tag that specifies the applicable privacy and security policies governing ...
    control: Optional[List[Coding]] = field(default_factory=list)  # Security label privacy tag that specifies the manner in which term and/or term elements are to be...

@dataclass
class ContractTermOffer:
    """
    ContractTermOffer nested class.
    """

    reference: List[Reference] = field(default_factory=list)  # Participant in the offer.
    role: Optional[CodeableConcept] = None  # How the party participates in the offer.
    value: Optional[Any] = None  # Response to an offer clause or question text,  which enables selection of values to be agreed to,...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # Unique identifier for this particular Contract Provision.
    party: Optional[List[BackboneElement]] = field(default_factory=list)  # Offer Recipient.
    topic: Optional[Reference] = None  # The owner of an asset has the residual control rights over the asset: the right to decide all usa...
    type: Optional[CodeableConcept] = None  # Type of Contract Provision such as specific requirements, purposes for actions, obligations, proh...
    decision: Optional[CodeableConcept] = None  # Type of choice made by accepting party with respect to an offer made by an offeror/ grantee.
    decisionMode: Optional[List[CodeableConcept]] = field(default_factory=list)  # How the decision about a Contract was conveyed.
    answer: Optional[List[BackboneElement]] = field(default_factory=list)  # Response to offer text.
    text: Optional[str] = None  # Human readable form of this Contract Offer.
    linkId: Optional[List[str]] = field(default_factory=list)  # The id of the clause or question text of the offer in the referenced questionnaire/response.
    securityLabelNumber: Optional[List[int]] = field(default_factory=list)  # Security labels that protects the offer.

@dataclass
class ContractTermOfferParty:
    """
    ContractTermOfferParty nested class.
    """

    reference: List[Reference] = field(default_factory=list)  # Participant in the offer.
    role: Optional[CodeableConcept] = None  # How the party participates in the offer.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class ContractTermOfferAnswer:
    """
    ContractTermOfferAnswer nested class.
    """

    value: Optional[Any] = None  # Response to an offer clause or question text,  which enables selection of values to be agreed to,...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class ContractTermAsset:
    """
    ContractTermAsset nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    scope: Optional[CodeableConcept] = None  # Differentiates the kind of the asset .
    type: Optional[List[CodeableConcept]] = field(default_factory=list)  # Target entity type about which the term may be concerned.
    typeReference: Optional[List[Reference]] = field(default_factory=list)  # Associated entities.
    subtype: Optional[List[CodeableConcept]] = field(default_factory=list)  # May be a subtype or part of an offered asset.
    relationship: Optional[Coding] = None  # Specifies the applicability of the term to an asset resource instance, and instances it refers to...
    context: Optional[List[BackboneElement]] = field(default_factory=list)  # Circumstance of the asset.
    reference: Optional[Reference] = None  # Asset context reference may include the creator, custodian, or owning Person or Organization (e.g...
    code: Optional[List[CodeableConcept]] = field(default_factory=list)  # Coded representation of the context generally or of the Referenced entity, such as the asset hold...
    text: Optional[str] = None  # Context description.
    condition: Optional[str] = None  # Description of the quality and completeness of the asset that may be a factor in its valuation.
    periodType: Optional[List[CodeableConcept]] = field(default_factory=list)  # Type of Asset availability for use or ownership.
    period: Optional[List[Period]] = field(default_factory=list)  # Asset relevant contractual time period.
    usePeriod: Optional[List[Period]] = field(default_factory=list)  # Time period of asset use.
    linkId: Optional[List[str]] = field(default_factory=list)  # Id [identifier??] of the clause or question text about the asset in the referenced form or Questi...
    answer: Optional[List[Any]] = field(default_factory=list)  # Response to assets.
    securityLabelNumber: Optional[List[int]] = field(default_factory=list)  # Security labels that protects the asset.
    valuedItem: Optional[List[BackboneElement]] = field(default_factory=list)  # Contract Valued Item List.
    entity: Optional[Any] = None  # Specific type of Contract Valued Item that may be priced.
    identifier: Optional[Identifier] = None  # Identifies a Contract Valued Item instance.
    effectiveTime: Optional[str] = None  # Indicates the time during which this Contract ValuedItem information is effective.
    quantity: Optional[Quantity] = None  # Specifies the units by which the Contract Valued Item is measured or counted, and quantifies the ...
    unitPrice: Optional[Money] = None  # A Contract Valued Item unit valuation measure.
    factor: Optional[float] = None  # A real number that represents a multiplier used in determining the overall value of the Contract ...
    points: Optional[float] = None  # An amount that expresses the weighting (based on difficulty, cost and/or resource intensiveness) ...
    net: Optional[Money] = None  # Expresses the product of the Contract Valued Item unitQuantity and the unitPriceAmt. For example,...
    payment: Optional[str] = None  # Terms of valuation.
    paymentDate: Optional[str] = None  # When payment is due.
    responsible: Optional[Reference] = None  # Who will make payment.
    recipient: Optional[Reference] = None  # Who will receive payment.

@dataclass
class ContractTermAssetContext:
    """
    ContractTermAssetContext nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    reference: Optional[Reference] = None  # Asset context reference may include the creator, custodian, or owning Person or Organization (e.g...
    code: Optional[List[CodeableConcept]] = field(default_factory=list)  # Coded representation of the context generally or of the Referenced entity, such as the asset hold...
    text: Optional[str] = None  # Context description.

@dataclass
class ContractTermAssetValuedItem:
    """
    ContractTermAssetValuedItem nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    entity: Optional[Any] = None  # Specific type of Contract Valued Item that may be priced.
    identifier: Optional[Identifier] = None  # Identifies a Contract Valued Item instance.
    effectiveTime: Optional[str] = None  # Indicates the time during which this Contract ValuedItem information is effective.
    quantity: Optional[Quantity] = None  # Specifies the units by which the Contract Valued Item is measured or counted, and quantifies the ...
    unitPrice: Optional[Money] = None  # A Contract Valued Item unit valuation measure.
    factor: Optional[float] = None  # A real number that represents a multiplier used in determining the overall value of the Contract ...
    points: Optional[float] = None  # An amount that expresses the weighting (based on difficulty, cost and/or resource intensiveness) ...
    net: Optional[Money] = None  # Expresses the product of the Contract Valued Item unitQuantity and the unitPriceAmt. For example,...
    payment: Optional[str] = None  # Terms of valuation.
    paymentDate: Optional[str] = None  # When payment is due.
    responsible: Optional[Reference] = None  # Who will make payment.
    recipient: Optional[Reference] = None  # Who will receive payment.
    linkId: Optional[List[str]] = field(default_factory=list)  # Id  of the clause or question text related to the context of this valuedItem in the referenced fo...
    securityLabelNumber: Optional[List[int]] = field(default_factory=list)  # A set of security labels that define which terms are controlled by this condition.

@dataclass
class ContractTermAction:
    """
    ContractTermAction nested class.
    """

    type: Optional[CodeableConcept] = None  # Activity or service obligation to be done or not done, performed or not performed, effectuated or...
    reference: List[Reference] = field(default_factory=list)  # The entity the action is performed or not performed on or for.
    intent: Optional[CodeableConcept] = None  # Reason or purpose for the action stipulated by this Contract Provision.
    status: Optional[CodeableConcept] = None  # Current state of the term action.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    doNotPerform: Optional[bool] = None  # True if the term prohibits the  action.
    subject: Optional[List[BackboneElement]] = field(default_factory=list)  # Entity of the action.
    role: Optional[CodeableConcept] = None  # Role type of agent assigned roles in this Contract.
    linkId: Optional[List[str]] = field(default_factory=list)  # Id [identifier??] of the clause or question text related to this action in the referenced form or...
    context: Optional[Reference] = None  # Encounter or Episode with primary association to the specified term activity.
    contextLinkId: Optional[List[str]] = field(default_factory=list)  # Id [identifier??] of the clause or question text related to the requester of this action in the r...
    occurrence: Optional[Any] = None  # When action happens.
    requester: Optional[List[Reference]] = field(default_factory=list)  # Who or what initiated the action and has responsibility for its activation.
    requesterLinkId: Optional[List[str]] = field(default_factory=list)  # Id [identifier??] of the clause or question text related to the requester of this action in the r...
    performerType: Optional[List[CodeableConcept]] = field(default_factory=list)  # The type of individual that is desired or required to perform or not perform the action.
    performerRole: Optional[CodeableConcept] = None  # The type of role or competency of an individual desired or required to perform or not perform the...
    performer: Optional[Reference] = None  # Indicates who or what is being asked to perform (or not perform) the ction.
    performerLinkId: Optional[List[str]] = field(default_factory=list)  # Id [identifier??] of the clause or question text related to the reason type or reference of this ...
    reason: Optional[List[Any]] = field(default_factory=list)  # Rationale for the action to be performed or not performed. Describes why the action is permitted ...
    reasonLinkId: Optional[List[str]] = field(default_factory=list)  # Id [identifier??] of the clause or question text related to the reason type or reference of this ...
    note: Optional[List[Annotation]] = field(default_factory=list)  # Comments made about the term action made by the requester, performer, subject or other participants.
    securityLabelNumber: Optional[List[int]] = field(default_factory=list)  # Security labels that protects the action.

@dataclass
class ContractTermActionSubject:
    """
    ContractTermActionSubject nested class.
    """

    reference: List[Reference] = field(default_factory=list)  # The entity the action is performed or not performed on or for.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    role: Optional[CodeableConcept] = None  # Role type of agent assigned roles in this Contract.

@dataclass
class ContractSigner:
    """
    ContractSigner nested class.
    """

    type: Optional[Coding] = None  # Role of this Contract signer, e.g. notary, grantee.
    party: Optional[Reference] = None  # Party which is a signator to this Contract.
    signature: List[Signature] = field(default_factory=list)  # Legally binding Contract DSIG signature contents in Base64.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class ContractFriendly:
    """
    ContractFriendly nested class.
    """

    content: Optional[Any] = None  # Human readable rendering of this Contract in a format and representation intended to enhance comp...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class ContractLegal:
    """
    ContractLegal nested class.
    """

    content: Optional[Any] = None  # Contract legal text in human renderable form.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class ContractRule:
    """
    ContractRule nested class.
    """

    content: Optional[Any] = None  # Computable Contract conveyed using a policy rule language (e.g. XACML, DKAL, SecPal).
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...


@dataclass
class Contract(FHIRResource):
    """
    Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
    """

    resourceType: str = "Contract"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # Unique identifier for this Contract or a derivative that references a Source Contract.
    url: Optional[str] = None  # Canonical identifier for this contract, represented as a URI (globally unique).
    version: Optional[str] = None  # An edition identifier used for business purposes to label business significant variants.
    status: Optional[str] = None  # The status of the resource instance.
    legalState: Optional[CodeableConcept] = None  # Legal states of the formation of a legal instrument, which is a formally executed written documen...
    instantiatesCanonical: Optional[Reference] = None  # The URL pointing to a FHIR-defined Contract Definition that is adhered to in whole or part by thi...
    instantiatesUri: Optional[str] = None  # The URL pointing to an externally maintained definition that is adhered to in whole or in part by...
    contentDerivative: Optional[CodeableConcept] = None  # The minimal content derived from the basal information source at a specific stage in its lifecycle.
    issued: Optional[str] = None  # When this  Contract was issued.
    applies: Optional[Period] = None  # Relevant time or time-period when this Contract is applicable.
    expirationType: Optional[CodeableConcept] = None  # Event resulting in discontinuation or termination of this Contract instance by one or more partie...
    subject: Optional[List[Reference]] = field(default_factory=list)  # The target entity impacted by or of interest to parties to the agreement.
    authority: Optional[List[Reference]] = field(default_factory=list)  # A formally or informally recognized grouping of people, principals, organizations, or jurisdictio...
    domain: Optional[List[Reference]] = field(default_factory=list)  # Recognized governance framework or system operating with a circumscribed scope in accordance with...
    site: Optional[List[Reference]] = field(default_factory=list)  # Sites in which the contract is complied with,  exercised, or in force.
    name: Optional[str] = None  # A natural language name identifying this Contract definition, derivative, or instance in any lega...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for this Contract definition, derivative, or instance i...
    subtitle: Optional[str] = None  # A more detailed or qualifying explanatory or alternate user-friendly title for this Contract defi...
    alias: Optional[List[str]] = field(default_factory=list)  # Alternative representation of the title for this Contract definition, derivative, or instance in ...
    author: Optional[Reference] = None  # The individual or organization that authored the Contract definition, derivative, or instance in ...
    scope: Optional[CodeableConcept] = None  # A selector of legal concerns for this Contract definition, derivative, or instance in any legal s...
    topic: Optional[Any] = None  # Narrows the range of legal concerns to focus on the achievement of specific contractual objectives.
    type: Optional[CodeableConcept] = None  # A high-level category for the legal instrument, whether constructed as a Contract definition, der...
    subType: Optional[List[CodeableConcept]] = field(default_factory=list)  # Sub-category for the Contract that distinguishes the kinds of systems that would be interested in...
    contentDefinition: Optional[BackboneElement] = None  # Precusory content developed with a focus and intent of supporting the formation a Contract instan...
    term: Optional[List[BackboneElement]] = field(default_factory=list)  # One or more Contract Provisions, which may be related and conveyed as a group, and may contain ne...
    supportingInfo: Optional[List[Reference]] = field(default_factory=list)  # Information that may be needed by/relevant to the performer in their execution of this term action.
    relevantHistory: Optional[List[Reference]] = field(default_factory=list)  # Links to Provenance records for past versions of this Contract definition, derivative, or instanc...
    signer: Optional[List[BackboneElement]] = field(default_factory=list)  # Parties with legal standing in the Contract, including the principal parties, the grantor(s) and ...
    friendly: Optional[List[BackboneElement]] = field(default_factory=list)  # The \"patient friendly language\" versionof the Contract in whole or in parts. \"Patient friendly...
    legal: Optional[List[BackboneElement]] = field(default_factory=list)  # List of Legal expressions or representations of this Contract.
    rule: Optional[List[BackboneElement]] = field(default_factory=list)  # List of Computable Policy Rule Language Representations of this Contract.
    legallyBinding: Optional[Any] = None  # Legally binding Contract: This is the signed and legally recognized representation of the Contrac...