# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 EventDefinition resource.

The EventDefinition resource provides a reusable description of when a particular event can occur.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import CodeableConcept, Coding, ContactDetail, Identifier, Period, Reference, RelatedArtifact, TriggerDefinition, UsageContext
from typing import Any, List, Optional

@dataclass
class EventDefinition(FHIRResource):
    """
    The EventDefinition resource provides a reusable description of when a particular event can occur.
    """

    status: Optional[str] = None  # The status of this event definition. Enables tracking the life-cycle of the content.
    trigger: List[TriggerDefinition] = field(default_factory=list)  # The trigger element defines when the event occurs. If more than one trigger condition is specifie...
    resourceType: str = "EventDefinition"
    url: Optional[str] = None  # An absolute URI that is used to identify this event definition when it is referenced in a specifi...
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this event definition when it is represented in othe...
    version: Optional[str] = None  # The identifier that is used to identify this version of the event definition when it is reference...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    name: Optional[str] = None  # A natural language name identifying the event definition. This name should be usable as an identi...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the event definition.
    subtitle: Optional[str] = None  # An explanatory or alternate title for the event definition giving additional information about it...
    experimental: Optional[bool] = None  # A Boolean value to indicate that this event definition is authored for testing purposes (or educa...
    subject: Optional[Any] = None  # A code or group definition that describes the intended subject of the event definition.
    date: Optional[str] = None  # The date  (and optionally time) when the event definition was last significantly changed. The dat...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    description: Optional[str] = None  # A free text natural language description of the event definition from a consumer's perspective.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the event definition is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this event definition is needed and why it has been designed as it has.
    usage: Optional[str] = None  # A detailed description of how the event definition is used from a clinical perspective.
    copyright: Optional[str] = None  # A copyright statement relating to the event definition and/or its contents. Copyright statements ...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the resource content was approved by the publisher. Approval happens once when ...
    lastReviewDate: Optional[str] = None  # The date on which the resource content was last reviewed. Review happens periodically after appro...
    effectivePeriod: Optional[Period] = None  # The period during which the event definition content was or is planned to be in active use.
    topic: Optional[List[CodeableConcept]] = field(default_factory=list)  # Descriptive topics related to the module. Topics provide a high-level categorization of the modul...
    author: Optional[List[ContactDetail]] = field(default_factory=list)  # An individiual or organization primarily involved in the creation and maintenance of the content.
    editor: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization primarily responsible for internal coherence of the content.
    reviewer: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be primarily responsible for review of...
    endorser: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be responsible for officially endorsin...
    relatedArtifact: Optional[List[RelatedArtifact]] = field(default_factory=list)  # Related resources such as additional documentation, justification, or bibliographic references.