# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 FamilyMemberHistory resource.

Significant health conditions for a person related to the patient relevant in the context of care for the patient.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Age, Annotation, BackboneElement, CodeableConcept, Extension, Identifier, Period, Range, Reference
from typing import Any, List, Optional

@dataclass
class FamilyMemberHistoryParticipant:
    """
    FamilyMemberHistoryParticipant nested class.
    """

    actor: Optional[Reference] = None  # Indicates who or what participated in the activities related to the family member history.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    function: Optional[CodeableConcept] = None  # Distinguishes the type of involvement of the actor in the activities related to the family member...

@dataclass
class FamilyMemberHistoryCondition:
    """
    FamilyMemberHistoryCondition nested class.
    """

    code: Optional[CodeableConcept] = None  # The actual condition specified. Could be a coded condition (like MI or Diabetes) or a less specif...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    outcome: Optional[CodeableConcept] = None  # Indicates what happened following the condition.  If the condition resulted in death, deceased da...
    contributedToDeath: Optional[bool] = None  # This condition contributed to the cause of death of the related person. If contributedToDeath is ...
    onset: Optional[Any] = None  # Either the age of onset, range of approximate age or descriptive string can be recorded.  For con...
    note: Optional[List[Annotation]] = field(default_factory=list)  # An area where general notes can be placed about this specific condition.

@dataclass
class FamilyMemberHistoryProcedure:
    """
    FamilyMemberHistoryProcedure nested class.
    """

    code: Optional[CodeableConcept] = None  # The actual procedure specified. Could be a coded procedure or a less specific string depending on...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    outcome: Optional[CodeableConcept] = None  # Indicates what happened following the procedure. If the procedure resulted in death, deceased dat...
    contributedToDeath: Optional[bool] = None  # This procedure contributed to the cause of death of the related person. If contributedToDeath is ...
    performed: Optional[Any] = None  # Estimated or actual date, date-time, period, or age when the procedure was performed. Allows a pe...
    note: Optional[List[Annotation]] = field(default_factory=list)  # An area where general notes can be placed about this specific procedure.


@dataclass
class FamilyMemberHistory(FHIRResource):
    """
    Significant health conditions for a person related to the patient relevant in the context of care for the patient.
    """

    status: Optional[str] = None  # A code specifying the status of the record of the family history of a specific family member.
    patient: Optional[Reference] = None  # The person who this history concerns.
    relationship: Optional[CodeableConcept] = None  # The type of relationship this person has to the patient (father, mother, brother etc.).
    resourceType: str = "FamilyMemberHistory"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # Business identifiers assigned to this family member history by the performer or other systems whi...
    instantiatesCanonical: Optional[List[str]] = field(default_factory=list)  # The URL pointing to a FHIR-defined protocol, guideline, orderset or other definition that is adhe...
    instantiatesUri: Optional[List[str]] = field(default_factory=list)  # The URL pointing to an externally maintained protocol, guideline, orderset or other definition th...
    dataAbsentReason: Optional[CodeableConcept] = None  # Describes why the family member's history is not available.
    date: Optional[str] = None  # The date (and possibly time) when the family member history was recorded or last updated.
    participant: Optional[List[BackboneElement]] = field(default_factory=list)  # Indicates who or what participated in the activities related to the family member history and how...
    name: Optional[str] = None  # This will either be a name or a description; e.g. \"Aunt Susan\", \"my cousin with the red hair\".
    sex: Optional[CodeableConcept] = None  # The birth sex of the family member.
    born: Optional[Any] = None  # The actual or approximate date of birth of the relative.
    age: Optional[Any] = None  # The age of the relative at the time the family member history is recorded.
    estimatedAge: Optional[bool] = None  # If true, indicates that the age value specified is an estimated value.
    deceased: Optional[Any] = None  # Deceased flag or the actual or approximate age of the relative at the time of death for the famil...
    reason: Optional[List[Any]] = field(default_factory=list)  # Describes why the family member history occurred in coded or textual form, or Indicates a Conditi...
    note: Optional[List[Annotation]] = field(default_factory=list)  # This property allows a non condition-specific note to the made about the related person. Ideally,...
    condition: Optional[List[BackboneElement]] = field(default_factory=list)  # The significant Conditions (or condition) that the family member had. This is a repeating section...
    procedure: Optional[List[BackboneElement]] = field(default_factory=list)  # The significant Procedures (or procedure) that the family member had. This is a repeating section...