# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 Ingredient resource.

An ingredient of a manufactured item or pharmaceutical product.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Extension, Identifier, Quantity, Ratio, Reference
from typing import Any, List, Optional

@dataclass
class IngredientManufacturer:
    """
    IngredientManufacturer nested class.
    """

    manufacturer: Optional[Reference] = None  # An organization that manufactures this ingredient.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    role: Optional[str] = None  # The way in which this manufacturer is associated with the ingredient. For example whether it is a...

@dataclass
class IngredientSubstance:
    """
    IngredientSubstance nested class.
    """

    code: Optional[Any] = None  # A code or full resource that represents the ingredient's substance.
    substance: Optional[Any] = None  # Relevant reference substance.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    strength: Optional[List[BackboneElement]] = field(default_factory=list)  # The quantity of substance in the unit of presentation, or in the volume (or mass) of the single p...
    presentation: Optional[Any] = None  # The quantity of substance in the unit of presentation, or in the volume (or mass) of the single p...
    textPresentation: Optional[str] = None  # A textual represention of either the whole of the presentation strength or a part of it - with th...
    concentration: Optional[Any] = None  # The strength per unitary volume (or mass).
    textConcentration: Optional[str] = None  # A textual represention of either the whole of the concentration strength or a part of it - with t...
    basis: Optional[CodeableConcept] = None  # A code that indicates if the strength is, for example, based on the ingredient substance as state...
    measurementPoint: Optional[str] = None  # For when strength is measured at a particular point or distance. There are products where strengt...
    country: Optional[List[CodeableConcept]] = field(default_factory=list)  # The country or countries for which the strength range applies.
    referenceStrength: Optional[List[BackboneElement]] = field(default_factory=list)  # Strength expressed in terms of a reference substance. For when the ingredient strength is additio...

@dataclass
class IngredientSubstanceStrength:
    """
    IngredientSubstanceStrength nested class.
    """

    substance: Optional[Any] = None  # Relevant reference substance.
    strength: Optional[Any] = None  # Strength expressed in terms of a reference substance.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    presentation: Optional[Any] = None  # The quantity of substance in the unit of presentation, or in the volume (or mass) of the single p...
    textPresentation: Optional[str] = None  # A textual represention of either the whole of the presentation strength or a part of it - with th...
    concentration: Optional[Any] = None  # The strength per unitary volume (or mass).
    textConcentration: Optional[str] = None  # A textual represention of either the whole of the concentration strength or a part of it - with t...
    basis: Optional[CodeableConcept] = None  # A code that indicates if the strength is, for example, based on the ingredient substance as state...
    measurementPoint: Optional[str] = None  # For when strength is measured at a particular point or distance. There are products where strengt...
    country: Optional[List[CodeableConcept]] = field(default_factory=list)  # The country or countries for which the strength range applies.
    referenceStrength: Optional[List[BackboneElement]] = field(default_factory=list)  # Strength expressed in terms of a reference substance. For when the ingredient strength is additio...

@dataclass
class IngredientSubstanceStrengthReferenceStrength:
    """
    IngredientSubstanceStrengthReferenceStrength nested class.
    """

    substance: Optional[Any] = None  # Relevant reference substance.
    strength: Optional[Any] = None  # Strength expressed in terms of a reference substance.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    measurementPoint: Optional[str] = None  # For when strength is measured at a particular point or distance.
    country: Optional[List[CodeableConcept]] = field(default_factory=list)  # The country or countries for which the strength range applies.


@dataclass
class Ingredient(FHIRResource):
    """
    An ingredient of a manufactured item or pharmaceutical product.
    """

    status: Optional[str] = None  # The status of this ingredient. Enables tracking the life-cycle of the content.
    role: Optional[CodeableConcept] = None  # A classification of the ingredient identifying its purpose within the product, e.g. active, inact...
    substance: Optional[BackboneElement] = None  # The substance that comprises this ingredient.
    resourceType: str = "Ingredient"
    identifier: Optional[Identifier] = None  # The identifier(s) of this Ingredient that are assigned by business processes and/or used to refer...
    for_: Optional[List[Reference]] = field(default_factory=list)  # The product which this ingredient is a constituent part of.
    function: Optional[List[CodeableConcept]] = field(default_factory=list)  # A classification of the ingredient identifying its precise purpose(s) in the drug product. This e...
    group: Optional[CodeableConcept] = None  # A classification of the ingredient according to where in the physical item it tends to be used, s...
    allergenicIndicator: Optional[bool] = None  # If the ingredient is a known or suspected allergen. Note that this is a property of the substance...
    comment: Optional[str] = None  # A place for providing any notes that are relevant to the component, e.g. removed during process, ...
    manufacturer: Optional[List[BackboneElement]] = field(default_factory=list)  # The organization(s) that manufacture this ingredient. Can be used to indicate:         1) Organiz...