# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 Measure resource.

Supports declaration of the Measure metadata required by HL7 and other organizations that share and publish measures with a focus on the aspects of that metadata that are important for post-publication activities including distribution, inclusion in repositories, consumption, and implementation.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Attachment, BackboneElement, CodeableConcept, Coding, ContactDetail, Expression, Extension, Identifier, Period, Reference, RelatedArtifact, UsageContext
from typing import Any, List, Optional

@dataclass
class MeasureRelatedArtifact:
    """
    MeasureRelatedArtifact nested class.
    """

    type: Optional[str] = None  # The type of relationship to the related artifact.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    classifier: Optional[List[CodeableConcept]] = field(default_factory=list)  # Provides additional classifiers of the related artifact.
    label: Optional[str] = None  # A short label that can be used to reference the citation from elsewhere in the containing artifac...
    display: Optional[str] = None  # A brief description of the document or knowledge resource being referenced, suitable for display ...
    citation: Optional[str] = None  # A bibliographic citation for the related artifact. This text SHOULD be formatted according to an ...
    document: Optional[Attachment] = None  # The document being referenced, represented as an attachment. This is exclusive with the resource ...
    resource: Optional[str] = None  # The related artifact, such as a library, value set, profile, or other knowledge resource.
    resourceReference: Optional[Reference] = None  # The related artifact, if the artifact is not a canonical resource, or a resource reference to a c...
    publicationStatus: Optional[str] = None  # The publication status of the artifact being referred to.
    publicationDate: Optional[str] = None  # The date of publication of the artifact being referred to.

@dataclass
class MeasureTerm:
    """
    MeasureTerm nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    code: Optional[CodeableConcept] = None  # A codeable representation of the defined term.
    definition: Optional[str] = None  # Provides a definition for the term as used within the measure.

@dataclass
class MeasureGroup:
    """
    MeasureGroup nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    linkId: Optional[str] = None  # An identifier that is unique within the Measure allowing linkage to the equivalent item in a Meas...
    code: Optional[CodeableConcept] = None  # Indicates a meaning for the group. This can be as simple as a unique identifier, or it can establ...
    description: Optional[str] = None  # The human readable description of this population group.
    type: Optional[List[CodeableConcept]] = field(default_factory=list)  # Indicates whether the measure is used to examine a process, an outcome over time, a patient-repor...
    subject: Optional[Any] = None  # The intended subjects for the measure. If this element is not provided, a Patient subject is assu...
    basis: Optional[str] = None  # The population basis specifies the type of elements in the population. For a subject-based measur...
    scoring: Optional[CodeableConcept] = None  # Indicates how the calculation is performed for the measure, including proportion, ratio, continuo...
    scoringUnit: Optional[CodeableConcept] = None  # Defines the expected units of measure for the measure score. This element SHOULD be specified as ...
    rateAggregation: Optional[str] = None  # Describes how to combine the information calculated, based on logic in each of several population...
    improvementNotation: Optional[CodeableConcept] = None  # Information on whether an increase or decrease in score is the preferred result (e.g., a higher s...
    library: Optional[List[str]] = field(default_factory=list)  # A reference to a Library resource containing the formal logic used by the measure group.
    population: Optional[List[BackboneElement]] = field(default_factory=list)  # A population criteria for the measure.
    criteria: Optional[Expression] = None  # An expression that specifies the criteria for the population, typically the name of an expression...
    groupDefinition: Optional[Reference] = None  # A Group resource that defines this population as a set of characteristics.
    inputPopulationId: Optional[str] = None  # The id of a population element in this measure that provides the input for this population criter...
    aggregateMethod: Optional[CodeableConcept] = None  # Specifies which method should be used to aggregate measure observation values. For most scoring t...
    stratifier: Optional[List[BackboneElement]] = field(default_factory=list)  # The stratifier criteria for the measure report, specified as either the name of a valid CQL expre...
    component: Optional[List[BackboneElement]] = field(default_factory=list)  # A component of the stratifier criteria for the measure report, specified as either the name of a ...

@dataclass
class MeasureGroupPopulation:
    """
    MeasureGroupPopulation nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    linkId: Optional[str] = None  # An identifier that is unique within the Measure allowing linkage to the equivalent population in ...
    code: Optional[CodeableConcept] = None  # The type of population criteria.
    description: Optional[str] = None  # The human readable description of this population criteria.
    criteria: Optional[Expression] = None  # An expression that specifies the criteria for the population, typically the name of an expression...
    groupDefinition: Optional[Reference] = None  # A Group resource that defines this population as a set of characteristics.
    inputPopulationId: Optional[str] = None  # The id of a population element in this measure that provides the input for this population criter...
    aggregateMethod: Optional[CodeableConcept] = None  # Specifies which method should be used to aggregate measure observation values. For most scoring t...

@dataclass
class MeasureGroupStratifier:
    """
    MeasureGroupStratifier nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    linkId: Optional[str] = None  # An identifier that is unique within the Measure allowing linkage to the equivalent item in a Meas...
    code: Optional[CodeableConcept] = None  # Indicates a meaning for the stratifier. This can be as simple as a unique identifier, or it can e...
    description: Optional[str] = None  # The human readable description of this stratifier criteria.
    criteria: Optional[Expression] = None  # An expression that specifies the criteria for the stratifier. This is typically the name of an ex...
    groupDefinition: Optional[Reference] = None  # A Group resource that defines this population as a set of characteristics.
    component: Optional[List[BackboneElement]] = field(default_factory=list)  # A component of the stratifier criteria for the measure report, specified as either the name of a ...

@dataclass
class MeasureGroupStratifierComponent:
    """
    MeasureGroupStratifierComponent nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    linkId: Optional[str] = None  # An identifier that is unique within the Measure allowing linkage to the equivalent item in a Meas...
    code: Optional[CodeableConcept] = None  # Indicates a meaning for the stratifier component. This can be as simple as a unique identifier, o...
    description: Optional[str] = None  # The human readable description of this stratifier criteria component.
    criteria: Optional[Expression] = None  # An expression that specifies the criteria for this component of the stratifier. This is typically...
    groupDefinition: Optional[Reference] = None  # A Group resource that defines this population as a set of characteristics.

@dataclass
class MeasureSupplementalData:
    """
    MeasureSupplementalData nested class.
    """

    criteria: Optional[Expression] = None  # The criteria for the supplemental data. This is typically the name of a valid expression defined ...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    linkId: Optional[str] = None  # An identifier that is unique within the Measure allowing linkage to the equivalent item in a Meas...
    code: Optional[CodeableConcept] = None  # Indicates a meaning for the supplemental data. This can be as simple as a unique identifier, or i...
    usage: Optional[List[CodeableConcept]] = field(default_factory=list)  # An indicator of the intended usage for the supplemental data element. Supplemental data indicates...
    description: Optional[str] = None  # The human readable description of this supplemental data.


@dataclass
class Measure(FHIRResource):
    """
    Supports declaration of the Measure metadata required by HL7 and other organizations that share and publish measures with a focus on the aspects of that metadata that are important for post-publication activities including distribution, inclusion in repositories, consumption, and implementation.
    """

    url: Optional[str] = None  # An absolute URI that is used to identify this measure when it is referenced in a specification, m...
    version: Optional[str] = None  # The identifier that is used to identify this version of the measure when it is referenced in a sp...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the measure.
    status: Optional[str] = None  # The status of this measure. Enables tracking the life-cycle of the content.
    date: Optional[str] = None  # The date  (and optionally time) when the measure was last significantly changed. The date must ch...
    description: Optional[str] = None  # A free text natural language description of the measure from a consumer's perspective.
    resourceType: str = "Measure"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this measure when it is represented in other formats...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    name: Optional[str] = None  # A natural language name identifying the measure. This name should be usable as an identifier for ...
    subtitle: Optional[str] = None  # An explanatory or alternate title for the measure giving additional information about its content.
    experimental: Optional[bool] = None  # A Boolean value to indicate that this measure is authored for testing purposes (or education/eval...
    subject: Optional[Any] = None  # The intended subjects for the measure. If this element is not provided, a Patient subject is assu...
    basis: Optional[str] = None  # The population basis specifies the type of elements in the population. For a subject-based measur...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the measure is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this measure is needed and why it has been designed as it has.
    usage: Optional[str] = None  # A detailed description, from a clinical perspective, of how the measure is used.
    copyright: Optional[str] = None  # A copyright statement relating to the measure and/or its contents. Copyright statements are gener...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the resource content was approved by the publisher. Approval happens once when ...
    lastReviewDate: Optional[str] = None  # The date on which the resource content was last reviewed. Review happens periodically after appro...
    effectivePeriod: Optional[Period] = None  # The period during which the measure content was or is planned to be in active use.
    topic: Optional[List[CodeableConcept]] = field(default_factory=list)  # Descriptive topics related to the content of the measure. Topics provide a high-level categorizat...
    author: Optional[List[ContactDetail]] = field(default_factory=list)  # An individiual or organization primarily involved in the creation and maintenance of the content.
    editor: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization primarily responsible for internal coherence of the content.
    reviewer: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be primarily responsible for review of...
    endorser: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be responsible for officially endorsin...
    relatedArtifact: Optional[List[RelatedArtifact]] = field(default_factory=list)  # Related artifacts such as additional documentation, justification, or bibliographic references.
    library: Optional[List[str]] = field(default_factory=list)  # A reference to a Library resource containing the formal logic used by the measure.
    disclaimer: Optional[str] = None  # Notices and disclaimers regarding the use of the measure or related to intellectual property (suc...
    scoring: Optional[CodeableConcept] = None  # Indicates how the calculation is performed for the measure, including proportion, ratio, continuo...
    scoringUnit: Optional[CodeableConcept] = None  # Defines the expected units of measure for the measure score. This element SHOULD be specified as ...
    compositeScoring: Optional[CodeableConcept] = None  # If this is a composite measure, the scoring method used to combine the component measures to dete...
    type: Optional[List[CodeableConcept]] = field(default_factory=list)  # Indicates whether the measure is used to examine a process, an outcome over time, a patient-repor...
    riskAdjustment: Optional[str] = None  # A description of the risk adjustment factors that may impact the resulting score for the measure ...
    rateAggregation: Optional[str] = None  # Describes how to combine the information calculated, based on logic in each of several population...
    rationale: Optional[str] = None  # Provides a succinct statement of the need for the measure. Usually includes statements pertaining...
    clinicalRecommendationStatement: Optional[str] = None  # Provides a summary of relevant clinical guidelines or other clinical recommendations supporting t...
    improvementNotation: Optional[CodeableConcept] = None  # Information on whether an increase or decrease in score is the preferred result (e.g., a higher s...
    term: Optional[List[BackboneElement]] = field(default_factory=list)  # Provides a description of an individual term used within the measure.
    guidance: Optional[str] = None  # Additional guidance for the measure including how it can be used in a clinical context, and the i...
    group: Optional[List[BackboneElement]] = field(default_factory=list)  # A group of population criteria for the measure.
    supplementalData: Optional[List[BackboneElement]] = field(default_factory=list)  # The supplemental data criteria for the measure report, specified as either the name of a valid CQ...