# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 MedicationRequest resource.

An order or request for both supply of the medication and the instructions for administration of the medication to a patient. The resource is called "MedicationRequest" rather than "MedicationPrescription" or "MedicationOrder" to generalize the use across inpatient and outpatient settings, including care plans, etc., and to harmonize with workflow patterns.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Annotation, BackboneElement, CodeableConcept, Dosage, Duration, Extension, Identifier, Period, Quantity, Reference
from typing import Any, List, Optional

@dataclass
class MedicationRequestDispenseRequest:
    """
    MedicationRequestDispenseRequest nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    initialFill: Optional[BackboneElement] = None  # Indicates the quantity or duration for the first dispense of the medication.
    quantity: Optional[Quantity] = None  # The amount or quantity to provide as part of the first dispense.
    duration: Optional[Duration] = None  # The length of time that the first dispense is expected to last.
    dispenseInterval: Optional[Duration] = None  # The minimum period of time that must occur between dispenses of the medication.
    validityPeriod: Optional[Period] = None  # This indicates the validity period of a prescription (stale dating the Prescription).
    numberOfRepeatsAllowed: Optional[int] = None  # An integer indicating the number of times, in addition to the original dispense, (aka refills or ...
    expectedSupplyDuration: Optional[Duration] = None  # Identifies the period time over which the supplied product is expected to be used, or the length ...
    dispenser: Optional[Reference] = None  # Indicates the intended performing Organization that will dispense the medication as specified by ...
    dispenserInstruction: Optional[List[Annotation]] = field(default_factory=list)  # Provides additional information to the dispenser, for example, counselling to be provided to the ...
    doseAdministrationAid: Optional[CodeableConcept] = None  # Provides information about the type of adherence packaging to be supplied for the medication disp...

@dataclass
class MedicationRequestDispenseRequestInitialFill:
    """
    MedicationRequestDispenseRequestInitialFill nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    quantity: Optional[Quantity] = None  # The amount or quantity to provide as part of the first dispense.
    duration: Optional[Duration] = None  # The length of time that the first dispense is expected to last.

@dataclass
class MedicationRequestSubstitution:
    """
    MedicationRequestSubstitution nested class.
    """

    allowed: Optional[Any] = None  # True if the prescriber allows a different drug to be dispensed from what was prescribed.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    reason: Optional[CodeableConcept] = None  # Indicates the reason for the substitution, or why substitution must or must not be performed.


@dataclass
class MedicationRequest(FHIRResource):
    """
    An order or request for both supply of the medication and the instructions for administration of the medication to a patient. The resource is called "MedicationRequest" rather than "MedicationPrescription" or "MedicationOrder" to generalize the use across inpatient and outpatient settings, including care plans, etc., and to harmonize with workflow patterns.
    """

    status: Optional[str] = None  # A code specifying the current state of the order.  Generally, this will be active or completed st...
    intent: Optional[str] = None  # Whether the request is a proposal, plan, or an original order.
    medication: Optional[Any] = None  # Identifies the medication being requested. This is a link to a resource that represents the medic...
    subject: Optional[Reference] = None  # The individual or group for whom the medication has been requested.
    resourceType: str = "MedicationRequest"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # Identifiers associated with this medication request that are defined by business processes and/or...
    basedOn: Optional[List[Reference]] = field(default_factory=list)  # A plan or request that is fulfilled in whole or in part by this medication request.
    priorPrescription: Optional[Reference] = None  # Reference to an order/prescription that is being replaced by this MedicationRequest.
    groupIdentifier: Optional[Identifier] = None  # A shared identifier common to multiple independent Request instances that were activated/authoriz...
    statusReason: Optional[CodeableConcept] = None  # Captures the reason for the current state of the MedicationRequest.
    statusChanged: Optional[str] = None  # The date (and perhaps time) when the status was changed.
    category: Optional[List[CodeableConcept]] = field(default_factory=list)  # An arbitrary categorization or grouping of the medication request.  It could be used for indicati...
    priority: Optional[str] = None  # Indicates how quickly the Medication Request should be addressed with respect to other requests.
    doNotPerform: Optional[bool] = None  # If true, indicates that the provider is asking for the patient to either stop taking or to not st...
    informationSource: Optional[List[Reference]] = field(default_factory=list)  # The person or organization who provided the information about this request, if the source is some...
    encounter: Optional[Reference] = None  # The Encounter during which this [x] was created or to which the creation of this record is tightl...
    supportingInformation: Optional[List[Reference]] = field(default_factory=list)  # Information to support fulfilling (i.e. dispensing or administering) of the medication, for examp...
    authoredOn: Optional[str] = None  # The date (and perhaps time) when the prescription was initially written or authored on.
    requester: Optional[Reference] = None  # The individual, organization, or device that initiated the request and has responsibility for its...
    reported: Optional[bool] = None  # Indicates if this record was captured as a secondary 'reported' record rather than as an original...
    performerType: Optional[CodeableConcept] = None  # Indicates the type of performer of the administration of the medication.
    performer: Optional[List[Reference]] = field(default_factory=list)  # The specified desired performer of the medication treatment (e.g. the performer of the medication...
    device: Optional[List[Any]] = field(default_factory=list)  # The intended type of device that is to be used for the administration of the medication (for exam...
    recorder: Optional[Reference] = None  # The person who entered the order on behalf of another individual for example in the case of a ver...
    reason: Optional[List[Any]] = field(default_factory=list)  # The reason or the indication for ordering or not ordering the medication.
    courseOfTherapyType: Optional[CodeableConcept] = None  # The description of the overall pattern of the administration of the medication to the patient.
    insurance: Optional[List[Reference]] = field(default_factory=list)  # Insurance plans, coverage extensions, pre-authorizations and/or pre-determinations that may be re...
    note: Optional[List[Annotation]] = field(default_factory=list)  # Extra information about the prescription that could not be conveyed by the other attributes.
    renderedDosageInstruction: Optional[str] = None  # The full representation of the dose of the medication included in all dosage instructions.  To be...
    effectiveDosePeriod: Optional[Period] = None  # The period over which the medication is to be taken.  Where there are multiple dosageInstruction ...
    dosageInstruction: Optional[List[Dosage]] = field(default_factory=list)  # Specific instructions for how the medication is to be used by the patient.
    dispenseRequest: Optional[BackboneElement] = None  # Indicates the specific details for the dispense or medication supply part of a medication request...
    substitution: Optional[BackboneElement] = None  # Indicates whether or not substitution can or should be part of the dispense. In some cases, subst...
    eventHistory: Optional[List[Reference]] = field(default_factory=list)  # Links to Provenance records for past versions of this resource or fulfilling request or event res...