# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 MetadataResource resource.

Common Interface declaration for conformance and knowledge artifact resources.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import CodeableConcept, Coding, ContactDetail, Identifier, Period, RelatedArtifact, UsageContext
from typing import Any, List, Optional

@dataclass
class MetadataResource(FHIRResource):
    """
    Common Interface declaration for conformance and knowledge artifact resources.
    """

    status: Optional[str] = None  # The current state of this {{title}}.
    resourceType: str = "MetadataResource"
    url: Optional[str] = None  # An absolute URI that is used to identify this {{title}} when it is referenced in a specification,...
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this {{title}} when it is represented in other forma...
    version: Optional[str] = None  # The identifier that is used to identify this version of the {{title}} when it is referenced in a ...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    name: Optional[str] = None  # A natural language name identifying the {{title}}. This name should be usable as an identifier fo...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the {{title}}.
    experimental: Optional[bool] = None  # A Boolean value to indicate that this {{title}} is authored for testing purposes (or education/ev...
    date: Optional[str] = None  # The date (and optionally time) when the {{title}} was last significantly changed. The date must c...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    description: Optional[str] = None  # A free text natural language description of the {{title}} from a consumer's perspective.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the {{title}} is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this {{title}} is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the {{title}} and/or its contents. Copyright statements are gen...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the resource content was approved by the publisher. Approval happens once when ...
    lastReviewDate: Optional[str] = None  # The date on which the resource content was last reviewed. Review happens periodically after appro...
    effectivePeriod: Optional[Period] = None  # The period during which the {{title}} content was or is planned to be in active use.
    topic: Optional[List[CodeableConcept]] = field(default_factory=list)  # Descriptive topics related to the content of the {{title}}. Topics provide a high-level categoriz...
    author: Optional[List[ContactDetail]] = field(default_factory=list)  # An individiual or organization primarily involved in the creation and maintenance of the {{title}}.
    editor: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization primarily responsible for internal coherence of the {{title}}.
    reviewer: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be primarily responsible for review of...
    endorser: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be responsible for officially endorsin...
    relatedArtifact: Optional[List[RelatedArtifact]] = field(default_factory=list)  # Related artifacts such as additional documentation, justification, dependencies, bibliographic re...