# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 MolecularSequence resource.

Representation of a molecular sequence.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Attachment, BackboneElement, CodeableConcept, Extension, Identifier, Range, Reference
from typing import Any, List, Optional

@dataclass
class MolecularSequenceRelative:
    """
    MolecularSequenceRelative nested class.
    """

    coordinateSystem: Optional[CodeableConcept] = None  # These are different ways of identifying nucleotides or amino acids within a sequence. Different d...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    ordinalPosition: Optional[int] = None  # Indicates the order in which the sequence should be considered when putting multiple 'relative' e...
    sequenceRange: Optional[Range] = None  # Indicates the nucleotide range in the composed sequence when multiple 'relative' elements are use...
    startingSequence: Optional[BackboneElement] = None  # A sequence that is used as a starting sequence to describe variants that are present in a sequenc...
    genomeAssembly: Optional[CodeableConcept] = None  # The genome assembly used for starting sequence, e.g. GRCh38.
    chromosome: Optional[CodeableConcept] = None  # Structural unit composed of a nucleic acid molecule which controls its own replication through th...
    sequence: Optional[Any] = None  # The reference sequence that represents the starting sequence.
    windowStart: Optional[int] = None  # Start position of the window on the starting sequence. This value should honor the rules of the c...
    windowEnd: Optional[int] = None  # End position of the window on the starting sequence. This value should honor the rules of the  co...
    orientation: Optional[str] = None  # A relative reference to a DNA strand based on gene orientation. The strand that contains the open...
    strand: Optional[str] = None  # An absolute reference to a strand. The Watson strand is the strand whose 5'-end is on the short a...
    edit: Optional[List[BackboneElement]] = field(default_factory=list)  # Changes in sequence from the starting sequence.
    start: Optional[int] = None  # Start position of the edit on the starting sequence. If the coordinate system is either 0-based o...
    end: Optional[int] = None  # End position of the edit on the starting sequence. If the coordinate system is 0-based then end i...
    replacementSequence: Optional[str] = None  # Allele that was observed. Nucleotide(s)/amino acids from start position of sequence to stop posit...
    replacedSequence: Optional[str] = None  # Allele in the starting sequence. Nucleotide(s)/amino acids from start position of sequence to sto...

@dataclass
class MolecularSequenceRelativeStartingSequence:
    """
    MolecularSequenceRelativeStartingSequence nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    genomeAssembly: Optional[CodeableConcept] = None  # The genome assembly used for starting sequence, e.g. GRCh38.
    chromosome: Optional[CodeableConcept] = None  # Structural unit composed of a nucleic acid molecule which controls its own replication through th...
    sequence: Optional[Any] = None  # The reference sequence that represents the starting sequence.
    windowStart: Optional[int] = None  # Start position of the window on the starting sequence. This value should honor the rules of the c...
    windowEnd: Optional[int] = None  # End position of the window on the starting sequence. This value should honor the rules of the  co...
    orientation: Optional[str] = None  # A relative reference to a DNA strand based on gene orientation. The strand that contains the open...
    strand: Optional[str] = None  # An absolute reference to a strand. The Watson strand is the strand whose 5'-end is on the short a...

@dataclass
class MolecularSequenceRelativeEdit:
    """
    MolecularSequenceRelativeEdit nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    start: Optional[int] = None  # Start position of the edit on the starting sequence. If the coordinate system is either 0-based o...
    end: Optional[int] = None  # End position of the edit on the starting sequence. If the coordinate system is 0-based then end i...
    replacementSequence: Optional[str] = None  # Allele that was observed. Nucleotide(s)/amino acids from start position of sequence to stop posit...
    replacedSequence: Optional[str] = None  # Allele in the starting sequence. Nucleotide(s)/amino acids from start position of sequence to sto...


@dataclass
class MolecularSequence(FHIRResource):
    """
    Representation of a molecular sequence.
    """

    resourceType: str = "MolecularSequence"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A unique identifier for this particular sequence instance.
    type: Optional[str] = None  # Amino Acid Sequence/ DNA Sequence / RNA Sequence.
    subject: Optional[Reference] = None  # Indicates the subject this sequence is associated too.
    focus: Optional[List[Reference]] = field(default_factory=list)  # The actual focus of a molecular sequence when it is not the patient of record representing someth...
    specimen: Optional[Reference] = None  # Specimen used for sequencing.
    device: Optional[Reference] = None  # The method for sequencing, for example, chip information.
    performer: Optional[Reference] = None  # The organization or lab that should be responsible for this result.
    literal: Optional[str] = None  # Sequence that was observed.
    formatted: Optional[List[Attachment]] = field(default_factory=list)  # Sequence that was observed as file content. Can be an actual file contents, or referenced by a UR...
    relative: Optional[List[BackboneElement]] = field(default_factory=list)  # A sequence defined relative to another sequence.