# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 NamingSystem resource.

Defines and enforces the minimum expectations for publication and distribution of a naming system, typically as part of an artifact repository or implementation guide publication
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Coding, ContactDetail, Extension, Identifier, Period, RelatedArtifact, UsageContext
from typing import Any, List, Optional

@dataclass
class NamingSystemUniqueId:
    """
    NamingSystemUniqueId nested class.
    """

    type: Optional[str] = None  # Identifies the unique identifier scheme used for this particular identifier.
    value: Optional[str] = None  # The string that should be sent over the wire to identify the code system or identifier system.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    preferred: Optional[bool] = None  # Indicates whether this identifier is the \"preferred\" identifier of this type.
    comment: Optional[str] = None  # Notes about the past or intended usage of this identifier.
    period: Optional[Period] = None  # Identifies the period of time over which this identifier is considered appropriate to refer to th...
    authoritative: Optional[bool] = None  # Indicates whether this identifier ie endorsed by the official owner of the associated naming system.


@dataclass
class NamingSystem(FHIRResource):
    """
    Defines and enforces the minimum expectations for publication and distribution of a naming system, typically as part of an artifact repository or implementation guide publication
    """

    url: Optional[str] = None  # An absolute URI that is used to identify this naming system when it is referenced in a specificat...
    version: Optional[str] = None  # The identifier that is used to identify this version of the naming system when it is referenced i...
    name: Optional[str] = None  # A natural language name identifying the naming system. This name should be usable as an identifie...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the naming system.
    status: Optional[str] = None  # The status of this naming system. Enables tracking the life-cycle of the content.
    kind: Optional[str] = None  # Indicates the purpose for the naming system - what kinds of things does it make unique?
    date: Optional[str] = None  # The date  (and optionally time) when the naming system was last significantly changed. The date m...
    description: Optional[str] = None  # A free text natural language description of the naming system from a consumer's perspective. Deta...
    uniqueId: List[BackboneElement] = field(default_factory=list)  # Indicates how the system may be identified when referenced in electronic exchange.
    resourceType: str = "NamingSystem"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this naming system when it is represented in other f...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which NamingSystem is more current.
    experimental: Optional[bool] = None  # A Boolean value to indicate that this naming system is authored for testing purposes (or educatio...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    responsible: Optional[str] = None  # The name of the organization that is responsible for issuing identifiers or codes for this namesp...
    type: Optional[CodeableConcept] = None  # Categorizes a naming system for easier search by grouping related naming systems.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the naming system is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this naming system is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the naming system and/or its contents. Copyright statements are...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the resource content was approved by the publisher. Approval happens once when ...
    lastReviewDate: Optional[str] = None  # The date on which the resource content was last reviewed. Review happens periodically after appro...
    effectivePeriod: Optional[Period] = None  # The period during which the NamingSystem content was or is planned to be in active use.
    topic: Optional[List[CodeableConcept]] = field(default_factory=list)  # Descriptions related to the content of the NamingSystem. Topics provide a high-level categorizati...
    author: Optional[List[ContactDetail]] = field(default_factory=list)  # An individiual or organization primarily involved in the creation and maintenance of the NamingSy...
    editor: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization primarily responsible for internal coherence of the NamingSystem.
    reviewer: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be primarily responsible for review of...
    endorser: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be responsible for officially endorsin...
    relatedArtifact: Optional[List[RelatedArtifact]] = field(default_factory=list)  # Related artifacts such as additional documentation, justification, dependencies, bibliographic re...
    usage: Optional[str] = None  # Provides guidance on the use of the namespace, including the handling of formatting characters, u...