# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 NutritionOrder resource.

A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to a patient/resident.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Annotation, BackboneElement, CodeableConcept, Extension, Identifier, Quantity, Ratio, Reference, Timing
from typing import Any, List, Optional

@dataclass
class NutritionOrderOralDiet:
    """
    NutritionOrderOralDiet nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    type: Optional[List[CodeableConcept]] = field(default_factory=list)  # The kind of diet or dietary restriction such as fiber restricted diet or diabetic diet.
    schedule: Optional[BackboneElement] = None  # Schedule information for an oral diet.
    timing: Optional[List[Timing]] = field(default_factory=list)  # The time period and frequency at which the diet should be given.  The diet should be given for th...
    asNeeded: Optional[bool] = None  # Indicates whether the product is only taken when needed within a specific dosing schedule.
    asNeededFor: Optional[CodeableConcept] = None  # Indicates whether the product is only taken based on a precondition for taking the product.
    nutrient: Optional[List[BackboneElement]] = field(default_factory=list)  # Class that defines the quantity and type of nutrient modifications (for example carbohydrate, fib...
    modifier: Optional[CodeableConcept] = None  # The nutrient that is being modified such as carbohydrate or sodium.
    amount: Optional[Quantity] = None  # The quantity of the specified nutrient to include in diet.
    texture: Optional[List[BackboneElement]] = field(default_factory=list)  # Class that describes any texture modifications required for the patient to safely consume various...
    foodType: Optional[CodeableConcept] = None  # The food type(s) (e.g. meats, all foods)  that the texture modification applies to.  This could b...
    fluidConsistencyType: Optional[List[CodeableConcept]] = field(default_factory=list)  # The required consistency (e.g. honey-thick, nectar-thick, thin, thickened.) of liquids or fluids ...
    instruction: Optional[str] = None  # Free text or additional instructions or information pertaining to the oral diet.

@dataclass
class NutritionOrderOralDietSchedule:
    """
    NutritionOrderOralDietSchedule nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    timing: Optional[List[Timing]] = field(default_factory=list)  # The time period and frequency at which the diet should be given.  The diet should be given for th...
    asNeeded: Optional[bool] = None  # Indicates whether the product is only taken when needed within a specific dosing schedule.
    asNeededFor: Optional[CodeableConcept] = None  # Indicates whether the product is only taken based on a precondition for taking the product.

@dataclass
class NutritionOrderOralDietNutrient:
    """
    NutritionOrderOralDietNutrient nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifier: Optional[CodeableConcept] = None  # The nutrient that is being modified such as carbohydrate or sodium.
    amount: Optional[Quantity] = None  # The quantity of the specified nutrient to include in diet.

@dataclass
class NutritionOrderOralDietTexture:
    """
    NutritionOrderOralDietTexture nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifier: Optional[CodeableConcept] = None  # Any texture modifications (for solid foods) that should be made, e.g. easy to chew, chopped, grou...
    foodType: Optional[CodeableConcept] = None  # The food type(s) (e.g. meats, all foods)  that the texture modification applies to.  This could b...

@dataclass
class NutritionOrderSupplement:
    """
    NutritionOrderSupplement nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    type: Optional[Any] = None  # The kind of nutritional supplement product required such as a high protein or pediatric clear liq...
    productName: Optional[str] = None  # The product or brand name of the nutritional supplement such as \"Acme Protein Shake\".
    schedule: Optional[BackboneElement] = None  # Schedule information for a supplement.
    timing: Optional[List[Timing]] = field(default_factory=list)  # The time period and frequency at which the supplement should be given.  The supplement should be ...
    asNeeded: Optional[bool] = None  # Indicates whether the supplement is only taken when needed within a specific dosing schedule.
    asNeededFor: Optional[CodeableConcept] = None  # Indicates whether the supplement is only taken based on a precondition for taking the supplement.
    quantity: Optional[Quantity] = None  # The amount of the nutritional supplement to be given.
    instruction: Optional[str] = None  # Free text or additional instructions or information pertaining to the oral supplement.

@dataclass
class NutritionOrderSupplementSchedule:
    """
    NutritionOrderSupplementSchedule nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    timing: Optional[List[Timing]] = field(default_factory=list)  # The time period and frequency at which the supplement should be given.  The supplement should be ...
    asNeeded: Optional[bool] = None  # Indicates whether the supplement is only taken when needed within a specific dosing schedule.
    asNeededFor: Optional[CodeableConcept] = None  # Indicates whether the supplement is only taken based on a precondition for taking the supplement.

@dataclass
class NutritionOrderEnteralFormula:
    """
    NutritionOrderEnteralFormula nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    baseFormulaType: Optional[Any] = None  # The type of enteral or infant formula such as an adult standard formula with fiber or a soy-based...
    baseFormulaProductName: Optional[str] = None  # The product or brand name of the enteral or infant formula product such as \"ACME Adult Standard ...
    deliveryDevice: Optional[List[Any]] = field(default_factory=list)  # The intended type of device that is to be used for the administration of the enteral formula.
    additive: Optional[List[BackboneElement]] = field(default_factory=list)  # Indicates modular components to be provided in addition or mixed with the base formula.
    type: Optional[Any] = None  # Indicates the type of modular component such as protein, carbohydrate, fat or fiber to be provide...
    productName: Optional[str] = None  # The product or brand name of the type of modular component to be added to the formula.
    quantity: Optional[Quantity] = None  # The amount of additive to be given in addition or to be mixed in with the base formula.
    caloricDensity: Optional[Quantity] = None  # The amount of energy (calories) that the formula should provide per specified volume, typically p...
    routeOfAdministration: Optional[CodeableConcept] = None  # The route or physiological path of administration into the patient's gastrointestinal  tract for ...
    administration: Optional[List[BackboneElement]] = field(default_factory=list)  # Formula administration instructions as structured data.  This repeating structure allows for chan...
    schedule: Optional[BackboneElement] = None  # Schedule information for an enteral formula.
    timing: Optional[List[Timing]] = field(default_factory=list)  # The time period and frequency at which the enteral formula should be given.  The enteral formula ...
    asNeeded: Optional[bool] = None  # Indicates whether the enteral formula is only taken when needed within a specific dosing schedule.
    asNeededFor: Optional[CodeableConcept] = None  # Indicates whether the enteral formula is only taken based on a precondition for taking the entera...
    rate: Optional[Any] = None  # The rate of administration of formula via a feeding pump, e.g. 60 mL per hour, according to the s...
    maxVolumeToDeliver: Optional[Quantity] = None  # The maximum total quantity of formula that may be administered to a subject over the period of ti...
    administrationInstruction: Optional[str] = None  # Free text formula administration, feeding instructions or additional instructions or information.

@dataclass
class NutritionOrderEnteralFormulaAdditive:
    """
    NutritionOrderEnteralFormulaAdditive nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    type: Optional[Any] = None  # Indicates the type of modular component such as protein, carbohydrate, fat or fiber to be provide...
    productName: Optional[str] = None  # The product or brand name of the type of modular component to be added to the formula.
    quantity: Optional[Quantity] = None  # The amount of additive to be given in addition or to be mixed in with the base formula.

@dataclass
class NutritionOrderEnteralFormulaAdministration:
    """
    NutritionOrderEnteralFormulaAdministration nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    schedule: Optional[BackboneElement] = None  # Schedule information for an enteral formula.
    timing: Optional[List[Timing]] = field(default_factory=list)  # The time period and frequency at which the enteral formula should be given.  The enteral formula ...
    asNeeded: Optional[bool] = None  # Indicates whether the enteral formula is only taken when needed within a specific dosing schedule.
    asNeededFor: Optional[CodeableConcept] = None  # Indicates whether the enteral formula is only taken based on a precondition for taking the entera...
    quantity: Optional[Quantity] = None  # The volume of formula to provide to the patient per the specified administration schedule.
    rate: Optional[Any] = None  # The rate of administration of formula via a feeding pump, e.g. 60 mL per hour, according to the s...

@dataclass
class NutritionOrderEnteralFormulaAdministrationSchedule:
    """
    NutritionOrderEnteralFormulaAdministrationSchedule nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    timing: Optional[List[Timing]] = field(default_factory=list)  # The time period and frequency at which the enteral formula should be given.  The enteral formula ...
    asNeeded: Optional[bool] = None  # Indicates whether the enteral formula is only taken when needed within a specific dosing schedule.
    asNeededFor: Optional[CodeableConcept] = None  # Indicates whether the enteral formula is only taken based on a precondition for taking the entera...


@dataclass
class NutritionOrder(FHIRResource):
    """
    A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to a patient/resident.
    """

    status: Optional[str] = None  # The workflow status of the nutrition order/request.
    intent: Optional[str] = None  # Indicates the level of authority/intentionality associated with the NutrionOrder and where the re...
    subject: Optional[Reference] = None  # The person or set of individuals who needs the nutrition order for an oral diet, nutritional supp...
    dateTime: Optional[str] = None  # The date and time that this nutrition order was requested.
    resourceType: str = "NutritionOrder"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # Identifiers assigned to this order by the order sender or by the order receiver.
    instantiatesCanonical: Optional[List[str]] = field(default_factory=list)  # The URL pointing to a FHIR-defined protocol, guideline, orderset or other definition that is adhe...
    instantiatesUri: Optional[List[str]] = field(default_factory=list)  # The URL pointing to an externally maintained protocol, guideline, orderset or other definition th...
    instantiates: Optional[List[str]] = field(default_factory=list)  # The URL pointing to a protocol, guideline, orderset or other definition that is adhered to in who...
    basedOn: Optional[List[Reference]] = field(default_factory=list)  # A plan or request that is fulfilled in whole or in part by this nutrition order.
    groupIdentifier: Optional[Identifier] = None  # A shared identifier common to all nutrition orders that were authorized more or less simultaneous...
    priority: Optional[str] = None  # Indicates how quickly the Nutrition Order should be addressed with respect to other        requests.
    encounter: Optional[Reference] = None  # An encounter that provides additional information about the healthcare context in which this requ...
    supportingInformation: Optional[List[Reference]] = field(default_factory=list)  # Information to support fulfilling (i.e. dispensing or administering) of the nutrition,        for...
    orderer: Optional[Reference] = None  # The practitioner that holds legal responsibility for ordering the diet, nutritional supplement, o...
    performer: Optional[List[Any]] = field(default_factory=list)  # The specified desired performer of the nutrition order.
    allergyIntolerance: Optional[List[Reference]] = field(default_factory=list)  # A link to a record of allergies or intolerances  which should be included in the nutrition order.
    foodPreferenceModifier: Optional[List[CodeableConcept]] = field(default_factory=list)  # This modifier is used to convey order-specific modifiers about the type of food that should be gi...
    excludeFoodModifier: Optional[List[CodeableConcept]] = field(default_factory=list)  # This modifier is used to convey Order-specific modifier about the type of oral food or oral fluid...
    outsideFoodAllowed: Optional[bool] = None  # This modifier is used to convey whether a food item is allowed to be brought in by the patient an...
    oralDiet: Optional[BackboneElement] = None  # Diet given orally in contrast to enteral (tube) feeding.
    supplement: Optional[List[BackboneElement]] = field(default_factory=list)  # Oral nutritional products given in order to add further nutritional value to the patient's diet.
    enteralFormula: Optional[BackboneElement] = None  # Feeding provided through the gastrointestinal tract via a tube, catheter, or stoma that delivers ...
    note: Optional[List[Annotation]] = field(default_factory=list)  # Comments made about the {{title}} by the requester, performer, subject or other participants.