# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 ObservationDefinition resource.

Set of definitional characteristics for a kind of observation or measurement produced or consumed by an orderable health care service.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Coding, ContactDetail, Extension, Identifier, Period, Range, Reference, UsageContext
from typing import Any, List, Optional

@dataclass
class ObservationDefinitionQualifiedValue:
    """
    ObservationDefinitionQualifiedValue nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    context: Optional[CodeableConcept] = None  # A concept defining the context for this set of qualified values.
    appliesTo: Optional[List[CodeableConcept]] = field(default_factory=list)  # The target population this  set of qualified values applies to.
    gender: Optional[str] = None  # The gender this  set of qualified values applies to.
    age: Optional[Range] = None  # The age range this  set of qualified values applies to.
    gestationalAge: Optional[Range] = None  # The gestational age this  set of qualified values applies to.
    condition: Optional[str] = None  # Text based condition for which the the set of qualified values is valid.
    rangeCategory: Optional[str] = None  # The category of range of values for continuous or ordinal observations that match the criteria of...
    range: Optional[Range] = None  # The range of values defined for continuous or ordinal observations that match the criteria of thi...
    validCodedValueSet: Optional[str] = None  # The set of valid coded results for qualitative observations  that match the criteria of this set ...
    normalCodedValueSet: Optional[str] = None  # The set of normal coded results for qualitative observations  that match the criteria of this set...
    abnormalCodedValueSet: Optional[str] = None  # The set of abnormal coded results for qualitative observations  that match the criteria of this s...
    criticalCodedValueSet: Optional[str] = None  # The set of critical coded results for qualitative observations  that match the criteria of this s...

@dataclass
class ObservationDefinitionComponent:
    """
    ObservationDefinitionComponent nested class.
    """

    code: Optional[CodeableConcept] = None  # Describes what will be observed.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    permittedDataType: Optional[List[str]] = field(default_factory=list)  # The data types allowed for the value element of the instance of this component observations.
    permittedUnit: Optional[List[Coding]] = field(default_factory=list)  # Units allowed for the valueQuantity element in the instance observations conforming to this Obser...
    qualifiedValue: Optional[List[Any]] = field(default_factory=list)  # A set of qualified values associated with a context and a set of conditions -  provides a range f...


@dataclass
class ObservationDefinition(FHIRResource):
    """
    Set of definitional characteristics for a kind of observation or measurement produced or consumed by an orderable health care service.
    """

    status: Optional[str] = None  # The current state of the ObservationDefinition.
    code: Optional[CodeableConcept] = None  # Describes what will be observed. Sometimes this is called the observation \"name\".
    resourceType: str = "ObservationDefinition"
    url: Optional[str] = None  # An absolute URL that is used to identify this ObservationDefinition when it is referenced in a sp...
    identifier: Optional[Identifier] = None  # Business identifiers assigned to this ObservationDefinition. by the performer and/or other system...
    version: Optional[str] = None  # The identifier that is used to identify this version of the ObservationDefinition when it is refe...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    name: Optional[str] = None  # A natural language name identifying the ObservationDefinition. This name should be usable as an i...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the ObservationDefinition.
    experimental: Optional[bool] = None  # A flag to indicate that this ObservationDefinition is authored for testing purposes (or education...
    date: Optional[str] = None  # The date (and optionally time) when the ObservationDefinition was last significantly changed. The...
    publisher: Optional[str] = None  # Helps establish the \"authority/credibility\" of the ObservationDefinition. May also allow for co...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    description: Optional[str] = None  # A free text natural language description of the ObservationDefinition from the consumer's perspec...
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A jurisdiction in which the ObservationDefinition is intended to be used.
    purpose: Optional[str] = None  # Explains why this ObservationDefinition is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # Copyright statement relating to the ObservationDefinition and/or its contents. Copyright statemen...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the asset content was approved by the publisher. Approval happens once when the...
    lastReviewDate: Optional[str] = None  # The date on which the asset content was last reviewed. Review happens periodically after that, bu...
    effectivePeriod: Optional[Period] = None  # The period during which the ObservationDefinition content was or is planned to be effective.
    derivedFromCanonical: Optional[List[str]] = field(default_factory=list)  # The canonical URL pointing to another FHIR-defined ObservationDefinition that is adhered to in wh...
    derivedFromUri: Optional[List[str]] = field(default_factory=list)  # The URL pointing to an externally-defined observation definition, guideline or other definition t...
    subject: Optional[List[CodeableConcept]] = field(default_factory=list)  # A code that describes the intended kind of subject of Observation instances conforming to this Ob...
    performerType: Optional[CodeableConcept] = None  # The type of individual/organization/device that is expected to act upon instances of this definit...
    category: Optional[List[CodeableConcept]] = field(default_factory=list)  # A code that classifies the general type of observation.
    permittedDataType: Optional[List[str]] = field(default_factory=list)  # The data types allowed for the value element of the instance observations conforming to this Obse...
    multipleResultsAllowed: Optional[bool] = None  # Multiple results allowed for observations conforming to this ObservationDefinition.
    bodySite: Optional[CodeableConcept] = None  # The site on the subject's body where the  observation is to be made.
    method: Optional[CodeableConcept] = None  # The method or technique used to perform the observation.
    specimen: Optional[List[Reference]] = field(default_factory=list)  # The kind of specimen that this type of observation is produced on.
    device: Optional[List[Reference]] = field(default_factory=list)  # The measurement model of device or actual device used to produce observations of this type.
    preferredReportName: Optional[str] = None  # The preferred name to be used when reporting the results of observations conforming to this Obser...
    permittedUnit: Optional[List[Coding]] = field(default_factory=list)  # Units allowed for the valueQuantity element in the instance observations conforming to this Obser...
    qualifiedValue: Optional[List[BackboneElement]] = field(default_factory=list)  # A set of qualified values associated with a context and a set of conditions -  provides a range f...
    hasMember: Optional[List[Reference]] = field(default_factory=list)  # This ObservationDefinition defines a group  observation (e.g. a battery, a panel of tests, a set ...
    component: Optional[List[BackboneElement]] = field(default_factory=list)  # Some observations have multiple component observations, expressed as separate code value pairs.