# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 Observation resource.

Measurements and simple assertions made about a patient, device or other subject.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Annotation, Attachment, BackboneElement, CodeableConcept, Extension, Identifier, Period, Quantity, Range, Ratio, Reference, SampledData, Timing
from typing import Any, List, Optional

@dataclass
class ObservationTriggeredBy:
    """
    ObservationTriggeredBy nested class.
    """

    observation: Optional[Reference] = None  # Reference to the triggering observation.
    type: Optional[str] = None  # The type of trigger. Reflex | Repeat | Re-run.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    reason: Optional[str] = None  # Provides the reason why this observation was performed as a result of the observation(s) referenced.

@dataclass
class ObservationReferenceRange:
    """
    ObservationReferenceRange nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    low: Optional[Quantity] = None  # The value of the low bound of the reference range.  The low bound of the reference range endpoint...
    high: Optional[Quantity] = None  # The value of the high bound of the reference range.  The high bound of the reference range endpoi...
    normalValue: Optional[CodeableConcept] = None  # The value of the normal value of the reference range.
    type: Optional[CodeableConcept] = None  # Codes to indicate the what part of the targeted reference population it applies to. For example, ...
    appliesTo: Optional[List[CodeableConcept]] = field(default_factory=list)  # Codes to indicate the target population this reference range applies to.  For example, a referenc...
    age: Optional[Range] = None  # The age at which this reference range is applicable. This is a neonatal age (e.g. number of weeks...
    text: Optional[str] = None  # Text based reference range in an observation which may be used when a quantitative range is not a...

@dataclass
class ObservationComponent:
    """
    ObservationComponent nested class.
    """

    code: Optional[CodeableConcept] = None  # Describes what was observed. Sometimes this is called the observation \"code\".
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    value: Optional[Any] = None  # The information determined as a result of making the observation, if the information has a simple...
    dataAbsentReason: Optional[CodeableConcept] = None  # Provides a reason why the expected value in the element Observation.component.value[x] is missing.
    interpretation: Optional[List[CodeableConcept]] = field(default_factory=list)  # A categorical assessment of an observation value.  For example, high, low, normal.
    referenceRange: Optional[List[Any]] = field(default_factory=list)  # Guidance on how to interpret the value by comparison to a normal or recommended range.


@dataclass
class Observation(FHIRResource):
    """
    Measurements and simple assertions made about a patient, device or other subject.
    """

    status: Optional[str] = None  # The status of the result value.
    code: Optional[CodeableConcept] = None  # Describes what was observed. Sometimes this is called the observation \"name\".
    resourceType: str = "Observation"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A unique identifier assigned to this observation.
    instantiates: Optional[Any] = None  # The reference to a FHIR ObservationDefinition resource that provides the definition that is adher...
    basedOn: Optional[List[Reference]] = field(default_factory=list)  # A plan, proposal or order that is fulfilled in whole or in part by this event.  For example, a Me...
    triggeredBy: Optional[List[ObservationTriggeredBy]] = field(default_factory=list)  # Identifies the observation(s) that triggered the performance of this observation.
    partOf: Optional[List[Reference]] = field(default_factory=list)  # A larger event of which this particular Observation is a component or step.  For example,  an obs...
    category: Optional[List[CodeableConcept]] = field(default_factory=list)  # A code that classifies the general type of observation being made.
    subject: Optional[Reference] = None  # The patient, or group of patients, location, device, organization, procedure or practitioner this...
    focus: Optional[List[Reference]] = field(default_factory=list)  # The actual focus of an observation when it is not the patient of record representing something or...
    encounter: Optional[Reference] = None  # The healthcare event  (e.g. a patient and healthcare provider interaction) during which this obse...
    effective: Optional[Any] = None  # The time or time-period the observed value is asserted as being true. For biological subjects - e...
    issued: Optional[str] = None  # The date and time this version of the observation was made available to providers, typically afte...
    performer: Optional[List[Reference]] = field(default_factory=list)  # Who was responsible for asserting the observed value as \"true\".
    value: Optional[Any] = None  # The information determined as a result of making the observation, if the information has a simple...
    dataAbsentReason: Optional[CodeableConcept] = None  # Provides a reason why the expected value in the element Observation.value[x] is missing.
    interpretation: Optional[List[CodeableConcept]] = field(default_factory=list)  # A categorical assessment of an observation value.  For example, high, low, normal.
    note: Optional[List[Annotation]] = field(default_factory=list)  # Comments about the observation or the results.
    bodySite: Optional[CodeableConcept] = None  # Indicates the site on the subject's body where the observation was made (i.e. the target site).
    bodyStructure: Optional[Reference] = None  # Indicates the body structure on the subject's body where the observation was made (i.e. the targe...
    method: Optional[CodeableConcept] = None  # Indicates the mechanism used to perform the observation.
    specimen: Optional[Reference] = None  # The specimen that was used when this observation was made.
    device: Optional[Reference] = None  # A reference to the device that generates the measurements or the device settings for the device.
    referenceRange: Optional[List[ObservationReferenceRange]] = field(default_factory=list)  # Guidance on how to interpret the value by comparison to a normal or recommended range.  Multiple ...
    hasMember: Optional[List[Reference]] = field(default_factory=list)  # This observation is a group observation (e.g. a battery, a panel of tests, a set of vital sign me...
    derivedFrom: Optional[List[Reference]] = field(default_factory=list)  # The target resource that represents a measurement from which this observation value is derived. F...
    component: Optional[List[ObservationComponent]] = field(default_factory=list)  # Some observations have multiple component observations.  These component observations are express...