# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 OperationDefinition resource.

A formal computable definition of an operation (on the RESTful interface) or a named query (using the search interaction).
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Coding, ContactDetail, Extension, Identifier, UsageContext
from typing import Any, List, Optional

@dataclass
class OperationDefinitionParameter:
    """
    OperationDefinitionParameter nested class.
    """

    name: Optional[str] = None  # The name of used to identify the parameter.
    use: Optional[str] = None  # Whether this is an input or an output parameter.
    min: Optional[int] = None  # The minimum number of times this parameter SHALL appear in the request or response.
    max: Optional[str] = None  # The maximum number of times this element is permitted to appear in the request or response.
    strength: Optional[str] = None  # Indicates the degree of conformance expectations associated with this binding - that is, the degr...
    valueSet: Optional[str] = None  # Points to the value set or external definition (e.g. implicit value set) that identifies the set ...
    source: Optional[str] = None  # The name of the parameter or dot-separated path of parameter names pointing to the resource param...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    scope: Optional[List[str]] = field(default_factory=list)  # If present, indicates that the parameter applies when the operation is being invoked at the speci...
    documentation: Optional[str] = None  # Describes the meaning or use of this parameter.
    type: Optional[str] = None  # The type for this parameter.
    allowedType: Optional[List[str]] = field(default_factory=list)  # Support for polymorphic types. If the parameter type is abstract, this element lists allowed sub-...
    targetProfile: Optional[List[str]] = field(default_factory=list)  # Used when the type is \"Reference\" or \"canonical\", and identifies a profile structure or imple...
    searchType: Optional[str] = None  # How the parameter is understood if/when it used as search parameter. This is only used if the par...
    binding: Optional[BackboneElement] = None  # Binds to a value set if this parameter is coded (code, Coding, CodeableConcept).
    referencedFrom: Optional[List[BackboneElement]] = field(default_factory=list)  # Identifies other resource parameters within the operation invocation that are expected to resolve...
    sourceId: Optional[str] = None  # The id of the element in the referencing resource that is expected to resolve to this resource.
    part: Optional[List[Any]] = field(default_factory=list)  # The parts of a nested Parameter.

@dataclass
class OperationDefinitionParameterBinding:
    """
    OperationDefinitionParameterBinding nested class.
    """

    strength: Optional[str] = None  # Indicates the degree of conformance expectations associated with this binding - that is, the degr...
    valueSet: Optional[str] = None  # Points to the value set or external definition (e.g. implicit value set) that identifies the set ...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class OperationDefinitionParameterReferencedFrom:
    """
    OperationDefinitionParameterReferencedFrom nested class.
    """

    source: Optional[str] = None  # The name of the parameter or dot-separated path of parameter names pointing to the resource param...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    sourceId: Optional[str] = None  # The id of the element in the referencing resource that is expected to resolve to this resource.

@dataclass
class OperationDefinitionOverload:
    """
    OperationDefinitionOverload nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    parameterName: Optional[List[str]] = field(default_factory=list)  # Name of parameter to include in overload.
    comment: Optional[str] = None  # Comments to go on overload.


@dataclass
class OperationDefinition(FHIRResource):
    """
    A formal computable definition of an operation (on the RESTful interface) or a named query (using the search interaction).
    """

    name: Optional[str] = None  # A natural language name identifying the operation definition. This name should be usable as an id...
    status: Optional[str] = None  # The current state of this operation definition.
    kind: Optional[str] = None  # Whether this is an operation or a named query.
    code: Optional[str] = None  # The label that is recommended to be used in the URL for this operation. In some cases, servers ma...
    system: Optional[bool] = None  # Indicates whether this operation or named query can be invoked at the system level (e.g. without ...
    type: Optional[bool] = None  # Indicates whether this operation or named query can be invoked at the resource type level for any...
    instance: Optional[bool] = None  # Indicates whether this operation can be invoked on a particular instance of one of the given types.
    resourceType: str = "OperationDefinition"
    url: Optional[str] = None  # An absolute URI that is used to identify this operation definition when it is referenced in a spe...
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this implementation guide when it is represented in ...
    version: Optional[str] = None  # The identifier that is used to identify this version of the operation definition when it is refer...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the operation definition.
    experimental: Optional[bool] = None  # A Boolean value to indicate that this operation definition is authored for testing purposes (or e...
    date: Optional[str] = None  # The date  (and optionally time) when the operation definition was last significantly changed. The...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    description: Optional[str] = None  # A free text natural language description of the operation definition from a consumer's perspective.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the operation definition is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this operation definition is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the operation definition and/or its contents. Copyright stateme...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    affectsState: Optional[bool] = None  # Whether the operation affects state. Side effects such as producing audit trail entries do not co...
    comment: Optional[str] = None  # Additional information about how to use this operation or named query.
    base: Optional[str] = None  # Indicates that this operation definition is a constraining profile on the base.
    resource: Optional[List[str]] = field(default_factory=list)  # The types on which this operation can be executed.
    inputProfile: Optional[str] = None  # Additional validation information for the in parameters - a single profile that covers all the pa...
    outputProfile: Optional[str] = None  # Additional validation information for the out parameters - a single profile that covers all the p...
    parameter: Optional[List[BackboneElement]] = field(default_factory=list)  # The parameters for the operation/query.
    overload: Optional[List[BackboneElement]] = field(default_factory=list)  # Defines an appropriate combination of parameters to use when invoking this operation, to help cod...