# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 PackagedProductDefinition resource.

A medically related item or items, in a container or package.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Attachment, BackboneElement, CodeableConcept, Extension, Identifier, Quantity, Reference
from typing import Any, List, Optional

@dataclass
class PackagedProductDefinitionLegalStatusOfSupply:
    """
    PackagedProductDefinitionLegalStatusOfSupply nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    code: Optional[CodeableConcept] = None  # The actual status of supply. Conveys in what situation this package type may be supplied for use.
    jurisdiction: Optional[CodeableConcept] = None  # The place where the legal status of supply applies. When not specified, this indicates it is unkn...

@dataclass
class PackagedProductDefinitionPackaging:
    """
    PackagedProductDefinitionPackaging nested class.
    """

    item: Optional[Any] = None  # The actual item(s) of medication, as manufactured, or a device (typically, but not necessarily, a...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A business identifier that is specific to this particular part of the packaging, often assigned b...
    type: Optional[CodeableConcept] = None  # The physical type of the container of the items.
    componentPart: Optional[bool] = None  # Is this a part of the packaging (e.g. a cap or bottle stopper), rather than the packaging itself ...
    quantity: Optional[int] = None  # The quantity of packaging items contained at this layer of the package. This does not relate to t...
    material: Optional[List[CodeableConcept]] = field(default_factory=list)  # Material type of the package item.
    alternateMaterial: Optional[List[CodeableConcept]] = field(default_factory=list)  # A possible alternate material for this part of the packaging, that is allowed to be used instead ...
    shelfLifeStorage: Optional[List[Any]] = field(default_factory=list)  # Shelf Life and storage information.
    manufacturer: Optional[List[Reference]] = field(default_factory=list)  # Manufacturer of this packaging item. When there are multiple values each one is a potential manuf...
    property: Optional[List[BackboneElement]] = field(default_factory=list)  # General characteristics of this item.
    value: Optional[Any] = None  # A value for the characteristic.
    containedItem: Optional[List[BackboneElement]] = field(default_factory=list)  # The item(s) within the packaging.
    amount: Optional[Quantity] = None  # The number of this type of item within this packaging or for continuous items such as liquids it ...
    packaging: Optional[List[Any]] = field(default_factory=list)  # Allows containers (and parts of containers) within containers, still as a part of a single packag...

@dataclass
class PackagedProductDefinitionPackagingProperty:
    """
    PackagedProductDefinitionPackagingProperty nested class.
    """

    type: Optional[CodeableConcept] = None  # A code expressing the type of characteristic.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    value: Optional[Any] = None  # A value for the characteristic.

@dataclass
class PackagedProductDefinitionPackagingContainedItem:
    """
    PackagedProductDefinitionPackagingContainedItem nested class.
    """

    item: Optional[Any] = None  # The actual item(s) of medication, as manufactured, or a device (typically, but not necessarily, a...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    amount: Optional[Quantity] = None  # The number of this type of item within this packaging or for continuous items such as liquids it ...


@dataclass
class PackagedProductDefinition(FHIRResource):
    """
    A medically related item or items, in a container or package.
    """

    resourceType: str = "PackagedProductDefinition"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A unique identifier for this package as whole - not the the content of the package. Unique instan...
    name: Optional[str] = None  # A name for this package. Typically what it would be listed as in a drug formulary or catalogue, i...
    type: Optional[CodeableConcept] = None  # A high level category e.g. medicinal product, raw material, shipping/transport container, etc.
    packageFor: Optional[List[Reference]] = field(default_factory=list)  # The product this package model relates to, not the contents of the package (for which see package...
    status: Optional[CodeableConcept] = None  # The status within the lifecycle of this item. A high level status, this is not intended to duplic...
    statusDate: Optional[str] = None  # The date at which the given status became applicable.
    containedItemQuantity: Optional[List[Quantity]] = field(default_factory=list)  # A total of the complete count of contained items of a particular type/form, independent of sub-pa...
    description: Optional[str] = None  # Textual description. Note that this is not the name of the package or product.
    legalStatusOfSupply: Optional[List[BackboneElement]] = field(default_factory=list)  # The legal status of supply of the packaged item as classified by the regulator.
    marketingStatus: Optional[List[Any]] = field(default_factory=list)  # Allows specifying that an item is on the market for sale, or that it is not available, and the da...
    copackagedIndicator: Optional[bool] = None  # Identifies if the package contains different items, such as when a drug product is supplied with ...
    manufacturer: Optional[List[Reference]] = field(default_factory=list)  # Manufacturer of this package type. When there are multiple it means these are all possible manufa...
    attachedDocument: Optional[List[Reference]] = field(default_factory=list)  # Additional information or supporting documentation about the packaged product.
    packaging: Optional[BackboneElement] = None  # A packaging item, as a container for medically related items, possibly with other packaging items...
    characteristic: Optional[List[Any]] = field(default_factory=list)  # Allows the key features to be recorded, such as \"hospital pack\", \"nurse prescribable\", \"cale...