# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 Procedure resource.

An action that is or was performed on or for a patient, practitioner, device, organization, or location. For example, this can be a physical intervention on a patient like an operation, or less invasive like long term services, counseling, or hypnotherapy.  This can be a quality or safety inspection for a location, organization, or device.  This can be an accreditation procedure on a practitioner for licensing.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Age, Annotation, BackboneElement, CodeableConcept, Extension, Identifier, Period, Range, Reference, Timing
from typing import Any, List, Optional

@dataclass
class ProcedurePerformer:
    """
    ProcedurePerformer nested class.
    """

    actor: Optional[Reference] = None  # Indicates who or what performed the procedure.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    function: Optional[CodeableConcept] = None  # Distinguishes the type of involvement of the performer in the procedure. For example, surgeon, an...
    onBehalfOf: Optional[Reference] = None  # The Organization the Patient, RelatedPerson, Device, CareTeam, and HealthcareService was acting o...
    period: Optional[Period] = None  # Time period during which the performer performed the procedure.

@dataclass
class ProcedureFocalDevice:
    """
    ProcedureFocalDevice nested class.
    """

    manipulated: Optional[Reference] = None  # The device that was manipulated (changed) during the procedure.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    action: Optional[CodeableConcept] = None  # The kind of change that happened to the device during the procedure.


@dataclass
class Procedure(FHIRResource):
    """
    An action that is or was performed on or for a patient, practitioner, device, organization, or location. For example, this can be a physical intervention on a patient like an operation, or less invasive like long term services, counseling, or hypnotherapy.  This can be a quality or safety inspection for a location, organization, or device.  This can be an accreditation procedure on a practitioner for licensing.
    """

    status: Optional[str] = None  # A code specifying the state of the procedure. Generally, this will be the in-progress or complete...
    subject: Optional[Reference] = None  # On whom or on what the procedure was performed. This is usually an individual human, but can also...
    resourceType: str = "Procedure"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # Business identifiers assigned to this procedure by the performer or other systems which remain co...
    instantiatesCanonical: Optional[List[str]] = field(default_factory=list)  # The URL pointing to a FHIR-defined protocol, guideline, order set or other definition that is adh...
    instantiatesUri: Optional[List[str]] = field(default_factory=list)  # The URL pointing to an externally maintained protocol, guideline, order set or other definition t...
    basedOn: Optional[List[Reference]] = field(default_factory=list)  # A reference to a resource that contains details of the request for this procedure.
    partOf: Optional[List[Reference]] = field(default_factory=list)  # A larger event of which this particular procedure is a component or step.
    statusReason: Optional[CodeableConcept] = None  # Captures the reason for the current state of the procedure.
    category: Optional[List[CodeableConcept]] = field(default_factory=list)  # A code that classifies the procedure for searching, sorting and display purposes (e.g. \"Surgical...
    code: Optional[CodeableConcept] = None  # The specific procedure that is performed. Use text if the exact nature of the procedure cannot be...
    focus: Optional[Reference] = None  # Who is the target of the procedure when it is not the subject of record only.  If focus is not pr...
    encounter: Optional[Reference] = None  # The Encounter during which this Procedure was created or performed or to which the creation of th...
    occurrence: Optional[Any] = None  # Estimated or actual date, date-time, period, or age when the procedure did occur or is occurring....
    recorded: Optional[str] = None  # The date the occurrence of the procedure was first captured in the record regardless of Procedure...
    recorder: Optional[Reference] = None  # Individual who recorded the record and takes responsibility for its content.
    reported: Optional[Any] = None  # Indicates if this record was captured as a secondary 'reported' record rather than as an original...
    performer: Optional[List[BackboneElement]] = field(default_factory=list)  # Indicates who or what performed the procedure and how they were involved.
    location: Optional[Reference] = None  # The location where the procedure actually happened.  E.g. a newborn at home, a tracheostomy at a ...
    reason: Optional[List[Any]] = field(default_factory=list)  # The coded reason or reference why the procedure was performed. This may be a coded entity of some...
    bodySite: Optional[List[CodeableConcept]] = field(default_factory=list)  # Detailed and structured anatomical location information. Multiple locations are allowed - e.g. mu...
    outcome: Optional[CodeableConcept] = None  # The outcome of the procedure - did it resolve the reasons for the procedure being performed?
    report: Optional[List[Reference]] = field(default_factory=list)  # This could be a histology result, pathology report, surgical report, etc.
    complication: Optional[List[Any]] = field(default_factory=list)  # Any complications that occurred during the procedure, or in the immediate post-performance period...
    followUp: Optional[List[CodeableConcept]] = field(default_factory=list)  # If the procedure required specific follow up - e.g. removal of sutures. The follow up may be repr...
    note: Optional[List[Annotation]] = field(default_factory=list)  # Any other notes and comments about the procedure.
    focalDevice: Optional[List[BackboneElement]] = field(default_factory=list)  # A device that is implanted, removed or otherwise manipulated (calibration, battery replacement, f...
    used: Optional[List[Any]] = field(default_factory=list)  # Identifies medications, devices and any other substance used as part of the procedure.
    supportingInfo: Optional[List[Reference]] = field(default_factory=list)  # Other resources from the patient record that may be relevant to the procedure.  The information f...