# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 Questionnaire resource.

A structured set of questions intended to guide the collection of answers from end-users. Questionnaires provide detailed control over order, presentation, phraseology and grouping to allow coherent, consistent data collection.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import Attachment, BackboneElement, CodeableConcept, Coding, ContactDetail, Extension, Identifier, Period, Quantity, Reference, UsageContext
from typing import Any, List, Optional

@dataclass
class QuestionnaireItem:
    """
    QuestionnaireItem nested class.
    """

    linkId: Optional[str] = None  # An identifier that is unique within the Questionnaire allowing linkage to the equivalent item in ...
    type: Optional[str] = None  # The type of questionnaire item this is - whether text for display, a grouping of other items or a...
    question: Optional[str] = None  # The linkId for the question whose answer (or lack of answer) governs whether this item is enabled.
    operator: Optional[str] = None  # Specifies the criteria by which the question is enabled.
    answer: Optional[Any] = None  # A value that the referenced question is tested using the specified operator in order for the item...
    value: Optional[Any] = None  # A potential answer that's allowed as the answer to this question.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    definition: Optional[str] = None  # This element is a URI that refers to an [ElementDefinition](elementdefinition.html) or to an [Obs...
    code: Optional[List[Coding]] = field(default_factory=list)  # A terminology code that corresponds to this group or question (e.g. a code from LOINC, which defi...
    prefix: Optional[str] = None  # A short label for a particular group, question or set of display text within the questionnaire us...
    text: Optional[str] = None  # The name of a section, the text of a question or text content for a display item.
    enableWhen: Optional[List[BackboneElement]] = field(default_factory=list)  # A constraint indicating that this item should only be enabled (displayed/allow answers to be capt...
    enableBehavior: Optional[str] = None  # Controls how multiple enableWhen values are interpreted -  whether all or any must be true.
    disabledDisplay: Optional[str] = None  # Indicates if and how items that are disabled (because enableWhen evaluates to 'false') should be ...
    required: Optional[bool] = None  # An indication, if true, that the item must be present in a \"completed\" QuestionnaireResponse.  ...
    repeats: Optional[bool] = None  # An indication, if true, that a QuestionnaireResponse for this item may include multiple answers a...
    readOnly: Optional[bool] = None  # An indication, when true, that the value cannot be changed by a human respondent to the Questionn...
    maxLength: Optional[int] = None  # The maximum number of characters that are permitted in the answer to be considered a \"valid\" Qu...
    answerConstraint: Optional[str] = None  # For items that have a defined set of allowed answers (via answerOption or answerValueSet), indica...
    answerValueSet: Optional[str] = None  # A reference to a value set containing a list of values representing permitted answers for a quest...
    answerOption: Optional[List[BackboneElement]] = field(default_factory=list)  # One of the permitted answers for the question.
    initialSelected: Optional[bool] = None  # Indicates whether the answer value is selected when the list of possible answers is initially shown.
    initial: Optional[List[BackboneElement]] = field(default_factory=list)  # One or more values that should be pre-populated in the answer when initially rendering the questi...
    item: Optional[List[Any]] = field(default_factory=list)  # Text, questions and other groups to be nested beneath a question or group.

@dataclass
class QuestionnaireItemEnableWhen:
    """
    QuestionnaireItemEnableWhen nested class.
    """

    question: Optional[str] = None  # The linkId for the question whose answer (or lack of answer) governs whether this item is enabled.
    operator: Optional[str] = None  # Specifies the criteria by which the question is enabled.
    answer: Optional[Any] = None  # A value that the referenced question is tested using the specified operator in order for the item...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class QuestionnaireItemAnswerOption:
    """
    QuestionnaireItemAnswerOption nested class.
    """

    value: Optional[Any] = None  # A potential answer that's allowed as the answer to this question.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    initialSelected: Optional[bool] = None  # Indicates whether the answer value is selected when the list of possible answers is initially shown.

@dataclass
class QuestionnaireItemInitial:
    """
    QuestionnaireItemInitial nested class.
    """

    value: Optional[Any] = None  # The actual value to for an initial answer.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...


@dataclass
class Questionnaire(FHIRResource):
    """
    A structured set of questions intended to guide the collection of answers from end-users. Questionnaires provide detailed control over order, presentation, phraseology and grouping to allow coherent, consistent data collection.
    """

    status: Optional[str] = None  # The current state of this questionnaire.
    resourceType: str = "Questionnaire"
    url: Optional[str] = None  # An absolute URI that is used to identify this questionnaire when it is referenced in a specificat...
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this questionnaire when it is represented in other f...
    version: Optional[str] = None  # The identifier that is used to identify this version of the questionnaire when it is referenced i...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    name: Optional[str] = None  # A natural language name identifying the questionnaire. This name should be usable as an identifie...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the questionnaire.
    derivedFrom: Optional[List[str]] = field(default_factory=list)  # The URL of a Questionnaire that this Questionnaire is based on.
    experimental: Optional[bool] = None  # A Boolean value to indicate that this questionnaire is authored for testing purposes (or educatio...
    subjectType: Optional[List[str]] = field(default_factory=list)  # The types of subjects that can be the subject of responses created for the questionnaire.
    date: Optional[str] = None  # The date  (and optionally time) when the questionnaire was last significantly changed. The date m...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    description: Optional[str] = None  # A free text natural language description of the questionnaire from a consumer's perspective.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the questionnaire is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this questionnaire is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the questionnaire and/or its contents. Copyright statements are...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the resource content was approved by the publisher. Approval happens once when ...
    lastReviewDate: Optional[str] = None  # The date on which the resource content was last reviewed. Review happens periodically after appro...
    effectivePeriod: Optional[Period] = None  # The period during which the questionnaire content was or is planned to be in active use.
    code: Optional[List[Coding]] = field(default_factory=list)  # An identifier for this collection of questions in a particular terminology such as LOINC.
    item: Optional[List[BackboneElement]] = field(default_factory=list)  # A particular question, question grouping or display text that is part of the questionnaire.