# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 StructureDefinition resource.

A definition of a FHIR structure. This resource is used to describe the underlying resources, data types defined in FHIR, and also for describing extensions and constraints on resources and data types.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Coding, ContactDetail, Extension, Identifier, UsageContext
from typing import Any, List, Optional

@dataclass
class StructureDefinitionMapping:
    """
    StructureDefinitionMapping nested class.
    """

    identity: Optional[str] = None  # An Internal id that is used to identify this mapping set when specific mappings are made.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    uri: Optional[str] = None  # An absolute URI that identifies the specification that this mapping is expressed to.
    name: Optional[str] = None  # A name for the specification that is being mapped to.
    comment: Optional[str] = None  # Comments about this mapping, including version notes, issues, scope limitations, and other import...

@dataclass
class StructureDefinitionContext:
    """
    StructureDefinitionContext nested class.
    """

    type: Optional[str] = None  # Defines how to interpret the expression that defines what the context of the extension is.
    expression: Optional[str] = None  # An expression that defines where an extension can be used in resources.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class StructureDefinitionSnapshot:
    """
    StructureDefinitionSnapshot nested class.
    """

    element: List[Any] = field(default_factory=list)  # Captures constraints on each element within the resource.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class StructureDefinitionDifferential:
    """
    StructureDefinitionDifferential nested class.
    """

    element: List[Any] = field(default_factory=list)  # Captures constraints on each element within the resource.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...


@dataclass
class StructureDefinition(FHIRResource):
    """
    A definition of a FHIR structure. This resource is used to describe the underlying resources, data types defined in FHIR, and also for describing extensions and constraints on resources and data types.
    """

    url: Optional[str] = None  # An absolute URI that is used to identify this structure definition when it is referenced in a spe...
    name: Optional[str] = None  # A natural language name identifying the structure definition. This name should be usable as an id...
    status: Optional[str] = None  # The status of this structure definition. Enables tracking the life-cycle of the content.
    kind: Optional[str] = None  # Defines the kind of structure that this definition is describing.
    abstract: Optional[bool] = None  # Whether structure this definition describes is abstract or not  - that is, whether the structure ...
    type: Optional[str] = None  # The type this structure describes. If the derivation kind is 'specialization' then this is the ma...
    resourceType: str = "StructureDefinition"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this structure definition when it is represented in ...
    version: Optional[str] = None  # The identifier that is used to identify this version of the structure definition when it is refer...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the structure definition.
    experimental: Optional[bool] = None  # A Boolean value to indicate that this structure definition is authored for testing purposes (or e...
    date: Optional[str] = None  # The date  (and optionally time) when the structure definition was last significantly changed. The...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    description: Optional[str] = None  # A free text natural language description of the structure definition from a consumer's perspective.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the structure definition is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this structure definition is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the structure definition and/or its contents. Copyright stateme...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    keyword: Optional[List[Coding]] = field(default_factory=list)  # (DEPRECATED) A set of key words or terms from external terminologies that may be used to assist w...
    fhirVersion: Optional[str] = None  # The version of the FHIR specification on which this StructureDefinition is based - this is the fo...
    mapping: Optional[List[BackboneElement]] = field(default_factory=list)  # An external specification that the content is mapped to.
    context: Optional[List[BackboneElement]] = field(default_factory=list)  # Identifies the types of resource or data type elements to which the extension can be applied. For...
    contextInvariant: Optional[List[str]] = field(default_factory=list)  # A set of rules as FHIRPath Invariants about when the extension can be used (e.g. co-occurrence va...
    baseDefinition: Optional[str] = None  # An absolute URI that is the base structure from which this type is derived, either by specializat...
    derivation: Optional[str] = None  # How the type relates to the baseDefinition.
    snapshot: Optional[BackboneElement] = None  # A snapshot view is expressed in a standalone form that can be used and interpreted without consid...
    differential: Optional[BackboneElement] = None  # A differential view is expressed relative to the base StructureDefinition - a statement of differ...