# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 SubscriptionTopic resource.

Describes a stream of resource state changes identified by trigger criteria and annotated with labels useful to filter projections from this topic.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Coding, ContactDetail, Extension, Identifier, Period, UsageContext
from typing import Any, List, Optional

@dataclass
class SubscriptionTopicResourceTrigger:
    """
    SubscriptionTopicResourceTrigger nested class.
    """

    resource: Optional[str] = None  # URL of the Resource that is the type used in this resource trigger.  Relative URLs are relative t...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    description: Optional[str] = None  # The human readable description of this resource trigger for the SubscriptionTopic -  for example,...
    supportedInteraction: Optional[List[str]] = field(default_factory=list)  # The FHIR RESTful interaction which can be used to trigger a notification for the SubscriptionTopi...
    queryCriteria: Optional[BackboneElement] = None  # The FHIR query based rules that the server should use to determine when to trigger a notification...
    previous: Optional[str] = None  # The FHIR query based rules are applied to the previous resource state (e.g., state before an upda...
    resultForCreate: Optional[str] = None  # For `create` interactions, should the `previous` criteria count as an automatic pass or an automa...
    current: Optional[str] = None  # The FHIR query based rules are applied to the current resource state (e.g., state after an update).
    resultForDelete: Optional[str] = None  # For 'delete' interactions, should the 'current' query criteria count as an automatic pass or an a...
    requireBoth: Optional[bool] = None  # If set to `true`, both the `current` and `previous` query criteria must evaluate `true` to trigge...
    fhirPathCriteria: Optional[str] = None  # The FHIRPath based rules that the server should use to determine when to trigger a notification f...

@dataclass
class SubscriptionTopicResourceTriggerQueryCriteria:
    """
    SubscriptionTopicResourceTriggerQueryCriteria nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    previous: Optional[str] = None  # The FHIR query based rules are applied to the previous resource state (e.g., state before an upda...
    resultForCreate: Optional[str] = None  # For `create` interactions, should the `previous` criteria count as an automatic pass or an automa...
    current: Optional[str] = None  # The FHIR query based rules are applied to the current resource state (e.g., state after an update).
    resultForDelete: Optional[str] = None  # For 'delete' interactions, should the 'current' query criteria count as an automatic pass or an a...
    requireBoth: Optional[bool] = None  # If set to `true`, both the `current` and `previous` query criteria must evaluate `true` to trigge...

@dataclass
class SubscriptionTopicEventTrigger:
    """
    SubscriptionTopicEventTrigger nested class.
    """

    event: Optional[CodeableConcept] = None  # A well-defined event which can be used to trigger notifications from the SubscriptionTopic.
    resource: Optional[str] = None  # URL of the Resource that is the focus type used in this event trigger.  Relative URLs are relativ...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    description: Optional[str] = None  # The human readable description of an event to trigger a notification for the SubscriptionTopic - ...

@dataclass
class SubscriptionTopicCanFilterBy:
    """
    SubscriptionTopicCanFilterBy nested class.
    """

    filterParameter: Optional[str] = None  # Either the canonical URL to a search parameter (like \"http://hl7.org/fhir/SearchParameter/encoun...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    description: Optional[str] = None  # Description of how this filtering parameter is intended to be used.
    resource: Optional[str] = None  # URL of the Resource that is the type used in this filter. This is the \"focus\" of the topic (or ...
    filterDefinition: Optional[str] = None  # Either the canonical URL to a search parameter (like \"http://hl7.org/fhir/SearchParameter/encoun...
    comparator: Optional[List[str]] = field(default_factory=list)  # Comparators allowed for the filter parameter.
    modifier: Optional[List[str]] = field(default_factory=list)  # Modifiers allowed for the filter parameter.

@dataclass
class SubscriptionTopicNotificationShape:
    """
    SubscriptionTopicNotificationShape nested class.
    """

    resource: Optional[str] = None  # URL of the Resource that is the type used in this shape. This is the 'focus' resource of the topi...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    include: Optional[List[str]] = field(default_factory=list)  # Search-style _include directives, rooted in the resource for this shape. Servers SHOULD include r...
    revInclude: Optional[List[str]] = field(default_factory=list)  # Search-style _revinclude directives, rooted in the resource for this shape. Servers SHOULD includ...


@dataclass
class SubscriptionTopic(FHIRResource):
    """
    Describes a stream of resource state changes identified by trigger criteria and annotated with labels useful to filter projections from this topic.
    """

    url: Optional[str] = None  # An absolute URI that is used to identify this subscription topic when it is referenced in a speci...
    status: Optional[str] = None  # The current state of the SubscriptionTopic.
    resourceType: str = "SubscriptionTopic"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # Business identifiers assigned to this subscription topic by the performer and/or other systems.  ...
    version: Optional[str] = None  # The identifier that is used to identify this version of the subscription topic when it is referen...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    name: Optional[str] = None  # A natural language name identifying the subscription topic This name should be usable as an ident...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the subscription topic.  For example, \"admission\".
    derivedFrom: Optional[List[str]] = field(default_factory=list)  # The canonical URL pointing to another FHIR-defined SubscriptionTopic that is adhered to in whole ...
    experimental: Optional[bool] = None  # A flag to indicate that this TopSubscriptionTopicic is authored for testing purposes (or educatio...
    date: Optional[str] = None  # The date (and optionally time) when the subscription topic was last significantly changed. The da...
    publisher: Optional[str] = None  # Helps establish the \"authority/credibility\" of the SubscriptionTopic.  May also allow for contact.
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    description: Optional[str] = None  # A free text natural language description of the Topic from the consumer's perspective.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A jurisdiction in which the Topic is intended to be used.
    purpose: Optional[str] = None  # Explains why this Topic is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the SubscriptionTopic and/or its contents. Copyright statements...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the asset content was approved by the publisher. Approval happens once when the...
    lastReviewDate: Optional[str] = None  # The date on which the asset content was last reviewed. Review happens periodically after that, bu...
    effectivePeriod: Optional[Period] = None  # The period during which the SubscriptionTopic content was or is planned to be effective.
    resourceTrigger: Optional[List[BackboneElement]] = field(default_factory=list)  # A definition of a resource-based event that triggers a notification based on the SubscriptionTopi...
    eventTrigger: Optional[List[BackboneElement]] = field(default_factory=list)  # Event definition which can be used to trigger the SubscriptionTopic.
    canFilterBy: Optional[List[BackboneElement]] = field(default_factory=list)  # List of properties by which Subscriptions on the SubscriptionTopic can be filtered. May be define...
    notificationShape: Optional[List[BackboneElement]] = field(default_factory=list)  # List of properties to describe the shape (e.g., resources) included in notifications from this Su...