# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 SubstanceSourceMaterial resource.

Source material shall capture information on the taxonomic and anatomical origins as well as the fraction of a material that can result in or can be modified to form a substance. This set of data elements shall be used to define polymer substances isolated from biological matrices. Taxonomic and anatomical origins shall be described using a controlled vocabulary as required. This information is captured for naturally derived polymers ( . starch) and structurally diverse substances. For Organisms belonging to the Kingdom Plantae the Substance level defines the fresh material of a single species or infraspecies, the Herbal Drug and the Herbal preparation. For Herbal preparations, the fraction information will be captured at the Substance information level and additional information for herbal extracts will be captured at the Specified Substance Group 1 information level. See for further explanation the Substance Class: Structurally Diverse and the herbal annex.
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Extension, Identifier
from typing import List, Optional

@dataclass
class SubstanceSourceMaterialFractionDescription:
    """
    SubstanceSourceMaterialFractionDescription nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    fraction: Optional[str] = None  # This element is capturing information about the fraction of a plant part, or human plasma for fra...
    materialType: Optional[CodeableConcept] = None  # The specific type of the material constituting the component. For Herbal preparations the particu...

@dataclass
class SubstanceSourceMaterialOrganism:
    """
    SubstanceSourceMaterialOrganism nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    family: Optional[CodeableConcept] = None  # The family of an organism shall be specified.
    genus: Optional[CodeableConcept] = None  # The genus of an organism shall be specified; refers to the Latin epithet of the genus element of ...
    species: Optional[CodeableConcept] = None  # The species of an organism shall be specified; refers to the Latin epithet of the species of the ...
    intraspecificType: Optional[CodeableConcept] = None  # The Intraspecific type of an organism shall be specified.
    intraspecificDescription: Optional[str] = None  # The intraspecific description of an organism shall be specified based on a controlled vocabulary....
    author: Optional[List[BackboneElement]] = field(default_factory=list)  # 4.9.13.6.1 Author type (Conditional).
    authorType: Optional[CodeableConcept] = None  # The type of author of an organism species shall be specified. The parenthetical author of an orga...
    authorDescription: Optional[str] = None  # The author of an organism species shall be specified. The author year of an organism shall also b...
    hybrid: Optional[BackboneElement] = None  # 4.9.13.8.1 Hybrid species maternal organism ID (Optional).
    maternalOrganismId: Optional[str] = None  # The identifier of the maternal species constituting the hybrid organism shall be specified based ...
    maternalOrganismName: Optional[str] = None  # The name of the maternal species constituting the hybrid organism shall be specified. For plants,...
    paternalOrganismId: Optional[str] = None  # The identifier of the paternal species constituting the hybrid organism shall be specified based ...
    paternalOrganismName: Optional[str] = None  # The name of the paternal species constituting the hybrid organism shall be specified.
    hybridType: Optional[CodeableConcept] = None  # The hybrid type of an organism shall be specified.
    organismGeneral: Optional[BackboneElement] = None  # 4.9.13.7.1 Kingdom (Conditional).
    kingdom: Optional[CodeableConcept] = None  # The kingdom of an organism shall be specified.
    phylum: Optional[CodeableConcept] = None  # The phylum of an organism shall be specified.
    class_: Optional[CodeableConcept] = None  # The class of an organism shall be specified.
    order: Optional[CodeableConcept] = None  # The order of an organism shall be specified,.

@dataclass
class SubstanceSourceMaterialOrganismAuthor:
    """
    SubstanceSourceMaterialOrganismAuthor nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    authorType: Optional[CodeableConcept] = None  # The type of author of an organism species shall be specified. The parenthetical author of an orga...
    authorDescription: Optional[str] = None  # The author of an organism species shall be specified. The author year of an organism shall also b...

@dataclass
class SubstanceSourceMaterialOrganismHybrid:
    """
    SubstanceSourceMaterialOrganismHybrid nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    maternalOrganismId: Optional[str] = None  # The identifier of the maternal species constituting the hybrid organism shall be specified based ...
    maternalOrganismName: Optional[str] = None  # The name of the maternal species constituting the hybrid organism shall be specified. For plants,...
    paternalOrganismId: Optional[str] = None  # The identifier of the paternal species constituting the hybrid organism shall be specified based ...
    paternalOrganismName: Optional[str] = None  # The name of the paternal species constituting the hybrid organism shall be specified.
    hybridType: Optional[CodeableConcept] = None  # The hybrid type of an organism shall be specified.

@dataclass
class SubstanceSourceMaterialOrganismOrganismGeneral:
    """
    SubstanceSourceMaterialOrganismOrganismGeneral nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    kingdom: Optional[CodeableConcept] = None  # The kingdom of an organism shall be specified.
    phylum: Optional[CodeableConcept] = None  # The phylum of an organism shall be specified.
    class_: Optional[CodeableConcept] = None  # The class of an organism shall be specified.
    order: Optional[CodeableConcept] = None  # The order of an organism shall be specified,.

@dataclass
class SubstanceSourceMaterialPartDescription:
    """
    SubstanceSourceMaterialPartDescription nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    part: Optional[CodeableConcept] = None  # Entity of anatomical origin of source material within an organism.
    partLocation: Optional[CodeableConcept] = None  # The detailed anatomic location when the part can be extracted from different anatomical locations...


@dataclass
class SubstanceSourceMaterial(FHIRResource):
    """
    Source material shall capture information on the taxonomic and anatomical origins as well as the fraction of a material that can result in or can be modified to form a substance. This set of data elements shall be used to define polymer substances isolated from biological matrices. Taxonomic and anatomical origins shall be described using a controlled vocabulary as required. This information is captured for naturally derived polymers ( . starch) and structurally diverse substances. For Organisms belonging to the Kingdom Plantae the Substance level defines the fresh material of a single species or infraspecies, the Herbal Drug and the Herbal preparation. For Herbal preparations, the fraction information will be captured at the Substance information level and additional information for herbal extracts will be captured at the Specified Substance Group 1 information level. See for further explanation the Substance Class: Structurally Diverse and the herbal annex.
    """

    resourceType: str = "SubstanceSourceMaterial"
    sourceMaterialClass: Optional[CodeableConcept] = None  # General high level classification of the source material specific to the origin of the material.
    sourceMaterialType: Optional[CodeableConcept] = None  # The type of the source material shall be specified based on a controlled vocabulary. For vaccines...
    sourceMaterialState: Optional[CodeableConcept] = None  # The state of the source material when extracted.
    organismId: Optional[Identifier] = None  # The unique identifier associated with the source material parent organism shall be specified.
    organismName: Optional[str] = None  # The organism accepted Scientific name shall be provided based on the organism taxonomy.
    parentSubstanceId: Optional[List[Identifier]] = field(default_factory=list)  # The parent of the herbal drug Ginkgo biloba, Leaf is the substance ID of the substance (fresh) of...
    parentSubstanceName: Optional[List[str]] = field(default_factory=list)  # The parent substance of the Herbal Drug, or Herbal preparation.
    countryOfOrigin: Optional[List[CodeableConcept]] = field(default_factory=list)  # The country where the plant material is harvested or the countries where the plasma is sourced fr...
    geographicalLocation: Optional[List[str]] = field(default_factory=list)  # The place/region where the plant is harvested or the places/regions where the animal source mater...
    developmentStage: Optional[CodeableConcept] = None  # Stage of life for animals, plants, insects and microorganisms. This information shall be provided...
    fractionDescription: Optional[List[BackboneElement]] = field(default_factory=list)  # Many complex materials are fractions of parts of plants, animals, or minerals. Fraction elements ...
    organism: Optional[BackboneElement] = None  # This subclause describes the organism which the substance is derived from. For vaccines, the pare...
    partDescription: Optional[List[BackboneElement]] = field(default_factory=list)  # To do.