# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 TestScript resource.

Enforces the minimum information set for the test script metadata required by HL7 and other organizations that share and publish test scripts
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Coding, ContactDetail, Extension, Identifier, Reference, UsageContext
from typing import Any, List, Optional

@dataclass
class TestScriptOrigin:
    """
    TestScriptOrigin nested class.
    """

    index: Optional[int] = None  # Abstract name given to an origin server in this test script.  The name is provided as a number st...
    profile: Optional[Coding] = None  # The type of origin profile the test system supports.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    url: Optional[str] = None  # The explicit url path of the origin server used in this test script.

@dataclass
class TestScriptDestination:
    """
    TestScriptDestination nested class.
    """

    index: Optional[int] = None  # Abstract name given to a destination server in this test script.  The name is provided as a numbe...
    profile: Optional[Coding] = None  # The type of destination profile the test system supports.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    url: Optional[str] = None  # The explicit url path of the destination server used in this test script.

@dataclass
class TestScriptMetadata:
    """
    TestScriptMetadata nested class.
    """

    url: Optional[str] = None  # URL to a particular requirement or feature within the FHIR specification.
    capability: List[BackboneElement] = field(default_factory=list)  # Capabilities that must exist and are assumed to function correctly on the FHIR server being tested.
    required: Optional[bool] = None  # Whether or not the test execution will require the given capabilities of the server in order for ...
    validated: Optional[bool] = None  # Whether or not the test execution will validate the given capabilities of the server in order for...
    capabilities: Optional[str] = None  # Minimum capabilities required of server for test script to execute successfully.   If server does...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    link: Optional[List[BackboneElement]] = field(default_factory=list)  # A link to the FHIR specification that this test is covering.
    description: Optional[str] = None  # Short description of the link.
    origin: Optional[List[int]] = field(default_factory=list)  # Which origin server these requirements apply to.
    destination: Optional[int] = None  # Which server these requirements apply to.

@dataclass
class TestScriptMetadataLink:
    """
    TestScriptMetadataLink nested class.
    """

    url: Optional[str] = None  # URL to a particular requirement or feature within the FHIR specification.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    description: Optional[str] = None  # Short description of the link.

@dataclass
class TestScriptMetadataCapability:
    """
    TestScriptMetadataCapability nested class.
    """

    required: Optional[bool] = None  # Whether or not the test execution will require the given capabilities of the server in order for ...
    validated: Optional[bool] = None  # Whether or not the test execution will validate the given capabilities of the server in order for...
    capabilities: Optional[str] = None  # Minimum capabilities required of server for test script to execute successfully.   If server does...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    description: Optional[str] = None  # Description of the capabilities that this test script is requiring the server to support.
    origin: Optional[List[int]] = field(default_factory=list)  # Which origin server these requirements apply to.
    destination: Optional[int] = None  # Which server these requirements apply to.
    link: Optional[List[str]] = field(default_factory=list)  # Links to the FHIR specification that describes this interaction and the resources involved in mor...

@dataclass
class TestScriptScope:
    """
    TestScriptScope nested class.
    """

    artifact: Optional[str] = None  # The specific conformance artifact being tested. The canonical reference can be version-specific.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    conformance: Optional[CodeableConcept] = None  # The expectation of whether the test must pass for the system to be considered conformant with the...
    phase: Optional[CodeableConcept] = None  # The phase of testing for this artifact: unit - development / implementation phase, integration - ...

@dataclass
class TestScriptFixture:
    """
    TestScriptFixture nested class.
    """

    autocreate: Optional[bool] = None  # Whether or not to implicitly create the fixture during setup. If true, the fixture is automatical...
    autodelete: Optional[bool] = None  # Whether or not to implicitly delete the fixture during teardown. If true, the fixture is automati...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    resource: Optional[Reference] = None  # Reference to the resource (containing the contents of the resource needed for operations). This i...

@dataclass
class TestScriptVariable:
    """
    TestScriptVariable nested class.
    """

    name: Optional[str] = None  # Descriptive name for this variable.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    defaultValue: Optional[str] = None  # A default, hard-coded, or user-defined value for this variable.
    description: Optional[str] = None  # A free text natural language description of the variable and its purpose.
    expression: Optional[str] = None  # The FHIRPath expression for a specific value to evaluate against the fixture body. When variables...
    headerField: Optional[str] = None  # Will be used to grab the HTTP header field value from the headers that sourceId is pointing to.
    hint: Optional[str] = None  # Displayable text string with hint help information to the user when entering a default value.
    path: Optional[str] = None  # XPath or JSONPath to evaluate against the fixture body.  When variables are defined, only one of ...
    sourceId: Optional[str] = None  # Fixture to evaluate the XPath/JSONPath expression or the headerField  against within this variable.

@dataclass
class TestScriptSetup:
    """
    TestScriptSetup nested class.
    """

    action: List[BackboneElement] = field(default_factory=list)  # Action would contain either an operation or an assertion.
    encodeRequestUrl: Optional[bool] = None  # Whether or not to implicitly send the request url in encoded format. The default is true to match...
    field_: Optional[str] = None  # The HTTP header field e.g. \"Accept\".
    value: Optional[str] = None  # The value of the header e.g. \"application/fhir+xml\".
    stopTestOnFail: Optional[bool] = None  # Whether or not the current test execution will stop on failure for this assert.
    warningOnly: Optional[bool] = None  # Whether or not the test execution will produce a warning only on error for this assert.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    operation: Optional[BackboneElement] = None  # The operation to perform.
    type: Optional[Coding] = None  # Server interaction or operation type.
    resource: Optional[str] = None  # The type of the FHIR resource. See the [resource list](resourcelist.html). Data type of uri is ne...
    label: Optional[str] = None  # The label would be used for tracking/logging purposes by test engines.
    description: Optional[str] = None  # The description would be used by test engines for tracking and reporting purposes.
    accept: Optional[str] = None  # The mime-type to use for RESTful operation in the 'Accept' header.
    contentType: Optional[str] = None  # The mime-type to use for RESTful operation in the 'Content-Type' header.
    destination: Optional[int] = None  # The server where the request message is destined for.  Must be one of the server numbers listed i...
    method: Optional[str] = None  # The HTTP method the test engine MUST use for this operation regardless of any other operation det...
    origin: Optional[int] = None  # The server where the request message originates from.  Must be one of the server numbers listed i...
    params: Optional[str] = None  # Path plus parameters after [type].  Used to set parts of the request URL explicitly.
    requestHeader: Optional[List[BackboneElement]] = field(default_factory=list)  # Header elements would be used to set HTTP headers.
    requestId: Optional[str] = None  # The fixture id (maybe new) to map to the request.
    responseId: Optional[str] = None  # The fixture id (maybe new) to map to the response.
    sourceId: Optional[str] = None  # The id of the fixture used as the body of a PUT or POST request.
    targetId: Optional[str] = None  # Id of fixture used for extracting the [id],  [type], and [vid] for GET requests.
    url: Optional[str] = None  # Complete request URL.
    assert_: Optional[BackboneElement] = None  # Evaluates the results of previous operations to determine if the server under test behaves approp...
    direction: Optional[str] = None  # The direction to use for the assertion.
    compareToSourceId: Optional[str] = None  # Id of the source fixture used as the contents to be evaluated by either the \"source/expression\"...
    compareToSourceExpression: Optional[str] = None  # The FHIRPath expression for a specific value to evaluate against the source fixture. When compare...
    compareToSourcePath: Optional[str] = None  # XPath or JSONPath expression to evaluate against the source fixture. When compareToSourceId is de...
    defaultManualCompletion: Optional[str] = None  # The default manual completion outcome applied to this assertion.
    expression: Optional[str] = None  # The FHIRPath expression to be evaluated against the request or response message contents - HTTP h...
    headerField: Optional[str] = None  # The HTTP header field name e.g. 'Location'.
    minimumId: Optional[str] = None  # The ID of a fixture. Asserts that the response contains at a minimum the fixture specified by min...
    navigationLinks: Optional[bool] = None  # Whether or not the test execution performs validation on the bundle navigation links.
    operator: Optional[str] = None  # The operator type defines the conditional behavior of the assert.
    path: Optional[str] = None  # The XPath or JSONPath expression to be evaluated against the fixture representing the response re...
    requestMethod: Optional[str] = None  # The request method or HTTP operation code to compare against that used by the client system under...
    requestURL: Optional[str] = None  # The value to use in a comparison against the request URL path string.
    response: Optional[str] = None  # continue | switchingProtocols | okay | created | accepted | nonAuthoritativeInformation | noConte...
    responseCode: Optional[str] = None  # The value of the HTTP response code to be tested.
    validateProfileId: Optional[str] = None  # The ID of the Profile to validate against.
    requirement: Optional[List[BackboneElement]] = field(default_factory=list)  # Links or references providing traceability to the testing requirements for this assert.
    link: Optional[Any] = None  # Link or reference providing traceability to the testing requirement for this test.

@dataclass
class TestScriptSetupAction:
    """
    TestScriptSetupAction nested class.
    """

    encodeRequestUrl: Optional[bool] = None  # Whether or not to implicitly send the request url in encoded format. The default is true to match...
    field_: Optional[str] = None  # The HTTP header field e.g. \"Accept\".
    value: Optional[str] = None  # The value of the header e.g. \"application/fhir+xml\".
    stopTestOnFail: Optional[bool] = None  # Whether or not the current test execution will stop on failure for this assert.
    warningOnly: Optional[bool] = None  # Whether or not the test execution will produce a warning only on error for this assert.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    operation: Optional[BackboneElement] = None  # The operation to perform.
    type: Optional[Coding] = None  # Server interaction or operation type.
    resource: Optional[str] = None  # The type of the FHIR resource. See the [resource list](resourcelist.html). Data type of uri is ne...
    label: Optional[str] = None  # The label would be used for tracking/logging purposes by test engines.
    description: Optional[str] = None  # The description would be used by test engines for tracking and reporting purposes.
    accept: Optional[str] = None  # The mime-type to use for RESTful operation in the 'Accept' header.
    contentType: Optional[str] = None  # The mime-type to use for RESTful operation in the 'Content-Type' header.
    destination: Optional[int] = None  # The server where the request message is destined for.  Must be one of the server numbers listed i...
    method: Optional[str] = None  # The HTTP method the test engine MUST use for this operation regardless of any other operation det...
    origin: Optional[int] = None  # The server where the request message originates from.  Must be one of the server numbers listed i...
    params: Optional[str] = None  # Path plus parameters after [type].  Used to set parts of the request URL explicitly.
    requestHeader: Optional[List[BackboneElement]] = field(default_factory=list)  # Header elements would be used to set HTTP headers.
    requestId: Optional[str] = None  # The fixture id (maybe new) to map to the request.
    responseId: Optional[str] = None  # The fixture id (maybe new) to map to the response.
    sourceId: Optional[str] = None  # The id of the fixture used as the body of a PUT or POST request.
    targetId: Optional[str] = None  # Id of fixture used for extracting the [id],  [type], and [vid] for GET requests.
    url: Optional[str] = None  # Complete request URL.
    assert_: Optional[BackboneElement] = None  # Evaluates the results of previous operations to determine if the server under test behaves approp...
    direction: Optional[str] = None  # The direction to use for the assertion.
    compareToSourceId: Optional[str] = None  # Id of the source fixture used as the contents to be evaluated by either the \"source/expression\"...
    compareToSourceExpression: Optional[str] = None  # The FHIRPath expression for a specific value to evaluate against the source fixture. When compare...
    compareToSourcePath: Optional[str] = None  # XPath or JSONPath expression to evaluate against the source fixture. When compareToSourceId is de...
    defaultManualCompletion: Optional[str] = None  # The default manual completion outcome applied to this assertion.
    expression: Optional[str] = None  # The FHIRPath expression to be evaluated against the request or response message contents - HTTP h...
    headerField: Optional[str] = None  # The HTTP header field name e.g. 'Location'.
    minimumId: Optional[str] = None  # The ID of a fixture. Asserts that the response contains at a minimum the fixture specified by min...
    navigationLinks: Optional[bool] = None  # Whether or not the test execution performs validation on the bundle navigation links.
    operator: Optional[str] = None  # The operator type defines the conditional behavior of the assert.
    path: Optional[str] = None  # The XPath or JSONPath expression to be evaluated against the fixture representing the response re...
    requestMethod: Optional[str] = None  # The request method or HTTP operation code to compare against that used by the client system under...
    requestURL: Optional[str] = None  # The value to use in a comparison against the request URL path string.
    response: Optional[str] = None  # continue | switchingProtocols | okay | created | accepted | nonAuthoritativeInformation | noConte...
    responseCode: Optional[str] = None  # The value of the HTTP response code to be tested.
    validateProfileId: Optional[str] = None  # The ID of the Profile to validate against.
    requirement: Optional[List[BackboneElement]] = field(default_factory=list)  # Links or references providing traceability to the testing requirements for this assert.
    link: Optional[Any] = None  # Link or reference providing traceability to the testing requirement for this test.

@dataclass
class TestScriptSetupActionOperation:
    """
    TestScriptSetupActionOperation nested class.
    """

    encodeRequestUrl: Optional[bool] = None  # Whether or not to implicitly send the request url in encoded format. The default is true to match...
    field_: Optional[str] = None  # The HTTP header field e.g. \"Accept\".
    value: Optional[str] = None  # The value of the header e.g. \"application/fhir+xml\".
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    type: Optional[Coding] = None  # Server interaction or operation type.
    resource: Optional[str] = None  # The type of the FHIR resource. See the [resource list](resourcelist.html). Data type of uri is ne...
    label: Optional[str] = None  # The label would be used for tracking/logging purposes by test engines.
    description: Optional[str] = None  # The description would be used by test engines for tracking and reporting purposes.
    accept: Optional[str] = None  # The mime-type to use for RESTful operation in the 'Accept' header.
    contentType: Optional[str] = None  # The mime-type to use for RESTful operation in the 'Content-Type' header.
    destination: Optional[int] = None  # The server where the request message is destined for.  Must be one of the server numbers listed i...
    method: Optional[str] = None  # The HTTP method the test engine MUST use for this operation regardless of any other operation det...
    origin: Optional[int] = None  # The server where the request message originates from.  Must be one of the server numbers listed i...
    params: Optional[str] = None  # Path plus parameters after [type].  Used to set parts of the request URL explicitly.
    requestHeader: Optional[List[BackboneElement]] = field(default_factory=list)  # Header elements would be used to set HTTP headers.
    requestId: Optional[str] = None  # The fixture id (maybe new) to map to the request.
    responseId: Optional[str] = None  # The fixture id (maybe new) to map to the response.
    sourceId: Optional[str] = None  # The id of the fixture used as the body of a PUT or POST request.
    targetId: Optional[str] = None  # Id of fixture used for extracting the [id],  [type], and [vid] for GET requests.
    url: Optional[str] = None  # Complete request URL.

@dataclass
class TestScriptSetupActionOperationRequestHeader:
    """
    TestScriptSetupActionOperationRequestHeader nested class.
    """

    field_: Optional[str] = None  # The HTTP header field e.g. \"Accept\".
    value: Optional[str] = None  # The value of the header e.g. \"application/fhir+xml\".
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class TestScriptSetupActionAssert:
    """
    TestScriptSetupActionAssert nested class.
    """

    stopTestOnFail: Optional[bool] = None  # Whether or not the current test execution will stop on failure for this assert.
    warningOnly: Optional[bool] = None  # Whether or not the test execution will produce a warning only on error for this assert.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    label: Optional[str] = None  # The label would be used for tracking/logging purposes by test engines.
    description: Optional[str] = None  # The description would be used by test engines for tracking and reporting purposes.
    direction: Optional[str] = None  # The direction to use for the assertion.
    compareToSourceId: Optional[str] = None  # Id of the source fixture used as the contents to be evaluated by either the \"source/expression\"...
    compareToSourceExpression: Optional[str] = None  # The FHIRPath expression for a specific value to evaluate against the source fixture. When compare...
    compareToSourcePath: Optional[str] = None  # XPath or JSONPath expression to evaluate against the source fixture. When compareToSourceId is de...
    contentType: Optional[str] = None  # The mime-type contents to compare against the request or response message 'Content-Type' header.
    defaultManualCompletion: Optional[str] = None  # The default manual completion outcome applied to this assertion.
    expression: Optional[str] = None  # The FHIRPath expression to be evaluated against the request or response message contents - HTTP h...
    headerField: Optional[str] = None  # The HTTP header field name e.g. 'Location'.
    minimumId: Optional[str] = None  # The ID of a fixture. Asserts that the response contains at a minimum the fixture specified by min...
    navigationLinks: Optional[bool] = None  # Whether or not the test execution performs validation on the bundle navigation links.
    operator: Optional[str] = None  # The operator type defines the conditional behavior of the assert.
    path: Optional[str] = None  # The XPath or JSONPath expression to be evaluated against the fixture representing the response re...
    requestMethod: Optional[str] = None  # The request method or HTTP operation code to compare against that used by the client system under...
    requestURL: Optional[str] = None  # The value to use in a comparison against the request URL path string.
    resource: Optional[str] = None  # The type of the resource.  See the [resource list](resourcelist.html).
    response: Optional[str] = None  # continue | switchingProtocols | okay | created | accepted | nonAuthoritativeInformation | noConte...
    responseCode: Optional[str] = None  # The value of the HTTP response code to be tested.
    sourceId: Optional[str] = None  # Fixture to evaluate the XPath/JSONPath expression or the headerField  against.
    validateProfileId: Optional[str] = None  # The ID of the Profile to validate against.
    value: Optional[str] = None  # The value to compare to.
    requirement: Optional[List[BackboneElement]] = field(default_factory=list)  # Links or references providing traceability to the testing requirements for this assert.
    link: Optional[Any] = None  # Link or reference providing traceability to the testing requirement for this test.

@dataclass
class TestScriptSetupActionAssertRequirement:
    """
    TestScriptSetupActionAssertRequirement nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    link: Optional[Any] = None  # Link or reference providing traceability to the testing requirement for this test.

@dataclass
class TestScriptTest:
    """
    TestScriptTest nested class.
    """

    action: List[BackboneElement] = field(default_factory=list)  # Action would contain either an operation or an assertion.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    name: Optional[str] = None  # The name of this test used for tracking/logging purposes by test engines.
    description: Optional[str] = None  # A short description of the test used by test engines for tracking and reporting purposes.
    operation: Optional[Any] = None  # An operation would involve a REST request to a server.
    assert_: Optional[Any] = None  # Evaluates the results of previous operations to determine if the server under test behaves approp...

@dataclass
class TestScriptTestAction:
    """
    TestScriptTestAction nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    operation: Optional[Any] = None  # An operation would involve a REST request to a server.
    assert_: Optional[Any] = None  # Evaluates the results of previous operations to determine if the server under test behaves approp...

@dataclass
class TestScriptTeardown:
    """
    TestScriptTeardown nested class.
    """

    action: List[BackboneElement] = field(default_factory=list)  # The teardown action will only contain an operation.
    operation: Optional[Any] = None  # An operation would involve a REST request to a server.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class TestScriptTeardownAction:
    """
    TestScriptTeardownAction nested class.
    """

    operation: Optional[Any] = None  # An operation would involve a REST request to a server.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...


@dataclass
class TestScript(FHIRResource):
    """
    Enforces the minimum information set for the test script metadata required by HL7 and other organizations that share and publish test scripts
    """

    url: Optional[str] = None  # An absolute URI that is used to identify this test script when it is referenced in a specificatio...
    version: Optional[str] = None  # The identifier that is used to identify this version of the test script when it is referenced in ...
    name: Optional[str] = None  # A natural language name identifying the test script. This name should be usable as an identifier ...
    status: Optional[str] = None  # The status of this test script. Enables tracking the life-cycle of the content.
    experimental: Optional[bool] = None  # A Boolean value to indicate that this test script is authored for testing purposes (or education/...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    description: Optional[str] = None  # A free text natural language description of the test script from a consumer's perspective.
    resourceType: str = "TestScript"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this test script when it is represented in other for...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which is more current.
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the test script.
    date: Optional[str] = None  # The date (and optionally time) when the test script was last significantly changed. The date must...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the test script is intended to be used.
    purpose: Optional[str] = None  # Explanation of why this test script is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the test script and/or its contents. Copyright statements are g...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    origin: Optional[List[BackboneElement]] = field(default_factory=list)  # An abstract server used in operations within this test script in the origin element.
    destination: Optional[List[BackboneElement]] = field(default_factory=list)  # An abstract server used in operations within this test script in the destination element.
    metadata: Optional[BackboneElement] = None  # The required capability must exist and are assumed to function correctly on the FHIR server being...
    scope: Optional[List[BackboneElement]] = field(default_factory=list)  # The scope indicates a conformance artifact that is tested by the test(s) within this test case an...
    fixture: Optional[List[BackboneElement]] = field(default_factory=list)  # Fixture in the test script - by reference (uri). All fixtures are required for the test script to...
    profile: Optional[List[str]] = field(default_factory=list)  # Reference to the profile to be used for validation.
    variable: Optional[List[BackboneElement]] = field(default_factory=list)  # Variable is set based either on element value in response body or on header field value in the re...
    setup: Optional[BackboneElement] = None  # A series of required setup operations before tests are executed.
    test: Optional[List[BackboneElement]] = field(default_factory=list)  # A test in this script.
    teardown: Optional[BackboneElement] = None  # A series of operations required to clean up after all the tests are executed (successfully or oth...