# Copyright 2025 DNAi inc.

# Dual-licensed under the DNAi Free License v1.1 and the
# DNAi Commercial License v1.1.
# See the LICENSE files in the project root for details.


"""
FHIR R5 ValueSet resource.

Enforces the minimum information set for the value set metadata required by HL7 and other organizations that share and publish value sets
"""

from dataclasses import dataclass, field
from dnhealth.dnhealth_fhir.resources.base import FHIRResource
from dnhealth.dnhealth_fhir.types import BackboneElement, CodeableConcept, Coding, ContactDetail, Extension, Identifier, Period, RelatedArtifact, UsageContext
from typing import Any, List, Optional

@dataclass
class ValueSetCompose:
    """
    ValueSetCompose nested class.
    """

    include: List[BackboneElement] = field(default_factory=list)  # Include one or more codes from a code system or other value set(s).
    code: Optional[str] = None  # Specifies a code for the concept to be included or excluded.
    value: Optional[str] = None  # The text value for this designation.
    property: Optional[str] = None  # A code that identifies a property or a filter defined in the code system.
    op: Optional[str] = None  # The kind of operation to perform as a part of the filter criteria.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    lockedDate: Optional[str] = None  # The Locked Date is  the effective date that is used to determine the version of all referenced Co...
    inactive: Optional[bool] = None  # Whether inactive codes - codes that are not approved for current use - are in the value set. If i...
    system: Optional[str] = None  # An absolute URI which is the code system from which the selected codes come from.
    version: Optional[str] = None  # The version of the code system that the codes are selected from, or the special version '*' for a...
    concept: Optional[List[BackboneElement]] = field(default_factory=list)  # Specifies a concept to be included or excluded.
    display: Optional[str] = None  # The text to display to the user for this concept in the context of this valueset. If no display i...
    designation: Optional[List[BackboneElement]] = field(default_factory=list)  # Additional representations for this concept when used in this value set - other languages, aliase...
    language: Optional[str] = None  # The language this designation is defined for.
    use: Optional[Coding] = None  # A code that represents types of uses of designations.
    additionalUse: Optional[List[Coding]] = field(default_factory=list)  # Additional codes that detail how this designation would be used, if there is more than one use.
    filter: Optional[List[BackboneElement]] = field(default_factory=list)  # Select concepts by specifying a matching criterion based on the properties (including relationshi...
    valueSet: Optional[List[str]] = field(default_factory=list)  # Selects the concepts found in this value set (based on its value set definition). This is an abso...
    copyright: Optional[str] = None  # A copyright statement for the specific code system asserted by the containing ValueSet.compose.in...
    exclude: Optional[List[Any]] = field(default_factory=list)  # Exclude one or more codes from the value set based on code system filters and/or other value sets.

@dataclass
class ValueSetComposeInclude:
    """
    ValueSetComposeInclude nested class.
    """

    code: Optional[str] = None  # Specifies a code for the concept to be included or excluded.
    value: Optional[str] = None  # The text value for this designation.
    property: Optional[str] = None  # A code that identifies a property or a filter defined in the code system.
    op: Optional[str] = None  # The kind of operation to perform as a part of the filter criteria.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    system: Optional[str] = None  # An absolute URI which is the code system from which the selected codes come from.
    version: Optional[str] = None  # The version of the code system that the codes are selected from, or the special version '*' for a...
    concept: Optional[List[BackboneElement]] = field(default_factory=list)  # Specifies a concept to be included or excluded.
    display: Optional[str] = None  # The text to display to the user for this concept in the context of this valueset. If no display i...
    designation: Optional[List[BackboneElement]] = field(default_factory=list)  # Additional representations for this concept when used in this value set - other languages, aliase...
    language: Optional[str] = None  # The language this designation is defined for.
    use: Optional[Coding] = None  # A code that represents types of uses of designations.
    additionalUse: Optional[List[Coding]] = field(default_factory=list)  # Additional codes that detail how this designation would be used, if there is more than one use.
    filter: Optional[List[BackboneElement]] = field(default_factory=list)  # Select concepts by specifying a matching criterion based on the properties (including relationshi...
    valueSet: Optional[List[str]] = field(default_factory=list)  # Selects the concepts found in this value set (based on its value set definition). This is an abso...
    copyright: Optional[str] = None  # A copyright statement for the specific code system asserted by the containing ValueSet.compose.in...

@dataclass
class ValueSetComposeIncludeConcept:
    """
    ValueSetComposeIncludeConcept nested class.
    """

    code: Optional[str] = None  # Specifies a code for the concept to be included or excluded.
    value: Optional[str] = None  # The text value for this designation.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    display: Optional[str] = None  # The text to display to the user for this concept in the context of this valueset. If no display i...
    designation: Optional[List[BackboneElement]] = field(default_factory=list)  # Additional representations for this concept when used in this value set - other languages, aliase...
    language: Optional[str] = None  # The language this designation is defined for.
    use: Optional[Coding] = None  # A code that represents types of uses of designations.
    additionalUse: Optional[List[Coding]] = field(default_factory=list)  # Additional codes that detail how this designation would be used, if there is more than one use.

@dataclass
class ValueSetComposeIncludeConceptDesignation:
    """
    ValueSetComposeIncludeConceptDesignation nested class.
    """

    value: Optional[str] = None  # The text value for this designation.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    language: Optional[str] = None  # The language this designation is defined for.
    use: Optional[Coding] = None  # A code that represents types of uses of designations.
    additionalUse: Optional[List[Coding]] = field(default_factory=list)  # Additional codes that detail how this designation would be used, if there is more than one use.

@dataclass
class ValueSetComposeIncludeFilter:
    """
    ValueSetComposeIncludeFilter nested class.
    """

    property: Optional[str] = None  # A code that identifies a property or a filter defined in the code system.
    op: Optional[str] = None  # The kind of operation to perform as a part of the filter criteria.
    value: Optional[str] = None  # The match value may be either a code defined by the system, or a string value, which is a regex m...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class ValueSetExpansion:
    """
    ValueSetExpansion nested class.
    """

    timestamp: Optional[str] = None  # The time at which the expansion was produced by the expanding system.
    name: Optional[str] = None  # Name of the input parameter to the $expand operation; may be a server-assigned name for additiona...
    code: Optional[str] = None  # A code that is used to identify the property. The code is used in ValueSet.expansion.contains.pro...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    identifier: Optional[str] = None  # An identifier that uniquely identifies this expansion of the valueset, based on a unique combinat...
    next: Optional[str] = None  # As per paging Search results, the next URLs are opaque to the client, have no dictated structure,...
    total: Optional[int] = None  # The total number of concepts in the expansion. If the number of concept nodes in this resource is...
    offset: Optional[int] = None  # If paging is being used, the offset at which this resource starts.  I.e. this resource is a parti...
    parameter: Optional[List[BackboneElement]] = field(default_factory=list)  # A parameter that controlled the expansion process. These parameters may be used by users of expan...
    value: Optional[Any] = None  # The value of the parameter.
    property: Optional[List[BackboneElement]] = field(default_factory=list)  # A property defines an additional slot through which additional information can be provided about ...
    uri: Optional[str] = None  # Reference to the formal meaning of the property. One possible source of meaning is the [Concept P...
    contains: Optional[List[BackboneElement]] = field(default_factory=list)  # The codes that are contained in the value set expansion.
    system: Optional[str] = None  # An absolute URI which is the code system in which the code for this item in the expansion is defi...
    abstract: Optional[bool] = None  # If true, this entry is included in the expansion for navigational purposes, and the user cannot s...
    inactive: Optional[bool] = None  # If the concept is inactive in the code system that defines it. Inactive codes are those that are ...
    version: Optional[str] = None  # The version of the code system from this code was taken. Note that a well-maintained code system ...
    display: Optional[str] = None  # The recommended display for this item in the expansion.
    designation: Optional[List[Any]] = field(default_factory=list)  # Additional representations for this item - other languages, aliases, specialized purposes, used f...
    subProperty: Optional[List[BackboneElement]] = field(default_factory=list)  # A subproperty value for this concept.

@dataclass
class ValueSetExpansionParameter:
    """
    ValueSetExpansionParameter nested class.
    """

    name: Optional[str] = None  # Name of the input parameter to the $expand operation; may be a server-assigned name for additiona...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    value: Optional[Any] = None  # The value of the parameter.

@dataclass
class ValueSetExpansionProperty:
    """
    ValueSetExpansionProperty nested class.
    """

    code: Optional[str] = None  # A code that is used to identify the property. The code is used in ValueSet.expansion.contains.pro...
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    uri: Optional[str] = None  # Reference to the formal meaning of the property. One possible source of meaning is the [Concept P...

@dataclass
class ValueSetExpansionContains:
    """
    ValueSetExpansionContains nested class.
    """

    value: Optional[Any] = None  # The value of this property.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    system: Optional[str] = None  # An absolute URI which is the code system in which the code for this item in the expansion is defi...
    abstract: Optional[bool] = None  # If true, this entry is included in the expansion for navigational purposes, and the user cannot s...
    inactive: Optional[bool] = None  # If the concept is inactive in the code system that defines it. Inactive codes are those that are ...
    version: Optional[str] = None  # The version of the code system from this code was taken. Note that a well-maintained code system ...
    code: Optional[str] = None  # The code for this item in the expansion hierarchy. If this code is missing the entry in the hiera...
    display: Optional[str] = None  # The recommended display for this item in the expansion.
    designation: Optional[List[Any]] = field(default_factory=list)  # Additional representations for this item - other languages, aliases, specialized purposes, used f...
    property: Optional[List[BackboneElement]] = field(default_factory=list)  # A property value for this concept.
    subProperty: Optional[List[BackboneElement]] = field(default_factory=list)  # A subproperty value for this concept.
    contains: Optional[List[Any]] = field(default_factory=list)  # Other codes and entries contained under this entry in the hierarchy.

@dataclass
class ValueSetExpansionContainsProperty:
    """
    ValueSetExpansionContainsProperty nested class.
    """

    code: Optional[str] = None  # A code that is a reference to ValueSet.expansion.property.code.
    value: Optional[Any] = None  # The value of this property.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    subProperty: Optional[List[BackboneElement]] = field(default_factory=list)  # A subproperty value for this concept.

@dataclass
class ValueSetExpansionContainsPropertySubProperty:
    """
    ValueSetExpansionContainsPropertySubProperty nested class.
    """

    code: Optional[str] = None  # A code that is a reference to ValueSet.expansion.property.code.
    value: Optional[Any] = None  # The value of this subproperty.
    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...

@dataclass
class ValueSetScope:
    """
    ValueSetScope nested class.
    """

    id: Optional[str] = None  # Unique id for the element within a resource (for internal references). This may be any string val...
    extension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    modifierExtension: Optional[List[Extension]] = field(default_factory=list)  # May be used to represent additional information that is not part of the basic definition of the e...
    inclusionCriteria: Optional[str] = None  # Criteria describing which concepts or codes should be included and why.
    exclusionCriteria: Optional[str] = None  # Criteria describing which concepts or codes should be excluded and why.


@dataclass
class ValueSet(FHIRResource):
    """
    Enforces the minimum information set for the value set metadata required by HL7 and other organizations that share and publish value sets
    """

    url: Optional[str] = None  # An absolute URI that is used to identify this value set when it is referenced in a specification,...
    version: Optional[str] = None  # The identifier that is used to identify this version of the value set when it is referenced in a ...
    title: Optional[str] = None  # A short, descriptive, user-friendly title for the value set.
    status: Optional[str] = None  # The status of this value set. Enables tracking the life-cycle of the content. The status of the v...
    experimental: Optional[bool] = None  # A Boolean value to indicate that this value set is authored for testing purposes (or education/ev...
    description: Optional[str] = None  # A free text natural language description of the value set from a consumer's perspective. The text...
    resourceType: str = "ValueSet"
    identifier: Optional[List[Identifier]] = field(default_factory=list)  # A formal identifier that is used to identify this value set when it is represented in other forma...
    versionAlgorithm: Optional[Any] = None  # Indicates the mechanism used to compare versions to determine which ValueSet is more current.
    name: Optional[str] = None  # A natural language name identifying the value set. This name should be usable as an identifier fo...
    date: Optional[str] = None  # The date (and optionally time) when the value set metadata or content logical definition (.compos...
    publisher: Optional[str] = None  # The name of the organization or individual responsible for the release and ongoing maintenance of...
    contact: Optional[List[ContactDetail]] = field(default_factory=list)  # Contact details to assist a user in finding and communicating with the publisher.
    useContext: Optional[List[UsageContext]] = field(default_factory=list)  # The content was developed with a focus and intent of supporting the contexts that are listed. The...
    jurisdiction: Optional[List[CodeableConcept]] = field(default_factory=list)  # A legal or geographic region in which the value set is intended to be used.
    immutable: Optional[bool] = None  # If this is set to 'true', then no new versions of the content logical definition can be created. ...
    purpose: Optional[str] = None  # Explanation of why this value set is needed and why it has been designed as it has.
    copyright: Optional[str] = None  # A copyright statement relating to the value set and/or its contents. Copyright statements are gen...
    copyrightLabel: Optional[str] = None  # A short string (<50 characters), suitable for inclusion in a page footer that identifies the copy...
    approvalDate: Optional[str] = None  # The date on which the resource content was approved by the publisher. Approval happens once when ...
    lastReviewDate: Optional[str] = None  # The date on which the resource content was last reviewed. Review happens periodically after appro...
    effectivePeriod: Optional[Period] = None  # The period during which the ValueSet content was or is planned to be in active use.
    topic: Optional[List[CodeableConcept]] = field(default_factory=list)  # Descriptions related to the content of the ValueSet. Topics provide a high-level categorization a...
    author: Optional[List[ContactDetail]] = field(default_factory=list)  # An individiual or organization primarily involved in the creation and maintenance of the ValueSet.
    editor: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization primarily responsible for internal coherence of the ValueSet.
    reviewer: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be primarily responsible for review of...
    endorser: Optional[List[ContactDetail]] = field(default_factory=list)  # An individual or organization asserted by the publisher to be responsible for officially endorsin...
    relatedArtifact: Optional[List[RelatedArtifact]] = field(default_factory=list)  # Related artifacts such as additional documentation, justification, dependencies, bibliographic re...
    compose: Optional[BackboneElement] = None  # A set of criteria that define the contents of the value set by including or excluding codes selec...
    expansion: Optional[BackboneElement] = None  # A value set can also be \"expanded\", where the value set is turned into a simple collection of e...
    scope: Optional[BackboneElement] = None  # Description of the semantic space the Value Set Expansion is intended to cover and should further...
